
[functions.baqueano-status]
enabled = true
verify_jwt = false
import_map = "./functions/baqueano-status/deno.json"
entrypoint = "./functions/baqueano-status/index.ts"

[functions.baqueano-ai]
enabled = true
verify_jwt = false
import_map = "./functions/baqueano-ai/deno.json"
entrypoint = "./functions/baqueano-ai/index.ts"
