-- ============================================================================
-- 🧭 BAQUEANO — IMPORTACIÓN MARENA: PLANES DE MANEJO (GENERADO — NO editar a mano)
-- 🎯 Fuente oficial trazable. ⚙️ Generado por website/scripts/import-marena-*.mjs; idempotente.
-- 📦 42 sentencias. Importar ≠ publicar: nada queda is_published = true.
-- ⚠️ Requiere 20261005090000_environmental_marena_module.sql. Ejecutar en UNA transacción y SOLO con autorización.
-- ============================================================================
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-reserva-natural-tisey-la-estanzuela', 'reserva-natural-tisey-la-estanzuela', 'Plan de Manejo Reserva Natural Tisey la Estanzuela', 'Plan de Manejo Reserva Natural Tisey la Estanzuela', 'https://www.marena.gob.ni/wp-content/uploads/2022/03/Plan-Manejo-Reserva-Natural-Tisey-Estanzuela.pdf', null, 'Resolución Ministerial No. 313-2021', 'La Gaceta, Diario Oficial No. 50 (martes 15 de marzo de 2022)', 'https://www.marena.gob.ni/wp-content/uploads/2023/11/R.M.-313-2021.-Reserva-Natural-Tisey-la-Estanzuela.pdf', 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-reserva-natural-tisey-la-estanzuela/', '2026-10-05'::timestamptz, 'partial', null, 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-marena-reserva-natural-serrania-de-dipilto-y-jalapa', 'reserva-natural-serrania-de-dipilto-y-jalapa', 'Plan de Manejo Reserva Natural Serranía de Dipilto y Jalapa', 'Plan de Manejo Reserva Natural Serranía de Dipilto y Jalapa', 'https://www.marena.gob.ni/wp-content/uploads/2022/04/Plan-Manejo-Reserva-Natural-Serrania-de-Dipilto-y-Jalapa.pdf', null, 'Resolución Ministerial No. 242-2021', 'La Gaceta, Diario Oficial No. 50 (martes 15 de marzo de 2022)', 'https://www.marena.gob.ni/wp-content/uploads/2023/11/242-2021.-Reserva-Natural-Serrania-Dipilto-Y-jalapa.pdf', 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-reserva-natural-serrania-de-dipilto-y-jalapa/', '2026-10-05'::timestamptz, 'partial', null, 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-marena-reserva-natural-cerro-tomabu', 'reserva-natural-cerro-tomabu', 'Plan de Manejo Reserva Natural Cerro Tomabu', 'Plan de Manejo Reserva Natural Cerro Tomabu', 'https://www.marena.gob.ni/wp-content/uploads/2022/04/Plan-Manejo-Reserva-Natural-Cerro-Tomabu.pdf', null, null, null, 'https://www.marena.gob.ni/wp-content/uploads/2023/11/R.M.-Reserva-Natural-Cerro-Tomabu.pdf', 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-reserva-natural-cerro-tomabu/', '2026-10-05'::timestamptz, 'partial', 'Hay Gaceta enlazada, pero el número de resolución no se pudo confirmar en su texto: approval_reference NULL.', 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-marena-reserva-natural-cerro-kuskawas', 'reserva-natural-cerro-kuskawas', 'Plan de Manejo Reserva Natural Cerro kuskawas', 'Plan de Manejo Reserva Natural Cerro kuskawas', 'https://www.marena.gob.ni/wp-content/uploads/2022/04/PlanManejo-Reserva-Natural-Cerro-kuskawas.pdf', null, 'Resolución Ministerial No. 293-2021', 'La Gaceta, Diario Oficial No. 51 (miercoles 16 de marzo de 2022)', 'https://www.marena.gob.ni/wp-content/uploads/2023/11/293-2021.-Cerro-Kuskawas.pdf', 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-reserva-natural-cerro-kuskawas/', '2026-10-05'::timestamptz, 'partial', null, 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-marena-reserva-natural-alamikamba', 'reserva-natural-alamikamba', 'Plan de Manejo Reserva Natural Alamikamba', 'Plan de Manejo Reserva Natural Alamikamba', 'https://www.marena.gob.ni/wp-content/uploads/2022/09/Plan-de-Manejo-Reserva-Natural-Alamikamba.pdf', null, null, null, null, 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-reserva-natural-alamikamba/', '2026-10-05'::timestamptz, 'partial', null, 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-marena-complejo-volcanico-san-cristobal', 'complejo-volcanico-san-cristobal', 'Plan de Manejo Complejo Volcánico San Cristobal', 'Plan de Manejo Complejo Volcánico San Cristobal', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/6-Plan-de-Manejo-Complejo-Volcanico-San-Cristobal.pdf', null, null, null, null, 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-complejo-volcanico-san-cristobal/', '2026-10-05'::timestamptz, 'partial', 'El título del plan no indica la categoría legal: official_category queda NULL (por confirmar).', 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-marena-monumento-historico-concepcion-de-maria', 'monumento-historico-concepcion-de-maria', 'Plan de Manejo Monumento Historico Concepción de María', 'Plan de Manejo Monumento Historico Concepción de María', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/7-Plan-de-Manejo-Monumento-Historico-Concepcion-de-Maria.pdf', null, null, null, null, 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-monumento-historico-concepcion-de-maria/', '2026-10-05'::timestamptz, 'partial', null, 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-marena-monumento-nacional-archipielago-solentiname', 'monumento-nacional-archipielago-solentiname', 'Plan de Manejo Monumento Nacional Archipiélago Solentiname', 'Plan de Manejo Monumento Nacional Archipiélago Solentiname', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/8-Plan-de-Manejo-Monumento-Nacional-Archipielago-Solentiname.pdf', null, null, null, null, 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-monumento-nacional-archipielago-solentiname/', '2026-10-05'::timestamptz, 'partial', null, 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-marena-monumento-nacional-canon-de-somoto', 'monumento-nacional-canon-de-somoto', 'Plan de Manejo Monumento Nacional Cañón de Somoto', 'Plan de Manejo Monumento Nacional Cañón de Somoto', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/9-Plan-de-Manejo-Monumento-Nacional-Canon-de-Somoto.pdf', null, 'Resolución Ministerial No. 251-2021', 'La Gaceta, Diario Oficial No. 50 (martes 15 de marzo de 2022)', 'https://www.marena.gob.ni/wp-content/uploads/2023/11/251-2021.-Monumento-Nacional-Canon-de-Somoto.pdf', 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-monumento-nacional-canon-de-somoto/', '2026-10-05'::timestamptz, 'partial', null, 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-marena-paisaje-terrestre-mesas-de-miraflor', 'paisaje-terrestre-mesas-de-miraflor', 'Plan de Manejo Paisaje Terrestre Mesas de Miraflor', 'Plan de Manejo Paisaje Terrestre Mesas de Miraflor', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/10-Plan-de-Manejo-Paisaje-Terrestre-Mesas-de-Miraflor.pdf', null, null, null, null, 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-paisaje-terrestre-mesas-de-miraflor/', '2026-10-05'::timestamptz, 'partial', null, 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-marena-parque-nacional-archipielago-zapatera', 'parque-nacional-archipielago-zapatera', 'Plan de Manejo Parque Nacional Archipielago Zapatera', 'Plan de Manejo Parque Nacional Archipielago Zapatera', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/11-Plan-de-Manejo-Parque-Nacional-Archipielago-Zapatera.pdf', null, null, null, null, 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-parque-nacional-archipielago-zapatera/', '2026-10-05'::timestamptz, 'partial', null, 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-parque-nacional-saslaya', 'parque-nacional-saslaya', 'Plan de Manejo Parque Nacional Saslaya', 'Plan de Manejo Parque Nacional Saslaya', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/12-Plan-de-Manejo-Parque-Nacional-Saslaya.pdf', null, null, null, 'https://www.marena.gob.ni/wp-content/uploads/2023/11/R.M.-327-2022.-Reserva-Natural-Cerro-Saslaya.pdf', 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-parque-nacional-saslaya/', '2026-10-05'::timestamptz, 'conflicting', 'Hay Gaceta enlazada, pero el número de resolución no se pudo confirmar en su texto: approval_reference NULL. Conflicto: MARENA titula el plan "Parque Nacional Saslaya" y el archivo de la Gaceta dice "Reserva Natural Cerro Saslaya".', 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-marena-parque-nacional-volcan-maderas', 'parque-nacional-volcan-maderas', 'Plan de Manejo Parque Nacional Volcán Maderas', 'Plan de Manejo Parque Nacional Volcán Maderas', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/13-Plan-de-Manejo-Parque-Nacional-Volcan-Maderas.pdf', null, 'Resolución Ministerial No. 168-2021', 'La Gaceta, Diario Oficial No. 231 (miercoles 15 de diciembre de 2021)', 'https://www.marena.gob.ni/wp-content/uploads/2023/11/168-2021.-Actualizacion-pln-general-del-area-protegida-parque-nacional-Volcan-Maderas..pdf', 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-parque-nacional-volcan-maderas/', '2026-10-05'::timestamptz, 'partial', null, 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-parque-nacional-volcan-masaya', 'parque-nacional-volcan-masaya', 'Plan de Manejo Parque Nacional Volcán Masaya', 'Plan de Manejo Parque Nacional Volcán Masaya', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/14-Plan-de-Manejo-Parque-Nacional-Volcan-Masaya.pdf', null, null, null, null, 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-parque-nacional-volcan-masaya/', '2026-10-05'::timestamptz, 'partial', null, 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-marena-refugio-vida-silvestre-istian', 'refugio-vida-silvestre-istian', 'Plan de Manejo Refugio Vida Silvestre Istián', 'Plan de Manejo Refugio Vida Silvestre Istián', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/15-Plan-de-Manejo-Refugio-Vida-Silvestre-Istian-Pena.pdf', null, 'Resolución Ministerial No. 159-2021', 'La Gaceta, Diario Oficial No. 149 (miercoles 11 de agosto de 2021)', 'https://www.marena.gob.ni/wp-content/uploads/2023/11/159-2021.-Plan-de-Manejo-del-area-protegida-Refugio-de-vida-Silvestre-Pena-Inculta-Humedal-Istian.pdf', 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-refugio-vida-silvestre-istian/', '2026-10-05'::timestamptz, 'partial', null, 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-marena-refugio-vida-silvestre-rio-escalante', 'refugio-vida-silvestre-rio-escalante', 'Plan de Manejo Refugio Vida Silvestre Río Escalante', 'Plan de Manejo Refugio Vida Silvestre Río Escalante', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/16-Plan-de-Manejo-Refugio-Vida-Silvestre-Rio-Escalante.pdf', null, null, null, null, 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-refugio-vida-silvestre-rio-escalante/', '2026-10-05'::timestamptz, 'partial', null, 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-refugio-de-vida-silvestre-rio-san-juan', 'refugio-vida-silvestre-rio-san-juan', 'Plan de Manejo Refugio Vida Silvestre Río San Juan', 'Plan de Manejo Refugio Vida Silvestre Río San Juan', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/17-Plan-de-Manejo-Refugio-Vida-Silvestre-Rio-San-Juan.pdf', null, null, null, null, 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-refugio-vida-silvestre-rio-san-juan/', '2026-10-05'::timestamptz, 'partial', null, 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-marena-reserva-recursos-geneticos-apacunca', 'reserva-recursos-geneticos-apacunca', 'Plan de Manejo Reserva Recursos Geneticos Apacunca', 'Plan de Manejo Reserva Recursos Geneticos Apacunca', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/18-Plan-de-Manejo-Reserva-Recursos-Geneticos-Apacunca.pdf', null, 'Resolución Ministerial No. 203-2021', 'La Gaceta, Diario Oficial No. 231 (miercoles 15 de diciembre de 2021)', 'https://www.marena.gob.ni/wp-content/uploads/2023/11/203-2021.-Actualizacion-Plan-General-de-Manejo-del-Area-Protegida-Recurss-Geneticos-de-Apacunca.pdf', 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-reserva-recursos-geneticos-apacunca/', '2026-10-05'::timestamptz, 'partial', null, 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-marena-reserva-natural-cerro-arenal', 'reserva-natural-cerro-arenal', 'Plan de Manejo Reserva Natural Cerro Arenal', 'Plan de Manejo Reserva Natural Cerro Arenal', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/19-Plan-de-Manejo-Reserva-Natural-Cerro-Arenal.pdf', null, null, null, null, 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-reserva-natural-cerro-arenal/', '2026-10-05'::timestamptz, 'partial', null, 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-marena-reserva-natural-cerro-cumaica', 'reserva-natural-cerro-cumaica', 'Plan de Manejo Reserva Natural Cerro Cumaica', 'Plan de Manejo Reserva Natural Cerro Cumaica', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/20-Plan-de-Manejo-Reserva-Natural-Cerro-Cumaica.pdf', null, 'Resolución Ministerial No. 243-2021', 'La Gaceta, Diario Oficial No. 232 (jueves 16 de diciembre de 2021)', 'https://www.marena.gob.ni/wp-content/uploads/2023/11/243-2021.-Cerro-Cumaica-Cerro-Alegre.pdf', 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-reserva-natural-cerro-cumaica/', '2026-10-05'::timestamptz, 'partial', null, 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-reserva-natural-cerro-datanli-el-diablo', 'reserva-natural-cerro-datanli-el-diablo', 'Plan de Manejo Reserva Natural Cerro Datanlí El Diablo', 'Plan de Manejo Reserva Natural Cerro Datanlí El Diablo', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/21-Plan-de-Manejo-Reserva-Natural-Cerro-Datanli-El-Diablo.pdf', null, null, null, null, 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-reserva-natural-cerro-datanli-el-diablo/', '2026-10-05'::timestamptz, 'partial', null, 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-marena-reserva-natural-cerro-kilambe', 'reserva-natural-cerro-kilambe', 'Plan de Manejo Reserva Natural Cerro Kilambé', 'Plan de Manejo Reserva Natural Cerro Kilambé', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/22-Plan-de-Manejo-Reserva-Natural-Cerro-Kilambe.pdf', null, 'Resolución Ministerial No. 295-2021', 'La Gaceta, Diario Oficial No. 62 (jueves 31 de marzo de 2022)', 'https://www.marena.gob.ni/wp-content/uploads/2023/11/295-2021.-Reserva-Natural-Cerro-Kilambe.pdf', 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-reserva-natural-cerro-kilambe/', '2026-10-05'::timestamptz, 'partial', null, 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-reserva-mombachito-cerro-la-vieja', 'reserva-natural-cerro-mombachito-la-vieja', 'Plan de Manejo Reserva Natural Cerro Mombachito La Vieja', 'Plan de Manejo Reserva Natural Cerro Mombachito La Vieja', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/23-Plan-de-Manejo-Reserva-Natural-Cerro-Mombachito-La-Vieja.pdf', null, 'Resolución Ministerial No. 296-2021', 'La Gaceta, Diario Oficial No. 62 (jueves 31 de marzo de 2022)', 'https://www.marena.gob.ni/wp-content/uploads/2023/11/296-2021.-Reserva-Natural-Mombachito-la-Vieja.pdf', 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-reserva-natural-cerro-mombachito-la-vieja/', '2026-10-05'::timestamptz, 'partial', null, 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-reserva-natural-cerro-musun', 'reserva-natural-cerro-musun', 'Plan de Manejo Reserva Natural Cerro Musún', 'Plan de Manejo Reserva Natural Cerro Musún', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/24-Plan-de-Manejo-Reserva-Natural-Cerro-Musun.pdf', null, null, null, null, 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-reserva-natural-cerro-musun/', '2026-10-05'::timestamptz, 'partial', null, 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-marena-reserva-natural-cerro-quiabuc-las-brisas', 'reserva-natural-cerro-quiabuc-las-brisas', 'Plan de Manejo Reserva Natural Cerro Quiabúc Las Brisas', 'Plan de Manejo Reserva Natural Cerro Quiabúc Las Brisas', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/25-Plan-de-Manejo-Reserva-Natural-Cerro-Quiabuc-Las-Brisas.pdf', null, null, null, 'https://www.marena.gob.ni/wp-content/uploads/2023/11/R.M.-Reserva-Natural-Quiabuc-las-brisas.pdf', 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-reserva-natural-cerro-quiabuc-las-brisas/', '2026-10-05'::timestamptz, 'partial', 'Hay Gaceta enlazada, pero el número de resolución no se pudo confirmar en su texto: approval_reference NULL.', 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-marena-reserva-natural-cerro-silva', 'reserva-natural-cerro-silva', 'Plan de Manejo Reserva Natural Cerro Silva', 'Plan de Manejo Reserva Natural Cerro Silva', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/26-Plan-de-Manejo-Reserva-Natural-Cerro-Silva.pdf', null, null, null, null, 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-reserva-natural-cerro-silva/', '2026-10-05'::timestamptz, 'partial', null, 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-marena-reserva-natural-cerros-de-yali', 'reserva-natural-cerros-de-yali', 'Plan de Manejo Reserva Natural Cerros de Yalí', 'Plan de Manejo Reserva Natural Cerros de Yalí', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/27-Plan-de-Manejo-Reserva-Natural-Cerros-de-Yali.pdf', null, null, null, null, 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-reserva-natural-cerros-de-yali/', '2026-10-05'::timestamptz, 'partial', null, 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-marena-reserva-natural-complejo-volcanico-telica', 'reserva-natural-complejo-volcanico-telica', 'Plan de Manejo Reserva Natural Complejo Volcánico Telica', 'Plan de Manejo Reserva Natural Complejo Volcánico Telica', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/28-Plan-de-Manejo-Reserva-Natural-Complejo-Volcanico-Telica-Rota.pdf', null, null, null, null, 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-reserva-natural-complejo-volcanico-telica/', '2026-10-05'::timestamptz, 'partial', null, 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-marena-reserva-natural-delta-estero-real', 'reserva-natural-delta-estero-real', 'Plan de Manejo Reserva Natural Delta Estero Real', 'Plan de Manejo Reserva Natural Delta Estero Real', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/29-Plan-de-Manejo-Reserva-Natural-Delta-del-Estero-Real.pdf', null, 'Resolución Ministerial No. 234-2021', 'La Gaceta, Diario Oficial No. 232 (jueves 16 de diciembre de 2021)', 'https://www.marena.gob.ni/wp-content/uploads/2023/11/234-2021-Actualizacion-Plan-General-de-Manejo-del-Area-Protegida-Reserva-Natural-Delta-de-Estero-Real.pdf', 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-reserva-natural-delta-estero-real/', '2026-10-05'::timestamptz, 'partial', null, 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-estero-padre-ramos', 'reserva-natural-estero-padre-ramos', 'Plan de Manejo Reserva Natural Estero Padre Ramos', 'Plan de Manejo Reserva Natural Estero Padre Ramos', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/30-Plan-de-Manejo-Reserva-Natural-Estero-Padre-Ramos.pdf', null, 'Resolución Ministerial No. 202-2021', 'La Gaceta, Diario Oficial No. 231 (miercoles 15 de diciembre de 2021)', 'https://www.marena.gob.ni/wp-content/uploads/2023/11/202-2021.-Actualizacion-del-plan-general-de-manejo-del-area-protegida-Reserva-Natural-Padre-Ramos.pdf', 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-reserva-natural-estero-padre-ramos/', '2026-10-05'::timestamptz, 'partial', null, 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-marena-reserva-natural-lagunetas-mecatepe', 'reserva-natural-lagunetas-mecatepe', 'Plan de Manejo Reserva Natural Lagunetas Mecatepe', 'Plan de Manejo Reserva Natural Lagunetas Mecatepe', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/31-Plan-de-Manejo-Reserva-Natural-Lagunetas-Mecatepe.pdf', null, null, null, null, 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-reserva-natural-lagunetas-mecatepe/', '2026-10-05'::timestamptz, 'partial', null, 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-marena-reserva-natural-isla-juan-venado', 'reserva-natural-isla-juan-venado', 'Plan de Manejo Reserva Natural Isla Juan Venado', 'Plan de Manejo Reserva Natural Isla Juan Venado', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/32-Plan-de-Manejo-Reserva-Natural-Isla-Juan-Venado-1.pdf', null, null, null, null, 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-reserva-natural-isla-juan-venado/', '2026-10-05'::timestamptz, 'partial', null, 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-reserva-natural-laguna-de-apoyo', 'reserva-natural-laguna-apoyo', 'Plan de Manejo Reserva Natural Laguna Apoyo', 'Plan de Manejo Reserva Natural Laguna Apoyo', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/33-Plan-de-Manejo-Reserva-Natural-Laguna-Apoyo.pdf', null, 'Resolución Ministerial No. 001-2010', 'La Gaceta, Diario Oficial No. 55 (viernes 19 de marzo de 2010)', 'https://www.marena.gob.ni/wp-content/uploads/2023/11/R.M.-001-2010-Aprobacion-Plan-de-Manejo-Laguna-de-Poyo.pdf', 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-reserva-natural-laguna-apoyo/', '2026-10-05'::timestamptz, 'partial', null, 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-marena-reserva-natural-laguna-asososca', 'reserva-natural-laguna-asososca', 'Plan de Manejo Reserva Natural Laguna Asososca', 'Plan de Manejo Reserva Natural Laguna Asososca', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/34-Plan-de-Manejo-Reserva-Natural-Laguna-Asososca.pdf', null, null, null, null, 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-reserva-natural-laguna-asososca/', '2026-10-05'::timestamptz, 'partial', null, 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-marena-reserva-natural-laguna-tiscapa', 'reserva-natural-laguna-tiscapa', 'Plan de Manejo Reserva Natural Laguna Tiscapa', 'Plan de Manejo Reserva Natural Laguna Tiscapa', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/35-Plan-de-Manejo-Reserva-Natural-Laguna-Tiscapa.pdf', null, null, null, null, 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-reserva-natural-laguna-tiscapa/', '2026-10-05'::timestamptz, 'partial', null, 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-marena-reserva-natural-llanos-limbaica', 'reserva-natural-llanos-limbaica', 'Plan de Manejo Reserva Natural Llanos Limbaica', 'Plan de Manejo Reserva Natural Llanos Limbaica', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/36-Plan-de-Manejo-Reserva-Natural-Llanos-Limbaica.pdf', null, null, null, null, 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-reserva-natural-llanos-limbaica/', '2026-10-05'::timestamptz, 'partial', null, 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-reserva-natural-macizo-de-penas-blancas', 'reserva-natural-macizo-penas-blancas', 'Plan de Manejo Reserva Natural Macizo Peñas Blancas', 'Plan de Manejo Reserva Natural Macizo Peñas Blancas', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/37-Plan-de-Manejo-Reserva-Natural-Macizo-Penas-Blancas.pdf', null, 'Resolución Ministerial No. 271-2021', 'La Gaceta, Diario Oficial No. 232 (jueves 16 de diciembre de 2021)', 'https://www.marena.gob.ni/wp-content/uploads/2023/11/271-2021.-Mazizo-de-penas-blancas.pdf', 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-reserva-natural-macizo-penas-blancas/', '2026-10-05'::timestamptz, 'partial', null, 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-marena-reserva-natural-serrania-amerrisque', 'reserva-natural-serrania-amerrisque', 'Plan de Manejo Reserva Natural Serrania Amerrisque', 'Plan de Manejo Reserva Natural Serrania Amerrisque', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/38-Plan-de-Manejo-Reserva-Natural-Serrania-Amerrisque.pdf', null, 'Resolución Ministerial No. 138-2021', 'La Gaceta, Diario Oficial No. 149 (miercoles 11 de agosto de 2021)', 'https://www.marena.gob.ni/wp-content/uploads/2023/11/138-2021.-Plan-de-manejo-del-area-protegida-Reserva-Natural-Serrania-de-amerrisque.pdf', 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-reserva-natural-serrania-amerrisque/', '2026-10-05'::timestamptz, 'partial', null, 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-marena-reserva-natural-serranias-tepesomoto', 'reserva-natural-serranias-tepesomoto', 'Plan de Manejo Reserva Natural Serranias Tepesomoto', 'Plan de Manejo Reserva Natural Serranias Tepesomoto', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/39-Plan-de-Manejo-Reserva-Natural-Serranias-Tepesomoto.pdf', null, null, null, 'https://www.marena.gob.ni/wp-content/uploads/2023/11/R.M.-301.-Plan-de-Manejo-Tepesomoto-y-Pataste..pdf', 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-reserva-natural-serranias-tepesomoto/', '2026-10-05'::timestamptz, 'partial', 'Hay Gaceta enlazada, pero el número de resolución no se pudo confirmar en su texto: approval_reference NULL.', 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-marena-reserva-natural-volcan-concepcion', 'reserva-natural-volcan-concepcion', 'Plan de Manejo Reserva Natural Volcán Concepción', 'Plan de Manejo Reserva Natural Volcán Concepción', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/40-Plan-de-Manejo-Reserva-Natural-Volcan-Concepcion.pdf', null, 'Resolución Ministerial No. 157-2021', 'La Gaceta, Diario Oficial No. 149 (miercoles 11 de agosto de 2021)', 'https://www.marena.gob.ni/wp-content/uploads/2023/11/157-2021.-Plan-de-Manejo-del-area-protegida-Reserva-Natural-Volcan-Concepcion.pdf', 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-reserva-natural-volcan-concepcion/', '2026-10-05'::timestamptz, 'partial', null, 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-marena-reserva-natural-volcan-cosiguina', 'reserva-natural-volcan-cosiguina', 'Plan de Manejo Reserva Natural Volcán Cosigüina', 'Plan de Manejo Reserva Natural Volcán Cosigüina', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/41-Plan-de-Manejo-Reserva-Natural-Volcan-Cosiguina.pdf', null, 'Resolución Ministerial No. 102-2021', 'La Gaceta, Diario Oficial No. 155 (jueves 19 de agosto de 2021)', 'https://www.marena.gob.ni/wp-content/uploads/2023/11/102-2021.-Plan-de-Manejo-del-area-protegida-Reserva-Natural-Volcan-Cosiguina..pdf', 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-reserva-natural-volcan-cosiguina/', '2026-10-05'::timestamptz, 'partial', null, 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
insert into public.management_plans (place_id, area_key, title, title_as_published, document_url, document_qr_url, approval_reference, gazette_reference, gazette_url, source_name, source_url, verified_at, status, notes, created_by, updated_by)
values ('pl-marena-reserva-natural-volcan-mombacho', 'reserva-natural-volcan-mombacho', 'Plan de Manejo Reserva Natural Volcán Mombacho', 'Plan de Manejo Reserva Natural Volcán Mombacho', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/42-Plan-de-Manejo-Reserva-Natural-Volcan-Mombacho.pdf', null, null, null, 'https://www.marena.gob.ni/wp-content/uploads/2023/11/R.M.-Plan-de-Manejo-Volcan-Mombacho.pdf', 'MARENA — Planes de Manejo de Áreas Protegidas', 'https://www.marena.gob.ni/planes-de-manejo/plan-de-manejo-reserva-natural-volcan-mombacho/', '2026-10-05'::timestamptz, 'partial', 'Hay Gaceta enlazada, pero el número de resolución no se pudo confirmar en su texto: approval_reference NULL.', 'import:marena', 'import:marena')
on conflict (area_key, source_url) do update set place_id = excluded.place_id, title = excluded.title, document_url = excluded.document_url,
  approval_reference = excluded.approval_reference, gazette_reference = excluded.gazette_reference, gazette_url = excluded.gazette_url,
  verified_at = excluded.verified_at, status = excluded.status, notes = excluded.notes
where public.management_plans.updated_by = 'import:marena';
