// ============================================================================
// BAQUEANO IA — PLANIFICADOR TERRITORIAL WEB
// 🎯 POR QUÉ: mantener el asistente útil aun cuando el gateway no esté disponible.
// ⚙️ CÓMO: intenta el endpoint oficial y usa un motor local determinista como respaldo.
// 📦 QUÉ: conversación, extracción básica y ruta diaria con presupuesto orientativo.
// ============================================================================
(function(){'use strict';
  const form=document.getElementById('aiForm'),input=document.getElementById('request'),messages=document.getElementById('messages'),result=document.getElementById('result');
  if(!form||!input||!messages||!result)return;
  const knowledge={León:['Catedral y centro histórico','Volcán Cerro Negro','Las Peñitas y cocina costera'],Granada:['Centro histórico colonial','Isletas del Gran Lago','Reserva Natural Volcán Mombacho'],Ometepe:['Moyogalpa y cultura isleña','Sendero del volcán Maderas','Ojo de Agua y fincas comunitarias'],Rivas:['San Juan del Sur','Playa Maderas','Miradores del istmo'],Matagalpa:['Ruta del café','Selva Negra','Comunidades y nebliselva'],Madriz:['Cañón de Somoto','Mercado y gastronomía de Somoto','Senderos rurales del norte']};
  const escapeHtml=(value)=>String(value).replace(/[&<>'"]/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  function addMessage(text,type){const article=document.createElement('article');article.className=`ai-message ${type}`;article.innerHTML=`<div class="ai-avatar"><i class="fa-solid ${type==='user'?'fa-user':'fa-compass'}"></i></div><div><small>${type==='user'?'EXPLORADOR':'BAQUEANO IA'}</small><p>${escapeHtml(text)}</p></div>`;messages.appendChild(article);messages.scrollTop=messages.scrollHeight;}
  function localPlan(){const territory=document.getElementById('territory').value,days=Math.max(1,Math.min(14,Number(document.getElementById('days').value)||3)),travelers=Math.max(1,Number(document.getElementById('travelers').value)||1),budget=Number(document.getElementById('budget').value)||600,style=document.querySelector('input[name="style"]:checked').value,places=knowledge[territory]||knowledge.León,perDay=Math.round(Math.min(budget,days*travelers*72)/days);return{territory,days,budget,style,total:perDay*days,items:Array.from({length:days},(_,i)=>({day:i+1,title:places[i%places.length],copy:`Jornada de ${style} con tiempo para traslados, comida local y exploración responsable. Presupuesto orientativo: $${perDay} USD.`}))};}
  function renderPlan(plan){result.innerHTML=`<div class="ai-result-head"><div><span class="ai-result-kicker">Ruta sugerida · ${escapeHtml(plan.territory)}</span><h2>Tu aventura toma forma</h2></div><div class="ai-total">Estimado total <strong>$${plan.total} USD</strong></div></div><div class="ai-days">${plan.items.map(item=>`<article class="ai-day"><span>DÍA ${item.day}</span><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.copy)}</p></article>`).join('')}</div><p class="ai-result-note"><i class="fa-solid fa-circle-check"></i> Ruta de orientación creada con el catálogo territorial local. Confirma horarios, clima, acceso y precios antes de viajar.</p>`;result.hidden=false;result.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});}
  async function requestPlan(text){const button=form.querySelector('button');button.disabled=true;button.innerHTML='<i class="fa-solid fa-spinner fa-spin"></i><span>Preparando</span>';try{const payload={days:Number(document.getElementById('days').value),groupSize:Number(document.getElementById('travelers').value),budgetUsd:Number(document.getElementById('budget').value),currency:'USD',department:document.getElementById('territory').value,interests:[document.querySelector('input[name="style"]:checked').value],travelStyle:document.querySelector('input[name="style"]:checked').value,prompt:text};const response=await fetch('/api/baqueano-ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!response.ok)throw new Error('gateway');const data=await response.json();if(!data.success||!data.itinerary)throw new Error('invalid');addMessage('Preparé una ruta usando el servicio territorial conectado. Revisa cada jornada y ajusta tu presupuesto cuando lo necesites.','assistant');const days=data.itinerary.days||[];renderPlan({territory:payload.department,total:data.itinerary.totalEstimatedCostUsd||payload.budgetUsd,items:days.map((day,index)=>({day:day.dayNumber||index+1,title:day.title||`Explora ${payload.department}`,copy:(day.stops||[]).map(stop=>stop.name).join(' · ')||'Experiencia territorial sugerida.'}))});}catch(_){const plan=localPlan();addMessage(`Preparé una ruta orientativa de ${plan.days} días por ${plan.territory}. Puedes ajustar territorio, ritmo y presupuesto para crear otra versión.`,'assistant');renderPlan(plan);}finally{button.disabled=false;button.innerHTML='<span>Crear mi ruta</span><i class="fa-solid fa-arrow-up"></i>';}}
  form.addEventListener('submit',(event)=>{event.preventDefault();const text=input.value.trim();if(!text)return;addMessage(text,'user');input.value='';requestPlan(text);});
  document.querySelectorAll('[data-prompt]').forEach(button=>button.addEventListener('click',()=>{input.value=button.dataset.prompt;input.focus();}));
})();
