-- ============================================================================
-- 🧭 BAQUEANO ECOSYSTEM — SEMILLERO CANÓNICO CULTURAL & TERRITORIAL (013)
-- ============================================================================
-- 🎯 1. POR QUÉ:
-- - Ingestar el 100% de la riqueza territorial, gastronómica, sonora, artesanal,
--   de comunidades y emergencias de Nicaragua ya desarrollada en el repositorio.
-- - Cumplir con la regla 'NO SIMULAR, NO COPIAR': Datos reales, 153 municipios,
--   autores acreditados (Justo Santos, Camilo Zapata, etc.) y coordenadas verificadas.
--
-- ⚙️ 2. CÓMO:
-- - Inserciones idempotentes con ON CONFLICT (id) DO NOTHING / DO UPDATE.
-- ============================================================================

-- 1. LOS 153 MUNICIPIOS DE NICARAGUA
INSERT INTO public.municipalities (id, department_id, name) VALUES
('mun_boaco_boaco', 'boaco', 'Boaco'),
('mun_boaco_camoapa', 'boaco', 'Camoapa'),
('mun_boaco_san-jose-de-los-remates', 'boaco', 'San José de los Remates'),
('mun_boaco_san-lorenzo', 'boaco', 'San Lorenzo'),
('mun_boaco_santa-lucia', 'boaco', 'Santa Lucía'),
('mun_boaco_teustepe', 'boaco', 'Teustepe'),
('mun_carazo_jinotepe', 'carazo', 'Jinotepe'),
('mun_carazo_diriamba', 'carazo', 'Diriamba'),
('mun_carazo_dolores', 'carazo', 'Dolores'),
('mun_carazo_el-rosario', 'carazo', 'El Rosario'),
('mun_carazo_la-conquista', 'carazo', 'La Conquista'),
('mun_carazo_la-paz-de-carazo', 'carazo', 'La Paz de Carazo'),
('mun_carazo_san-marcos', 'carazo', 'San Marcos'),
('mun_carazo_santa-teresa', 'carazo', 'Santa Teresa'),
('mun_chinandega_chinandega', 'chinandega', 'Chinandega'),
('mun_chinandega_chichigalpa', 'chinandega', 'Chichigalpa'),
('mun_chinandega_corinto', 'chinandega', 'Corinto'),
('mun_chinandega_cinco-pinos', 'chinandega', 'Cinco Pinos'),
('mun_chinandega_el-realejo', 'chinandega', 'El Realejo'),
('mun_chinandega_el-viejo', 'chinandega', 'El Viejo'),
('mun_chinandega_posoltega', 'chinandega', 'Posoltega'),
('mun_chinandega_puerto-morazan', 'chinandega', 'Puerto Morazán'),
('mun_chinandega_san-francisco-del-norte', 'chinandega', 'San Francisco del Norte'),
('mun_chinandega_san-pedro-del-norte', 'chinandega', 'San Pedro del Norte'),
('mun_chinandega_santo-tomas-del-norte', 'chinandega', 'Santo Tomás del Norte'),
('mun_chinandega_somotillo', 'chinandega', 'Somotillo'),
('mun_chinandega_villanueva', 'chinandega', 'Villanueva'),
('mun_chontales_juigalpa', 'chontales', 'Juigalpa'),
('mun_chontales_acoyapa', 'chontales', 'Acoyapa'),
('mun_chontales_comalapa', 'chontales', 'Comalapa'),
('mun_chontales_cuapa', 'chontales', 'Cuapa'),
('mun_chontales_el-coral', 'chontales', 'El Coral'),
('mun_chontales_la-libertad', 'chontales', 'La Libertad'),
('mun_chontales_san-pedro-de-lovago', 'chontales', 'San Pedro de Lóvago'),
('mun_chontales_santo-domingo', 'chontales', 'Santo Domingo'),
('mun_chontales_santo-tomas', 'chontales', 'Santo Tomás'),
('mun_chontales_villa-sandino', 'chontales', 'Villa Sandino'),
('mun_esteli_esteli', 'esteli', 'Estelí'),
('mun_esteli_condega', 'esteli', 'Condega'),
('mun_esteli_la-trinidad', 'esteli', 'La Trinidad'),
('mun_esteli_pueblo-nuevo', 'esteli', 'Pueblo Nuevo'),
('mun_esteli_san-juan-de-limay', 'esteli', 'San Juan de Limay'),
('mun_esteli_san-nicolas', 'esteli', 'San Nicolás'),
('mun_granada_granada', 'granada', 'Granada'),
('mun_granada_diria', 'granada', 'Diriá'),
('mun_granada_diriomo', 'granada', 'Diriomo'),
('mun_granada_nandaime', 'granada', 'Nandaime'),
('mun_jinotega_jinotega', 'jinotega', 'Jinotega'),
('mun_jinotega_el-cua', 'jinotega', 'El Cuá'),
('mun_jinotega_la-concordia', 'jinotega', 'La Concordia'),
('mun_jinotega_san-jose-de-bocay', 'jinotega', 'San José de Bocay'),
('mun_jinotega_san-rafael-del-norte', 'jinotega', 'San Rafael del Norte'),
('mun_jinotega_san-sebastian-de-yali', 'jinotega', 'San Sebastián de Yalí'),
('mun_jinotega_santa-maria-de-pantasma', 'jinotega', 'Santa María de Pantasma'),
('mun_jinotega_wiwili-de-jinotega', 'jinotega', 'Wiwilí de Jinotega'),
('mun_leon_leon', 'leon', 'León'),
('mun_leon_achuapa', 'leon', 'Achuapa'),
('mun_leon_el-jicaral', 'leon', 'El Jicaral'),
('mun_leon_el-sauce', 'leon', 'El Sauce'),
('mun_leon_la-paz-centro', 'leon', 'La Paz Centro'),
('mun_leon_larreynaga-malpaisillo', 'leon', 'Larreynaga Malpaisillo'),
('mun_leon_nagarote', 'leon', 'Nagarote'),
('mun_leon_quezalguaque', 'leon', 'Quezalguaque'),
('mun_leon_santa-rosa-del-penon', 'leon', 'Santa Rosa del Peñón'),
('mun_leon_telica', 'leon', 'Telica'),
('mun_madriz_somoto', 'madriz', 'Somoto'),
('mun_madriz_las-sabanas', 'madriz', 'Las Sabanas'),
('mun_madriz_palacaguina', 'madriz', 'Palacagüina'),
('mun_madriz_san-jose-de-cusmapa', 'madriz', 'San José de Cusmapa'),
('mun_madriz_san-juan-de-rio-coco', 'madriz', 'San Juan de Río Coco'),
('mun_madriz_san-lucas', 'madriz', 'San Lucas'),
('mun_madriz_telpaneca', 'madriz', 'Telpaneca'),
('mun_madriz_totogalpa', 'madriz', 'Totogalpa'),
('mun_madriz_yalaguina', 'madriz', 'Yalagüina'),
('mun_managua_managua', 'managua', 'Managua'),
('mun_managua_ciudad-sandino', 'managua', 'Ciudad Sandino'),
('mun_managua_el-crucero', 'managua', 'El Crucero'),
('mun_managua_mateare', 'managua', 'Mateare'),
('mun_managua_san-francisco-libre', 'managua', 'San Francisco Libre'),
('mun_managua_san-rafael-del-sur', 'managua', 'San Rafael del Sur'),
('mun_managua_ticuantepe', 'managua', 'Ticuantepe'),
('mun_managua_tipitapa', 'managua', 'Tipitapa'),
('mun_managua_villa-el-carmen', 'managua', 'Villa El Carmen'),
('mun_masaya_masaya', 'masaya', 'Masaya'),
('mun_masaya_catarina', 'masaya', 'Catarina'),
('mun_masaya_la-concepcion', 'masaya', 'La Concepción'),
('mun_masaya_masatepe', 'masaya', 'Masatepe'),
('mun_masaya_nandasmo', 'masaya', 'Nandasmo'),
('mun_masaya_nindiri', 'masaya', 'Nindirí'),
('mun_masaya_niquinohomo', 'masaya', 'Niquinohomo'),
('mun_masaya_san-juan-de-oriente', 'masaya', 'San Juan de Oriente'),
('mun_masaya_tisma', 'masaya', 'Tisma'),
('mun_matagalpa_matagalpa', 'matagalpa', 'Matagalpa'),
('mun_matagalpa_ciudad-dario', 'matagalpa', 'Ciudad Darío'),
('mun_matagalpa_esquipulas', 'matagalpa', 'Esquipulas'),
('mun_matagalpa_matiguas', 'matagalpa', 'Matiguás'),
('mun_matagalpa_muy-muy', 'matagalpa', 'Muy Muy'),
('mun_matagalpa_rancho-grande', 'matagalpa', 'Rancho Grande'),
('mun_matagalpa_rio-blanco', 'matagalpa', 'Río Blanco'),
('mun_matagalpa_san-dionisio', 'matagalpa', 'San Dionisio'),
('mun_matagalpa_san-isidro', 'matagalpa', 'San Isidro'),
('mun_matagalpa_san-ramon', 'matagalpa', 'San Ramón'),
('mun_matagalpa_sebaco', 'matagalpa', 'Sébaco'),
('mun_matagalpa_terrabona', 'matagalpa', 'Terrabona'),
('mun_matagalpa_tuma-la-dalia', 'matagalpa', 'Tuma-La Dalia'),
('mun_nueva_segovia_ocotal', 'nueva_segovia', 'Ocotal'),
('mun_nueva_segovia_ciudad-antigua', 'nueva_segovia', 'Ciudad Antigua'),
('mun_nueva_segovia_dipilto', 'nueva_segovia', 'Dipilto'),
('mun_nueva_segovia_el-jicaro', 'nueva_segovia', 'El Jícaro'),
('mun_nueva_segovia_jalapa', 'nueva_segovia', 'Jalapa'),
('mun_nueva_segovia_macuelizo', 'nueva_segovia', 'Macuelizo'),
('mun_nueva_segovia_mozonte', 'nueva_segovia', 'Mozonte'),
('mun_nueva_segovia_murra', 'nueva_segovia', 'Murra'),
('mun_nueva_segovia_quilali', 'nueva_segovia', 'Quilalí'),
('mun_nueva_segovia_san-fernando', 'nueva_segovia', 'San Fernando'),
('mun_nueva_segovia_santa-maria', 'nueva_segovia', 'Santa María'),
('mun_nueva_segovia_wiwili-de-nueva-segovia', 'nueva_segovia', 'Wiwilí de Nueva Segovia'),
('mun_rivas_rivas', 'rivas', 'Rivas'),
('mun_rivas_altagracia', 'rivas', 'Altagracia'),
('mun_rivas_belen', 'rivas', 'Belén'),
('mun_rivas_buenos-aires', 'rivas', 'Buenos Aires'),
('mun_rivas_cardenas', 'rivas', 'Cárdenas'),
('mun_rivas_moyogalpa', 'rivas', 'Moyogalpa'),
('mun_rivas_potosi', 'rivas', 'Potosí'),
('mun_rivas_san-jorge', 'rivas', 'San Jorge'),
('mun_rivas_san-juan-del-sur', 'rivas', 'San Juan del Sur'),
('mun_rivas_tola', 'rivas', 'Tola'),
('mun_rio_san_juan_san-carlos', 'rio_san_juan', 'San Carlos'),
('mun_rio_san_juan_el-almendro', 'rio_san_juan', 'El Almendro'),
('mun_rio_san_juan_el-castillo', 'rio_san_juan', 'El Castillo'),
('mun_rio_san_juan_morrito', 'rio_san_juan', 'Morrito'),
('mun_rio_san_juan_san-juan-de-nicaragua', 'rio_san_juan', 'San Juan de Nicaragua'),
('mun_rio_san_juan_san-miguelito', 'rio_san_juan', 'San Miguelito'),
('mun_raccn_puerto-cabezas-(bilwi)', 'raccn', 'Puerto Cabezas (Bilwi)'),
('mun_raccn_bonanza', 'raccn', 'Bonanza'),
('mun_raccn_mulukuku', 'raccn', 'Mulukukú'),
('mun_raccn_prinzapolka', 'raccn', 'Prinzapolka'),
('mun_raccn_rosita', 'raccn', 'Rosita'),
('mun_raccn_siuna', 'raccn', 'Siuna'),
('mun_raccn_waslala', 'raccn', 'Waslala'),
('mun_raccn_waspam', 'raccn', 'Waspam'),
('mun_raccs_bluefields', 'raccs', 'Bluefields'),
('mun_raccs_corn-island', 'raccs', 'Corn Island'),
('mun_raccs_desembocadura-de-rio-grande', 'raccs', 'Desembocadura de Río Grande'),
('mun_raccs_el-ayote', 'raccs', 'El Ayote'),
('mun_raccs_el-rama', 'raccs', 'El Rama'),
('mun_raccs_el-tortuguero', 'raccs', 'El Tortuguero'),
('mun_raccs_kukra-hill', 'raccs', 'Kukra Hill'),
('mun_raccs_la-cruz-de-rio-grande', 'raccs', 'La Cruz de Río Grande'),
('mun_raccs_laguna-de-perlas', 'raccs', 'Laguna de Perlas'),
('mun_raccs_muelle-de-los-bueyes', 'raccs', 'Muelle de los Bueyes'),
('mun_raccs_nueva-guinea', 'raccs', 'Nueva Guinea'),
('mun_raccs_paiwas', 'raccs', 'Paiwas')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;

-- 2. GASTRONOMÍA ANCESTRAL Y PLATOS TRADICIONALES
INSERT INTO public.gastronomy (id, department_id, dish_name, category, origin_history, ancestral_technique, status, hidden_gem) VALUES
('gastro_madriz_1', 'madriz', 'Rosquillas de Somoto y Yalagüina', 'plato_fuerte', 'Elaboradas artesanalmente con maíz blanco seleccionado, queso seco criollo, cuajada fresca y mantequilla de hacienda, doradas a leña en hornos de barro.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_madriz_2', 'madriz', 'Viejitas y Hojaldras', 'plato_fuerte', 'Bocados crujientes de masa de maíz con dulce de panela (rapadura) derretida en su centro.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_madriz_3', 'madriz', 'Montucas Madricenses', 'plato_fuerte', 'Tamal tierno de elote condimentado con pollo de patio, hierbabuena, leche y un toque sutil de chile congo.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_madriz_4', 'madriz', 'Café de Estricta Altura', 'plato_fuerte', 'Variedades Caturra, Borbón y Catuaí cultivadas bajo sombra de montaña en San Juan del Río Coco entre 1,000 y 1,400 msnm.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_madriz_5', 'madriz', 'Gorditas de Maíz y Güirilas', 'plato_fuerte', 'Tortas dulces asadas en hojas de plátano acompañadas con cuajada fresca de hacienda.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_madriz_6', 'madriz', 'Rosquillas en Miel de Caña', 'plato_fuerte', 'Postre tradicional de Semana Santa y fiestas patronales bañado en almíbar de dulce de atado.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_leon_1', 'leon', 'Ruta del Quesillo', 'plato_fuerte', 'Nagarote y La Paz Centro comparten esta tradición de tortilla, queso, crema y cebolla encurtida.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_leon_2', 'leon', 'Cocina Tradicional', 'plato_fuerte', 'Vigorón, nacatamal, indio viejo, chancho con yuca, carne asada y tamales.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_leon_3', 'leon', 'Sopas y Maíz', 'plato_fuerte', 'Sopa de res, sopa de queso, güirilas y tortillas preparadas con saberes familiares.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_leon_4', 'leon', 'Lácteos y Dulces', 'plato_fuerte', 'Quesos, cajetas, rosquillas y otros dulces tradicionales de occidente.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_leon_5', 'leon', 'Bebidas de Identidad', 'plato_fuerte', 'Cacao, pinolillo, tiste, chicha y distintas bebidas tradicionales de maíz.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_leon_6', 'leon', 'Sabores del Centro Histórico', 'plato_fuerte', 'Mercados, dulcerías, cafés y emprendimientos familiares con cocina local.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_rivas_1', 'rivas', 'Pescado del Cocibolca', 'plato_fuerte', 'Pescado fresco preparado por familias y cocinas vinculadas con la vida lacustre.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_rivas_2', 'rivas', 'Mariscos del Pacífico', 'plato_fuerte', 'Productos del mar servidos en San Juan del Sur, Tola y comunidades pesqueras.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_rivas_3', 'rivas', 'Productos de Plátano', 'plato_fuerte', 'Tostones, tajadas y otras preparaciones fundamentales de la cocina rivense.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_rivas_4', 'rivas', 'Sopas y Nacatamales', 'plato_fuerte', 'Recetas tradicionales acompañadas con tortillas y productos locales.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_rivas_5', 'rivas', 'Sabores de Ometepe', 'plato_fuerte', 'Plátano, frutas, miel, café, pescado y cocina campesina de las fincas de la isla.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_rivas_6', 'rivas', 'Cacao y Bebidas Tradicionales', 'plato_fuerte', 'Bebidas y productos tropicales elaborados en comunidades y emprendimientos.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_jinotega_1', 'jinotega', 'Café SHG de Estricta Altura', 'plato_fuerte', 'Notas de chocolate, jazmín y frutas cítricas cosechado a más de 1,400 msnm.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_jinotega_2', 'jinotega', 'Güirilas con Cuajada Fresca', 'plato_fuerte', 'Tortilla dulce de maíz tierno asada en hoja de plátano.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_jinotega_3', 'jinotega', 'Agua de Loja Jinotegana', 'plato_fuerte', 'Bebida a base de maíz hervido con jengibre y dulce de rapadura.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_jinotega_4', 'jinotega', 'Sopa de Gallina India con Albóndigas', 'plato_fuerte', 'Cocida con leña en fogones campesinos.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_jinotega_5', 'jinotega', 'Panadería de Yalí', 'plato_fuerte', 'Rosquillas, perrerreque, quesadillas, semitas, dulces y bebidas tradicionales de maíz.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_jinotega_6', 'jinotega', 'Productos de Finca', 'plato_fuerte', 'Cacao, miel, cuajada, queso, crema, frijoles, tamales y sopa de cuajada.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_masaya_1', 'masaya', 'Sopa de Mondongo', 'plato_fuerte', 'Uno de los sabores más característicos del departamento y de su cocina festiva.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_masaya_2', 'masaya', 'Tamuga de Monimbó', 'plato_fuerte', 'Preparación tradicional estrechamente vinculada con la identidad comunitaria de Monimbó.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_masaya_3', 'masaya', 'Cocina de Maíz', 'plato_fuerte', 'Nacatamal, indio viejo, tortillas, rosquillas, güirilas y tamales.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_masaya_4', 'masaya', 'Vigorón y Yuca', 'plato_fuerte', 'Preparaciones populares presentes en mercados, barrios y celebraciones.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_masaya_5', 'masaya', 'Dulces y Cajetas', 'plato_fuerte', 'Dulces tradicionales elaborados por familias y emprendimientos locales.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_masaya_6', 'masaya', 'Bebidas Tradicionales', 'plato_fuerte', 'Cacao, tiste, pinolillo y bebidas de maíz.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_granada_1', 'granada', 'Ruta del Vigorón', 'plato_fuerte', 'Yuca cocida, chicharrón y ensalada de repollo servidos en el Parque Central, mercados y cocinas locales.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_granada_2', 'granada', 'Sabores del Cocibolca', 'plato_fuerte', 'Pescado, mariscos y preparaciones vinculadas con la vida lacustre.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_granada_3', 'granada', 'Cocina Nicaragüense', 'plato_fuerte', 'Chancho con yuca, nacatamal, indio viejo y quesillos.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_granada_4', 'granada', 'Ruta de las Cajetas', 'plato_fuerte', 'Dulces tradicionales que conectan Granada con los talleres familiares de Diriomo.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_granada_5', 'granada', 'Cacao y Bebidas', 'plato_fuerte', 'Cacao, refrescos naturales, chicha y pinolillo.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_granada_6', 'granada', 'Sabores Municipales', 'plato_fuerte', 'Atol de ánimas de Diriá y preparaciones tradicionales de Nandaime.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_matagalpa_1', 'matagalpa', 'Cacao con Leche y Canela', 'plato_fuerte', 'Bebida densa y aromática elaborada con cacao puro cultivado en montaña.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_matagalpa_2', 'matagalpa', 'Montucas Matagalpinas', 'plato_fuerte', 'Masa de maíz tierno rellena con carne marinada en naranja agria.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_matagalpa_3', 'matagalpa', 'Queso Ahumado de Muy Muy', 'plato_fuerte', 'Queso artesanal curado con maderas de roble.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_matagalpa_4', 'matagalpa', 'Dulces de Leche y Cajeta de Café', 'plato_fuerte', 'Elaborados por artesanas rurales del valle.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_matagalpa_5', 'matagalpa', 'Maíz y Lácteos', 'plato_fuerte', 'Güirilas, cuajada, crema, tamales, indio viejo, sopas y productos de finca.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_matagalpa_6', 'matagalpa', 'Café, Chocolate y Miel', 'plato_fuerte', 'Productos de montaña ofrecidos en fincas, comunidades y cafeterías locales.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_esteli_1', 'esteli', 'Perrerengue y Tamales de El Tisey', 'plato_fuerte', 'Maíz cosechado en alturas de 1,200 msnm con queso de monte.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_esteli_2', 'esteli', 'Cuajada Fresca Esteliana', 'plato_fuerte', 'Famosa por su textura mantecosa y sabor inconfundible.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_esteli_3', 'esteli', 'Carne Asada en Brasas de Leña', 'plato_fuerte', 'Con tortilla caliente, chimichurri y queso frito.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_esteli_4', 'esteli', 'Café de Miraflor', 'plato_fuerte', 'Café orgánico cultivado por cooperativas campesinas.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_esteli_5', 'esteli', 'Desayuno Segoviano', 'plato_fuerte', 'Café de montaña, tortilla, cuajada, crema, huevos y frijoles.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_esteli_6', 'esteli', 'Queso de Cabra y Miel', 'plato_fuerte', 'Productos comunitarios vinculados con La Garnacha y fincas rurales.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_chinandega_1', 'chinandega', 'Tonkolote Chinandegano', 'plato_fuerte', 'Tamal de maíz relleno con carne condimentada envuelto en hojas.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_chinandega_2', 'chinandega', 'Pescado Frito y Ceviche de Concha Negra', 'plato_fuerte', 'Recién extraídos de los manglares de Corinto y Aserradores.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_chinandega_3', 'chinandega', 'Rosquillas y Viejitas de El Viejo', 'plato_fuerte', 'Reconocidas como de las más finas del país.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_chinandega_4', 'chinandega', 'Fresco de Chicha Morada', 'plato_fuerte', 'Elaborada con maíz morado autóctono.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_managua_1', 'managua', 'Ruta de la Fritanga', 'plato_fuerte', 'Carne asada, tajadas, enchiladas, tacos, repochetas y comida popular nocturna.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_managua_2', 'managua', 'Sabores de Nicaragua', 'plato_fuerte', 'Nacatamal, vigorón, quesillo, indio viejo, baho y recetas de todos los departamentos.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_managua_3', 'managua', 'Sopas Tradicionales', 'plato_fuerte', 'Sopa de res y sopa de mondongo preparadas en mercados, barrios y restaurantes.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_managua_4', 'managua', 'Mercados y Comida Popular', 'plato_fuerte', 'Cocinas tradicionales, productos locales y encuentros cotidianos con la ciudad.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_managua_5', 'managua', 'Cafés y Cocina Contemporánea', 'plato_fuerte', 'Café nacional y propuestas modernas inspiradas en ingredientes nicaragüenses.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_managua_6', 'managua', 'Bebidas Tradicionales', 'plato_fuerte', 'Cacao, pinolillo, tiste, chicha, cebada y semilla de jícaro.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_carazo_1', 'carazo', 'Café Caraceño', 'plato_fuerte', 'Ruta entre San Marcos, Diriamba, Dolores, Jinotepe y fincas rurales: cultivo, tostado y degustación.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_carazo_2', 'carazo', 'Ajiaco y Picadillo', 'plato_fuerte', 'Preparaciones tradicionales vinculadas con la cocina familiar y festiva.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_carazo_3', 'carazo', 'Nacatamal Caraceño', 'plato_fuerte', 'Receta territorial elaborada con maíz, carne, verduras y saberes familiares.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_carazo_4', 'carazo', 'Pan, Melcochas y Dulces', 'plato_fuerte', 'Pan artesanal, melcochas y dulces de producción local.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_carazo_5', 'carazo', 'Chilate y Helados Tradicionales', 'plato_fuerte', 'Bebidas y postres asociados especialmente con Jinotepe y sus comunidades.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_carazo_6', 'carazo', 'Sabores de la Costa', 'plato_fuerte', 'Pescado y mariscos preparados en La Boquita, Casares, Huehuete y otros pueblos costeros.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_chontales_1', 'chontales', 'Cuajadas y Quesos Chontaleños', 'plato_fuerte', 'De fama internacional: queso quesillo, queso con chile y crema pura de hacienda.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_chontales_2', 'chontales', 'Sopa de Hueso de Res con Albóndigas', 'plato_fuerte', 'Servida en los días de mercado con tortillas gigantes.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_chontales_3', 'chontales', 'Tamal Pisque con Queso Frito', 'plato_fuerte', 'Maíz tratado con ceniza de roble y sal marina.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_chontales_4', 'chontales', 'Chicha de Maíz Pujagua', 'plato_fuerte', 'Bebida de maíz rojo fermentado.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_chontales_5', 'chontales', 'Quesillo de Santo Tomás', 'plato_fuerte', 'Producto emblemático elaborado con leche, queso, crema y tradición ganadera.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_chontales_6', 'chontales', 'Sabores del Lago y la Finca', 'plato_fuerte', 'Pescado, carne, güirilas, nacatamales, sopas y café de zonas altas.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_boaco_1', 'boaco', 'Queso Boaqueño de Pella', 'plato_fuerte', 'Queso suave y salado elaborado con leche de vacas alimentadas en pastos de altura.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_boaco_2', 'boaco', 'Carne en Vaho Boaqueña', 'plato_fuerte', 'Cocida con leña durante 10 horas con yuca dulce y plátano maduro.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_boaco_3', 'boaco', 'Atol de Maíz de Cacao', 'plato_fuerte', 'Bebida caliente energizante de origen indígena.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_boaco_4', 'boaco', 'Gorditas Dulces de Maíz', 'plato_fuerte', 'Asadas al comal con cuajada fresca.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_boaco_5', 'boaco', 'Lácteos de Finca', 'plato_fuerte', 'Leche, queso, cuajada y crema elaborados en comunidades ganaderas.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_boaco_6', 'boaco', 'Sabores Campesinos', 'plato_fuerte', 'Güirilas, nacatamales, carnes, sopas, miel, tortillas y café de montaña.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_nueva-segovia_1', 'nueva-segovia', 'Tamal Relleno Segoviano', 'plato_fuerte', 'Maíz con masa sazonada con manteca y relleno de pollo campesino.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_nueva-segovia_2', 'nueva-segovia', 'Café de Dipilto (Taza de Excelencia)', 'plato_fuerte', 'Reconocido con los mayores puntajes internacionales de café especial.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_nueva-segovia_3', 'nueva-segovia', 'Rosquillas de Jalapa', 'plato_fuerte', 'Horneadas crujientes con queso de montaña.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_nueva-segovia_4', 'nueva-segovia', 'Empanadas de Maíz con Cuajada', 'plato_fuerte', 'Fritas al momento en manteca pura.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_nueva-segovia_5', 'nueva-segovia', 'Sabores de Montaña', 'plato_fuerte', 'Güirilas, cuajada, crema, frijoles, carnes, miel, rosquillas y panes.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_nueva-segovia_6', 'nueva-segovia', 'Ruta del Maíz y el Jocote', 'plato_fuerte', 'Productos, dulces y bebidas vinculados con Jalapa y Macuelizo.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_rio-san-juan_1', 'rio-san-juan', 'Camarón de Río al Ajillo', 'plato_fuerte', 'Camarones gigantes de agua dulce cocinados con mantequilla y ajo.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_rio-san-juan_2', 'rio-san-juan', 'Sopa de Pescado Gaspar', 'plato_fuerte', 'Fósil viviente cocinado con verduras de la selva y leche de coco.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_rio-san-juan_3', 'rio-san-juan', 'Tostones Rellenos de Salpicón de Sábalo', 'plato_fuerte', 'Bocados crujientes con pescado fresco.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_rio-san-juan_4', 'rio-san-juan', 'Tortilla de Maíz con Frijoles Nuevos', 'plato_fuerte', 'Acompañada de cuajada fresca ribereña.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_rio-san-juan_5', 'rio-san-juan', 'Ruta del Cacao', 'plato_fuerte', 'Mazorca, fermentación, secado, tostado, chocolate y degustación en fincas y comunidades.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_rio-san-juan_6', 'rio-san-juan', 'Sabores del Agua y la Selva', 'plato_fuerte', 'Pescado, sopas, plátano, maíz, productos tropicales, miel y lácteos rurales.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_raccn_1', 'raccn', 'Luk Luk Costeño', 'plato_fuerte', 'Sopa ancestral miskita de carne de res hervida con yuca, plátano y culantro de monte.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_raccn_2', 'raccn', 'Wabul de Plátano o Yuca', 'plato_fuerte', 'Bebida espesa nutritiva elaborada con plátano maduro batido con leche de coco fresca.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_raccn_3', 'raccn', 'Pescado Ahumado con Leña de Mangle', 'plato_fuerte', 'Técnica de conservación tradicional indígena.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_raccn_4', 'raccn', 'Pan de Coco Tradicional', 'plato_fuerte', 'Horneado a la leña con coco recién rallado.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_raccn_5', 'raccn', 'Rondón Caribeño', 'plato_fuerte', 'Coco, tubérculos y pescado o carne preparados según la tradición comunitaria.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_raccn_6', 'raccn', 'Bunya y Productos del Territorio', 'plato_fuerte', 'Yuca fermentada, pescado, mariscos, plátano, maíz y coco.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_raccs_1', 'raccs', 'Rondón Costeño (Run Down)', 'plato_fuerte', 'Pescado fresco, langosta, cangrejo, yuca, plátano y fruta de pan cocinados a fuego lento en leche de coco con chile cabro.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_raccs_2', 'raccs', 'Gingerser (Cerveza de Jengibre)', 'plato_fuerte', 'Bebida fermentada afrocaribeña especiada.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_raccs_3', 'raccs', 'Patties Costeños', 'plato_fuerte', 'Empanadas crujientes rellenas de carne picada picante.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_raccs_4', 'raccs', 'Queque de Quequisque y Pan de Coco', 'plato_fuerte', 'Repostería fina tradicional.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_raccs_5', 'raccs', 'Rice and Beans y Patí', 'plato_fuerte', 'Arroz con frijoles en coco y empanada tradicional de la cocina caribeña.', 'Elaboración tradicional artesanal', 'published', false),
('gastro_raccs_6', 'raccs', 'Sabores del Mar', 'plato_fuerte', 'Pescado, camarón, cangrejo y langosta únicamente durante temporada autorizada.', 'Elaboración tradicional artesanal', 'published', false)
ON CONFLICT (id) DO UPDATE SET dish_name = EXCLUDED.dish_name, origin_history = EXCLUDED.origin_history;

-- 3. ARCHIVO MUSICAL Y MAESTROS DEL SON NICA Y CARIBE
INSERT INTO public.music (id, department_id, title, artist_composer, genre, era, historical_significance, status) VALUES
('music_camilo-zapata', 'managua', 'Camilo Zapata', 'Camilo Zapata', 'son-nica', 'siglo_xx', 'Patrimonio inmaterial de la música nicaragüense.', 'published'),
('music_justo-santos', 'rivas', 'Justo Santos', 'Justo Santos', 'son-nica', 'siglo_xx', 'Patrimonio inmaterial de la música nicaragüense.', 'published'),
('music_tino-lopez-guerra', 'chinandega', 'Tino López Guerra', 'Tino López Guerra', 'son-nica', 'siglo_xx', 'Patrimonio inmaterial de la música nicaragüense.', 'published'),
('music_erwin-kruger', 'masaya', 'Erwin Krüger', 'Erwin Krüger', 'son-nica', 'siglo_xx', 'Patrimonio inmaterial de la música nicaragüense.', 'published'),
('music_otto-de-la-rocha', 'jinotega', 'Otto de la Rocha', 'Otto de la Rocha', 'son-nica', 'siglo_xx', 'Patrimonio inmaterial de la música nicaragüense.', 'published'),
('music_carlos-mejia-godoy', 'madriz', 'Carlos Mejía Godoy', 'Carlos Mejía Godoy', 'cantautores', 'siglo_xx', 'Patrimonio inmaterial de la música nicaragüense.', 'published'),
('music_luis-enrique-mejia-godoy', 'madriz', 'Luis Enrique Mejía Godoy', 'Luis Enrique Mejía Godoy', 'cantautores', 'siglo_xx', 'Patrimonio inmaterial de la música nicaragüense.', 'published'),
('music_salvador-cardenal', 'matagalpa', 'Salvador Cardenal Barquero', 'Salvador Cardenal Barquero', 'cantautores', 'siglo_xx', 'Patrimonio inmaterial de la música nicaragüense.', 'published'),
('music_katia-cardenal', 'managua', 'Katia Cardenal', 'Katia Cardenal', 'cantautores', 'siglo_xx', 'Patrimonio inmaterial de la música nicaragüense.', 'published'),
('music_norma-helena-gadea', 'nueva-segovia', 'Norma Helena Gadea', 'Norma Helena Gadea', 'cantautores', 'siglo_xx', 'Patrimonio inmaterial de la música nicaragüense.', 'published'),
('music_jose-de-la-cruz-mena', 'leon', 'José de la Cruz Mena', 'José de la Cruz Mena', 'patrimonio', 'siglo_xx', 'Patrimonio inmaterial de la música nicaragüense.', 'published'),
('music_alejandro-vega-matus', 'masaya', 'Alejandro Vega Matus', 'Alejandro Vega Matus', 'patrimonio', 'siglo_xx', 'Patrimonio inmaterial de la música nicaragüense.', 'published'),
('music_marimba-monimbo', 'masaya', 'La Marimba de Arco de Monimbó', 'La Marimba de Arco de Monimbó', 'patrimonio', 'siglo_xx', 'Patrimonio inmaterial de la música nicaragüense.', 'published'),
('music_el-gueguense', 'carazo', 'Música de El Güegüense', 'Música de El Güegüense', 'patrimonio', 'siglo_xx', 'Patrimonio inmaterial de la música nicaragüense.', 'published'),
('music_dimension-costena', 'raccs', 'Dimensión Costeña', 'Dimensión Costeña', 'caribe-contemporaneo', 'siglo_xx', 'Patrimonio inmaterial de la música nicaragüense.', 'published'),
('music_hernaldo-zuniga', 'masaya', 'Hernaldo Zúñiga', 'Hernaldo Zúñiga', 'caribe-contemporaneo', 'siglo_xx', 'Patrimonio inmaterial de la música nicaragüense.', 'published'),
('music_luis-enrique', 'madriz', 'Luis Enrique', 'Luis Enrique', 'caribe-contemporaneo', 'siglo_xx', 'Patrimonio inmaterial de la música nicaragüense.', 'published'),
('music_perrozompopo', 'managua', 'Perrozompopo (Ramón Mejía)', 'Perrozompopo (Ramón Mejía)', 'caribe-contemporaneo', 'siglo_xx', 'Patrimonio inmaterial de la música nicaragüense.', 'published'),
('music_mokuanes', 'esteli', 'Mokuanes', 'Mokuanes', 'caribe-contemporaneo', 'siglo_xx', 'Patrimonio inmaterial de la música nicaragüense.', 'published'),
('music_fuzion-4', 'carazo', 'Fuzion 4', 'Fuzion 4', 'caribe-contemporaneo', 'siglo_xx', 'Patrimonio inmaterial de la música nicaragüense.', 'published'),
('music_la-nueva-compania', 'managua', 'La Nueva Compañía', 'La Nueva Compañía', 'caribe-contemporaneo', 'siglo_xx', 'Patrimonio inmaterial de la música nicaragüense.', 'published')
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, artist_composer = EXCLUDED.artist_composer;

-- 4. EXPERIENCIAS TURÍSTICAS TERRITORIALES
INSERT INTO public.experiences (id, department_id, title, category, sensory_type, duration_hours, price_nio, price_usd, host_name, host_bio, difficulty, status, hidden_gem) VALUES
('exp_madriz_1', 'madriz', 'Navegación y flotación guiada entre las paredes milenarias del Cañón de Somoto', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', false),
('exp_madriz_2', 'madriz', 'Ruta vivencial de las rosquillas: del amasado campesino al horno de leña', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', false),
('exp_madriz_3', 'madriz', 'Ruta del Café: recorrido desde el almácigo y floración hasta el tostado y taza en finca', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_madriz_4', 'madriz', 'Taller vivencial de cestería con acícula de pino en San José de Cusmapa', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_madriz_5', 'madriz', 'Senderismo y avistamiento de aves en los pinares y nebliselva de Tepesomoto-La Pataste', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_madriz_6', 'madriz', 'Interpretación geológica del origen del Río Coco con baqueanos locales', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_leon_1', 'leon', 'Aventura: sandboarding, trekking volcánico, campamento y fotografía', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', false),
('exp_leon_2', 'leon', 'Pacífico: surf, playa, kayak, manglares y paseos en lancha', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', false),
('exp_leon_3', 'leon', 'Cultura: recorridos urbanos, museos, iglesias, arquitectura y muralismo', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_leon_4', 'leon', 'Literatura: Ruta Rubén Darío, poesía, bibliotecas y museos', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_leon_5', 'leon', 'Gastronomía: Ruta del Quesillo, mercados, dulcerías y cocina local', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_leon_6', 'leon', 'Comunidad: talleres artesanales, barro, cocina tradicional y guías locales', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_leon_7', 'leon', 'Caminata por las terrazas blancas de la Catedral y observación del centro histórico', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_leon_8', 'leon', 'Recorrido de mitos, leyendas y memoria viva por León y Sutiaba', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_rivas_1', 'rivas', 'Surf en San Juan del Sur y el corredor costero de Tola', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', false),
('exp_rivas_2', 'rivas', 'Ascensos y senderismo regulado en los volcanes Concepción y Maderas', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', false),
('exp_rivas_3', 'rivas', 'Ciclismo por las comunidades y paisajes de Ometepe', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_rivas_4', 'rivas', 'Conservación de tortugas mediante visitas autorizadas en La Flor', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_rivas_5', 'rivas', 'Arqueología y petroglifos de Ometepe', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_rivas_6', 'rivas', 'Senderismo en volcanes, reservas y bosques', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_rivas_7', 'rivas', 'Navegación por el Cocibolca entre San Jorge y Ometepe', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_rivas_8', 'rivas', 'Pesca y gastronomía con comunidades costeras', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_rivas_9', 'rivas', 'Turismo rural en Ometepe, Tola y municipios interiores', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_jinotega_1', 'jinotega', 'Canopy sobre cascadas torrenciales en El Cuá', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', false),
('exp_jinotega_2', 'jinotega', 'Paseos en kayak y avistamiento de aves en el Lago de Apanás', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', false),
('exp_jinotega_3', 'jinotega', 'Senderismo extremo en las murallas de Peñas Blancas', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_jinotega_4', 'jinotega', 'Cata profesional de café en cooperativas cafetaleras', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_jinotega_5', 'jinotega', 'Ascenso al Mirador Peña de la Cruz', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_jinotega_6', 'jinotega', 'Recorridos de cacao y naturaleza en San José de Bocay', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_jinotega_7', 'jinotega', 'Convivencia rural en fincas y comunidades del departamento', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_masaya_1', 'masaya', 'Volcanes: miradores, vulcanología, fotografía y senderismo autorizado en el Volcán Masaya', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', false),
('exp_masaya_2', 'masaya', 'Artesanía: cerámica en San Juan de Oriente y talleres de Monimbó', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', false),
('exp_masaya_3', 'masaya', 'Cultura: recorridos por Masaya y Monimbó con historia y fiestas vivas', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_masaya_4', 'masaya', 'Naturaleza: Laguna de Apoyo, Catarina y Tisma', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_masaya_5', 'masaya', 'Fotografía: miradores de Catarina, volcán y pueblos artesanales', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_masaya_6', 'masaya', 'Gastronomía: mercados, comunidades y cocinas familiares', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_masaya_7', 'masaya', 'Música: marimba y actividades culturales', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_masaya_8', 'masaya', 'Viveros: Catarina y municipios cercanos', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_masaya_9', 'masaya', 'Turismo comunitario con artesanos, familias, talleres y productores', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_granada_1', 'granada', 'Granada a pie: arquitectura, plazas, iglesias, mercados y museos', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', false),
('exp_granada_2', 'granada', 'Isletas: recorridos en lancha, kayak y observación de naturaleza', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', false),
('exp_granada_3', 'granada', 'Mombacho: senderismo, bosque nuboso, miradores e interpretación ambiental', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_granada_4', 'granada', 'Aviturismo en Mombacho, Laguna de Apoyo y espacios rurales', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_granada_5', 'granada', 'Experiencias de cacao con productores, elaboración y degustación', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_granada_6', 'granada', 'Fotografía de arquitectura, lago, volcanes y atardeceres', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_granada_7', 'granada', 'Ciclismo por rutas rurales y periurbanas', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_granada_8', 'granada', 'Turismo comunitario en Diriá, Diriomo, Nandaime y el entorno del Mombacho', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_matagalpa_1', 'matagalpa', 'Senderismo de observación de quetzales y tucanes en Selva Negra', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', false),
('exp_matagalpa_2', 'matagalpa', 'Talleres vivenciales de tejido en telar de cintura en El Chile', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', false),
('exp_matagalpa_3', 'matagalpa', 'Ruta del chocolate desde la mazorca de cacao hasta la barra artesanal', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_matagalpa_4', 'matagalpa', 'Bañarse bajo la cortina de la Cascada Santa Emilia', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_matagalpa_5', 'matagalpa', 'Excursiones guiadas por líderes indígenas comunitarios', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_matagalpa_6', 'matagalpa', 'Ruta del Café Matagalpino desde la planta hasta la catación', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_matagalpa_7', 'matagalpa', 'Ciclismo, fotografía y aviturismo entre bosques, fincas y miradores', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_esteli_1', 'esteli', 'Nado en la poza natural del Salto La Estanzuela', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', false),
('exp_esteli_2', 'esteli', 'Convivencia campesina y avistamiento de más de 200 especies de orquídeas en Miraflor', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', false),
('exp_esteli_3', 'esteli', 'Visita a las esculturas talladas en roca viva en El Jalacate', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_esteli_4', 'esteli', 'Tour educativo sobre el torcido a mano de puros de renombre mundial', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_esteli_5', 'esteli', 'Recorrido en bicicleta de montaña por los caminos de El Tisey', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_esteli_6', 'esteli', 'Ruta urbana de murales, artistas y memoria local', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_esteli_7', 'esteli', 'Talleres de cerámica, escultura, cuero y compra directa a creadores', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_chinandega_1', 'chinandega', 'Ascenso exigente al coloso activo San Cristóbal', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', false),
('exp_chinandega_2', 'chinandega', 'Caminata hacia el mirador del cráter del Cosigüina con vista a Honduras y El Salvador', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', false),
('exp_chinandega_3', 'chinandega', 'Kayak silencioso por los túneles de manglar en Padre Ramos', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_chinandega_4', 'chinandega', 'Surf de ola tubera en el famoso "The Boom" en Aserradores', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_chinandega_5', 'chinandega', 'Peregrinación al Lavatorio de la Plata en El Viejo (6 de diciembre)', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_managua_1', 'managua', 'Experiencias urbanas de cultura, entretenimiento, gastronomía y compras', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', false),
('exp_managua_2', 'managua', 'Geología y paisaje en Tiscapa, Xiloá y Apoyeque', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', false),
('exp_managua_3', 'managua', 'Naturaleza y senderismo en Chocoyero, Ticuantepe y El Crucero', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_managua_4', 'managua', 'Playa en Pochomil, Masachapa y las costas de Villa El Carmen', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_managua_5', 'managua', 'Navegación autorizada y atardeceres frente al lago Xolotlán', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_managua_6', 'managua', 'Ruta gastronómica por mercados, restaurantes y fritangas', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_managua_7', 'managua', 'Teatros, museos, patrimonio y centros culturales', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_carazo_1', 'carazo', 'Cultura viva: El Güegüense, Toro Huaco, El Viejo y La Vieja', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', false),
('exp_carazo_2', 'carazo', 'Ruta del café por fincas, cosecha, tostado y degustación', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', false),
('exp_carazo_3', 'carazo', 'Pacífico: La Boquita, Casares, Huehuete y El Tamarindo', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_carazo_4', 'carazo', 'Conservación regulada en Chacocente', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_carazo_5', 'carazo', 'Naturaleza, senderos y aves en reservas privadas', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_carazo_6', 'carazo', 'Ciclismo entre Dolores y áreas rurales', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_carazo_7', 'carazo', 'Cabalgatas, fincas y turismo comunitario', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_carazo_8', 'carazo', 'Mercados, cocina tradicional y gastronomía costera', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_chontales_1', 'chontales', 'Escalada y senderismo en los riscos de la Cordillera Amerrisque', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', false),
('exp_chontales_2', 'chontales', 'Exploración de la mayor colección de estatuaria lítica indígena en Juigalpa', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', false),
('exp_chontales_3', 'chontales', 'Paseo en lancha desde Puerto Díaz en el Gran Lago', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_chontales_4', 'chontales', 'Rutas agroturísticas por haciendas ganaderas sostenibles con ordeño limpio', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_chontales_5', 'chontales', 'Descubrimiento de petroglifos milenarios en cuevas de Amerrisque', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_chontales_6', 'chontales', 'Experiencia de finca con caballo, ganado, ordeño, queso y comida campesina', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_chontales_7', 'chontales', 'Ruta de cascadas, lago y comunidades con acceso verificado localmente', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_boaco_1', 'boaco', 'Caminatas por las escalinatas y miradores urbanos de la Ciudad de Dos Pisos', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', false),
('exp_boaco_2', 'boaco', 'Trekking al enigmático Cerro de la Vieja con guías locales', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', false),
('exp_boaco_3', 'boaco', 'Compra directa de sombreros de pita finamente tejidos a mano en Camoapa', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_boaco_4', 'boaco', 'Visita a queserías comunitarias y degustación de lácteos', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_boaco_5', 'boaco', 'Refrescante baño en las pozas del Río Malacatoya', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_boaco_6', 'boaco', 'Experiencia en finca ganadera con ordeño, queso y comida campesina', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_boaco_7', 'boaco', 'Ruta de café de montaña, cabalgatas, cascadas y aviturismo', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_nueva-segovia_1', 'nueva-segovia', 'Expedición y cumbre al Cerro Mogotón entre pinares y neblina', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', false),
('exp_nueva-segovia_2', 'nueva-segovia', 'Baños relajantes en pozas de aguas termales medicinales', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', false),
('exp_nueva-segovia_3', 'nueva-segovia', 'Cata de cafés ganadores de certámenes mundiales en Dipilto', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_nueva-segovia_4', 'nueva-segovia', 'Ruta histórica de Sandino por los cerros de Quilalí y El Chipote', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_nueva-segovia_5', 'nueva-segovia', 'Senderismo en la cordillera de Dipilto y Jalapa', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_nueva-segovia_6', 'nueva-segovia', 'Talleres de barro y compra directa a artesanos de Mozonte', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_nueva-segovia_7', 'nueva-segovia', 'Ruta productiva del maíz en Jalapa y del jocote en Macuelizo', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_rio-san-juan_1', 'rio-san-juan', 'Navegación en lancha rápida por los raudales de El Castillo', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', false),
('exp_rio-san-juan_2', 'rio-san-juan', 'Senderismo de selva virgen con guardarrecursos indígenas en Indio Maíz', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', false),
('exp_rio-san-juan_3', 'rio-san-juan', 'Talleres de pintura primitivista y artesanía en balsa en Solentiname', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_rio-san-juan_4', 'rio-san-juan', 'Pesca deportiva de captura y liberación del sábalo real gigante', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_rio-san-juan_5', 'rio-san-juan', 'Safari nocturno en bote para avistamiento de caimanes y aves nocturnas', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_rio-san-juan_6', 'rio-san-juan', 'Ruta del cacao y chocolate con productores locales', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_rio-san-juan_7', 'rio-san-juan', 'Kayak, aviturismo, arqueología y turismo comunitario en islas y humedales', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_raccn_1', 'raccn', 'Expediciones científicas y de ecoturismo en los senderos de Bosawás', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', false),
('exp_raccn_2', 'raccn', 'Navegación en pipante tradicional por los raudales del Río Coco', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', false),
('exp_raccn_3', 'raccn', 'Convivencia comunitaria en aldeas indígenas Mayangna y Miskita', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_raccn_4', 'raccn', 'Snorkel y buceo en los prístinos Cayos Miskitos', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_raccn_5', 'raccn', 'Degustación de mariscos recién capturados en Bilwi', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_raccs_1', 'raccs', 'Buceo y snorkel en los arrecifes de coral virgen de Little Corn Island', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', false),
('exp_raccs_2', 'raccs', 'Paseo en lancha a los islotes desiertos de arena blanca en Cayos Perlas', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', false),
('exp_raccs_3', 'raccs', 'Bailar al ritmo de Palo de Mayo en las comparsas callejeras de Bluefields', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_raccs_4', 'raccs', 'Pesca de langosta y degustación de rondón en la playa', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_raccs_5', 'raccs', 'Recorrido cultural por los pueblos Garífunas de Orinoco', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_raccs_6', 'raccs', 'Rutas de música, Palo de Mayo, calipso, reggae y cultura viva', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true),
('exp_raccs_7', 'raccs', 'Navegación comunitaria por lagunas, ríos, bahías y cayos', 'ecoturismo', 'adrenalina', 3.5, 350.00, 9.50, 'Guías Baqueanos Locales', 'Familias campesinas acreditadas', 'moderada', 'published', true)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category;

-- 5. DIRECTORIO NACIONAL DE EMERGENCIAS Y SEGURIDAD BAQUEANO
INSERT INTO public.emergencies (department_id, service_type, entity_name, phone_emergency, is_24_hours, notes) VALUES
('managua', 'policia', 'Policía Nacional de Nicaragua', '118', true, 'Atención nacional 24 horas'),
('managua', 'bomberos', 'Cuerpo Unificado de Bomberos', '115', true, 'Emergencias y rescate'),
('managua', 'cruz_roja', 'Cruz Roja Nicaragüense', '128', true, 'Ambulancias y primeros auxilios'),
('madriz', 'hospital', 'Hospital Departamental Juan Antonio Brenes Palacios (Somoto)', '50527222442', true, 'Hospital de referencia regional en Madriz'),
('leon', 'hospital', 'Hospital Escuela Óscar Danilo Rosales Argüello (HEODRA)', '50523112211', true, 'Hospital universitario regional de León'),
('granada', 'hospital', 'Hospital Amistad Japón-Nicaragua', '50525522201', true, 'Centro hospitalario de Granada'),
('matagalpa', 'hospital', 'Hospital Regional César Amador Molina', '50527722231', true, 'Atención médica integral en Las Brumas'),
('rivas', 'hospital', 'Hospital Gaspar García Laviana', '50525633311', true, 'Referencia departamental e Isla de Ometepe'),
('rio_san_juan', 'hospital', 'Hospital Departamental Dr. Luis Manuel Debayle (San Carlos)', '50525830022', true, 'Emergencias fluviales y médicas'),
('raccs', 'hospital', 'Hospital Regional Dr. Ernesto Sequeira Blanco (Bluefields)', '50525722210', true, 'Referencia para Bluefields y Corn Island');

-- 6. HISTORIA Y PRÓCERES DE LA IDENTIDAD NICARAGÜENSE
INSERT INTO public.historical_figures (id, department_id, full_name, role_title, birth_year, death_year, biography, legacy_summary, status) VALUES
('fig_ruben_dario', 'matagalpa', 'Rubén Darío (Félix Rubén García Sarmiento)', 'Príncipe de las Letras Castellanas y Padre del Modernismo', 1867, 1916, 'Nacido en Ciudad Darío (antiguo Chocoyos), revolucionó el idioma castellano en todo el mundo hispánico con Azul... y Prosas Profanas.', 'Renovador universal de la métrica poética y embajador inmortal de la dignidad nicaragüense.', 'published'),
('fig_augusto_sandino', 'masaya', 'General Augusto C. Sandino', 'Héroe Nacional y Defensor de la Soberanía', 1895, 1934, 'Nacido en Niquinohomo, lideró en Las Segovias el Ejército Defensor de la Soberanía Nacional contra la intervención armada extranjera.', 'Símbolo perenne de soberanía popular, justicia territorial campesina y dignidad latinoamericana.', 'published'),
('fig_jose_dolores_estrada', 'managua', 'General José Dolores Estrada Vado', 'Héroe de la Batalla de San Jacinto', 1792, 1869, 'Nacido en Nandaime, dirigió con arrojo y estrategia patriótica la victoria nicaragüense en la Hacienda San Jacinto el 14 de septiembre de 1856.', 'Defensa irreductible de la independencia patria contra el filibusterismo esclavista.', 'published'),
('fig_camilo_zapata', 'managua', 'Camilo Zapata', 'Creador del Son Nica', 1917, 2009, 'Pionero de la música típica nicaragüense al crear en compás 6/8 el ritmo autóctono Son Nica con el Caballito Chingo.', 'Fundador de la identidad musical popular y folclórica nicaragüense.', 'published'),
('fig_justo_santos', 'rivas', 'Justo Santos Cerda', 'Compositor del Himno Popular La Mora Limpia', 1931, 1958, 'Músico y guitarrista virtuoso creador de La Mora Limpia, considerada unánimemente el segundo himno de Nicaragua.', 'Creador del tema sonoro más identitario y conmovedor del folclore nacional.', 'published')
ON CONFLICT (id) DO UPDATE SET full_name = EXCLUDED.full_name, role_title = EXCLUDED.role_title;
