-- BAQUEANO · Importación territories-data.js → Supabase · parte 01 de 07
-- Generado desde supabase/imports/20261005_territories_import.sql. Ejecutar las partes EN ORDEN en el SQL Editor.
-- Idempotente: si una parte se ejecuta dos veces, no duplica (ON CONFLICT).
begin;
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-reserva-natural-tepesomoto-la-pataste', 'reserva-natural-tepesomoto-la-pataste', 'Reserva Natural Tepesomoto-La Pataste', 'reserva', null, 'Bosque Nuboso & Biodiversidad', 'fa-tree', 'madriz', null, null, 'Montaña protegida cerca de Somoto con bosque nuboso y pinares, fuente de agua para las comunidades y refugio de aves.', 'Montaña protegida cerca de Somoto con bosque nuboso y pinares, fuente de agua para las comunidades y refugio de aves.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'madriz::reserva natural tepesomoto la pataste', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-laguna-la-bruja-las-sabanas', 'laguna-la-bruja-las-sabanas', 'Laguna La Bruja (Las Sabanas)', 'laguna', null, 'Humedal de Altura & Canopy', 'fa-water', 'madriz', null, null, 'Laguna de altura en el municipio de Las Sabanas, rodeada de bosque de pino y clima fresco; se visita con guías comunitarios.', 'Laguna de altura en el municipio de Las Sabanas, rodeada de bosque de pino y clima fresco; se visita con guías comunitarios.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'madriz::laguna la bruja las sabanas', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-mirador-el-balcon-san-jose-de-cusmapa', 'mirador-el-balcon-san-jose-de-cusmapa', 'Mirador El Balcón (San José de Cusmapa)', 'mirador', null, 'Vistas al Pacífico & Serranías', 'fa-mountain-sun', 'madriz', null, null, 'Mirador en las serranías de Cusmapa, uno de los poblados más altos del país; en días despejados se divisa hacia el Golfo de Fonseca.', 'Mirador en las serranías de Cusmapa, uno de los poblados más altos del país; en días despejados se divisa hacia el Golfo de Fonseca.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'madriz::mirador el balcon san jose de cusmapa', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-parque-natural-el-majaste-san-juan-del-rio-coco', 'parque-natural-el-majaste-san-juan-del-rio-coco', 'Parque Natural El Majaste (San Juan del Río Coco)', 'cascada', null, 'Cafetales de Altura & Cascadas', 'fa-leaf', 'madriz', null, null, 'Área natural entre cafetales de altura del norte de Madriz, con senderos, pozas y caídas de agua.', 'Área natural entre cafetales de altura del norte de Madriz, con senderos, pozas y caídas de agua.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'madriz::parque natural el majaste san juan del rio coco', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-comunidad-indigena-san-jose-de-palmira-totogalpa', 'comunidad-indigena-san-jose-de-palmira-totogalpa', 'Comunidad Indígena San José de Palmira (Totogalpa)', 'turismo_comunitario', null, 'Turismo Rural Comunitario', 'fa-hands-holding-circle', 'madriz', null, null, 'Comunidad indígena de Totogalpa que recibe visitantes con turismo rural comunitario: vida campesina, cocina local y tradiciones.', 'Comunidad indígena de Totogalpa que recibe visitantes con turismo rural comunitario: vida campesina, cocina local y tradiciones.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'madriz::comunidad indigena san jose de palmira totogalpa', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-talleres-de-ceramica-de-loma-panda-san-lucas', 'talleres-de-ceramica-de-loma-panda-san-lucas', 'Talleres de Cerámica de Loma Panda (San Lucas)', 'centro_cultural', null, 'Alfarería Prehispánica', 'fa-palette', 'madriz', null, null, 'Talleres familiares de alfarería en San Lucas, donde se trabaja el barro con técnicas heredadas; se puede ver el proceso y comprar directo.', 'Talleres familiares de alfarería en San Lucas, donde se trabaja el barro con técnicas heredadas; se puede ver el proceso y comprar directo.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'madriz::talleres de ceramica de loma panda san lucas', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-parque-arqueologico-piedras-pintadas', 'parque-arqueologico-piedras-pintadas', 'Parque Arqueológico Piedras Pintadas', 'parque', null, 'Petroglifos & Memoria Viva', 'fa-feather', 'madriz', null, null, 'Rocas con petroglifos precolombinos que forman parte de la memoria ancestral de Madriz; se visitan con respeto y sin tocar los grabados.', 'Rocas con petroglifos precolombinos que forman parte de la memoria ancestral de Madriz; se visitan con respeto y sin tocar los grabados.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'madriz::parque arqueologico piedras pintadas', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-rosquillas-delicias-del-norte', 'rosquillas-delicias-del-norte', 'Rosquillas Delicias del Norte', 'atractivo', null, 'Gastronomía y emprendimiento local', 'fa-cookie-bite', 'madriz', null, null, 'Taller de rosquillas somoteñas que INTUR y el Mapa Nacional de Turismo mencionan como referencia en Somoto.', 'Taller de rosquillas somoteñas que INTUR y el Mapa Nacional de Turismo mencionan como referencia en Somoto.', null, null, 'missing', false, null, 'verified', '2026-10-05'::timestamptz, 'Mapa Nacional de Turismo', 'https://www.mapanicaragua.com/municipio-de-somoto/', 'other', '{"facts":"Empresa real de rosquillas somoteñas en Somoto. Fuentes periodísticas identifican a Flora (Florita) Ortiz como fundadora.","contact_note":"Contacto pendiente de confirmar directamente con el negocio.","price_note":{"text":"Consultar precio y horario al establecimiento.","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, true, 'territories-data.js', 'madriz::rosquillas delicias del norte', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-finca-entre-pinos', 'finca-entre-pinos', 'Finca Entre Pinos', 'agroturismo', null, 'Turismo rural · Senderismo', 'fa-house-chimney', 'madriz', null, null, 'Cabañas entre pinos, cedros y robles en El Rodeo de Cusmapa, unidas por puentes colgantes de árbol en árbol.', 'Cabañas entre pinos, cedros y robles en El Rodeo de Cusmapa, unidas por puentes colgantes de árbol en árbol.', null, null, 'missing', false, 'Bulevar de Cusmapa 5 km al este, El Rodeo.', 'verified', '2026-10-05'::timestamptz, 'INTUR · Catálogo de Iniciativas de Turismo Rural y Comunitario (2026)', null, 'other', '{"activities":"Senderismo, canopy, actividades agrícolas y avistamiento de aves.","services":"Alimentación, hospedaje, piscina climatizada, camping, juegos para niños y tienda de recuerdos.","hours":"9:00 a. m.–6:00 p. m.","modality":"Turismo rural","facts":"Cabañas entre pinos, cedros y robles en El Rodeo de Cusmapa, unidas por puentes colgantes de árbol en árbol.","map":"https://www.google.com/maps/d/u/0/edit?mid=1gJEZ4HTewWspc7_qtrxqICCTEkifU5U&usp=sharing","contact_note":"Contacto publicado por INTUR en el catálogo 2026; confirmar antes de viajar."}'::jsonb, true, 'territories-data.js', 'madriz::finca entre pinos', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-casa-de-huesped-la-ceibita', 'casa-de-huesped-la-ceibita', 'Casa de Huésped La Ceibita', 'agroturismo', null, 'Agroturismo · Senderismo', 'fa-seedling', 'madriz', null, null, 'Casa de familias anfitrionas junto al Cañón de Somoto, con tours al cañón y oficios tradicionales del campo.', 'Casa de familias anfitrionas junto al Cañón de Somoto, con tours al cañón y oficios tradicionales del campo.', null, null, 'missing', false, 'Entrada principal al Cañón de Somoto, 250 m al suroeste, Somoto.', 'verified', '2026-10-05'::timestamptz, 'INTUR · Catálogo de Iniciativas de Turismo Rural y Comunitario (2026)', null, 'other', '{"activities":"Senderismo, actividades agropecuarias, cabalgata, neumático, apicultura, ordeño y fogatas.","services":"Alimentación, hospedaje, tours al cañón y guía turístico.","hours":"Lunes a domingo, 6:00 a. m.–9:00 p. m.","modality":"Agroturismo","facts":"Casa de familias anfitrionas junto al Cañón de Somoto, con tours al cañón y oficios tradicionales del campo.","map":"https://www.google.com/maps/d/u/0/edit?mid=1qEo_gKYBh1qKs2ralmJFYM7KpFhlgJo&usp=sharing","contact_note":"Contacto publicado por INTUR en el catálogo 2026; confirmar antes de viajar."}'::jsonb, true, 'territories-data.js', 'madriz::casa de huesped la ceibita', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-rio-esteli', 'rio-esteli', 'Río Estelí', 'rio', null, 'Río · Paisaje', 'fa-water', 'madriz', 'madriz__telpaneca', null, 'Río principal de la cuenca de Estelí; su sistema fluvial se relaciona con el Salto de La Estanzuela.', 'Río principal de la cuenca de Estelí; su sistema fluvial se relaciona con el Salto de La Estanzuela.', 13.49602, -86.26757, 'approximate', false, null, 'verified', '2026-10-05'::timestamptz, 'GeoNames', 'https://mapcarta.com/es/19584058', 'other', '{"activities":"Paisaje, educación ambiental y senderismo en sitios asociados.","modality":"Ríos","facts":"Río principal de la cuenca de Estelí; su sistema fluvial se relaciona con el Salto de La Estanzuela."}'::jsonb, true, 'territories-data.js', 'madriz::rio esteli', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-insigne-basilica-catedral-de-leon', 'insigne-basilica-catedral-de-leon', 'Insigne Basílica Catedral de León', 'sitio_historico', null, 'Patrimonio Mundial, arquitectura, religión y fotografía', 'fa-church', 'leon', null, null, 'La catedral más grande de Centroamérica, Patrimonio de la Humanidad. Sus techos blancos se recorren a pie y guarda la tumba de Rubén Darío.', 'La catedral más grande de Centroamérica, Patrimonio de la Humanidad.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'leon::insigne basilica catedral de leon', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-museo-archivo-ruben-dario', 'museo-archivo-ruben-dario', 'Museo Archivo Rubén Darío', 'museo', null, 'Literatura, historia e identidad nacional', 'fa-book-open', 'leon', null, null, 'Casa donde vivió de niño Rubén Darío, el poeta del modernismo; conserva objetos, documentos y espacios de su vida en León.', 'Casa donde vivió de niño Rubén Darío, el poeta del modernismo; conserva objetos, documentos y espacios de su vida en León.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'leon::museo archivo ruben dario', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-museo-de-la-revolucion', 'museo-de-la-revolucion', 'Museo de la Revolución', 'museo', null, 'Historia política reciente y memoria nacional', 'fa-landmark', 'leon', null, null, 'Espacio dedicado a la historia política reciente de Nicaragua, con fotografías y relatos; desde su techo hay vistas del centro de León.', 'Espacio dedicado a la historia política reciente de Nicaragua, con fotografías y relatos; desde su techo hay vistas del centro de León.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'leon::museo de la revolucion', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-centro-de-arte-fundacion-ortiz-gurdian', 'centro-de-arte-fundacion-ortiz-gurdian', 'Centro de Arte Fundación Ortiz Gurdián', 'centro_cultural', null, 'Arte latinoamericano y europeo', 'fa-palette', 'leon', null, null, 'Colección de arte latinoamericano y europeo en casonas coloniales restauradas del centro de León.', 'Colección de arte latinoamericano y europeo en casonas coloniales restauradas del centro de León.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'leon::centro de arte fundacion ortiz gurdian', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-iglesia-san-juan-bautista-de-sutiaba', 'iglesia-san-juan-bautista-de-sutiaba', 'Iglesia San Juan Bautista de Sutiaba', 'sitio_historico', null, 'Patrimonio indígena, arquitectura y memoria', 'fa-place-of-worship', 'leon', null, null, 'Templo colonial del barrio indígena de Sutiaba, uno de los más antiguos de León, con su sol tallado en el techo de madera.', 'Templo colonial del barrio indígena de Sutiaba, uno de los más antiguos de León, con su sol tallado en el techo de madera.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'leon::iglesia san juan bautista de sutiaba', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-teatro-municipal-jose-de-la-cruz-mena', 'teatro-municipal-jose-de-la-cruz-mena', 'Teatro Municipal José de la Cruz Mena', 'centro_cultural', null, 'Cultura, música, arquitectura y artes escénicas', 'fa-masks-theater', 'leon', null, null, 'Teatro histórico de León que lleva el nombre del compositor leonés José de la Cruz Mena; sede de conciertos y artes escénicas.', 'Teatro histórico de León que lleva el nombre del compositor leonés José de la Cruz Mena; sede de conciertos y artes escénicas.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'leon::teatro municipal jose de la cruz mena', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-museo-de-mitos-y-leyendas', 'museo-de-mitos-y-leyendas', 'Museo de Mitos y Leyendas', 'museo', null, 'Narrativa popular y memoria viva', 'fa-book-skull', 'leon', null, null, 'Museo que reúne personajes de la tradición oral nicaragüense, como la Carreta Nahua y la Gigantona, en figuras y relatos.', 'Museo que reúne personajes de la tradición oral nicaragüense, como la Carreta Nahua y la Gigantona, en figuras y relatos.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'leon::museo de mitos y leyendas', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-volcan-telica', 'volcan-telica', 'Volcán Telica', 'volcan', null, 'Senderismo, fotografía y observación geológica', 'fa-mountain-sun', 'leon', 'leon__telica', null, 'Volcán activo de la cordillera de los Maribios; las caminatas guiadas suben hasta el borde del cráter, muy buscado al atardecer.', 'Volcán activo de la cordillera de los Maribios; las caminatas guiadas suben hasta el borde del cráter, muy buscado al atardecer.', 12.6, -86.87, 'reference', false, null, 'verified', '2026-10-05'::timestamptz, 'INETER (catálogo de naturaleza 2026)', null, 'other', '{"activities":"Senderismo con guía, geoturismo y paisaje volcánico.","facts":"Estratovolcán activo de la Cordillera de los Maribios, monitoreado por INETER."}'::jsonb, true, 'territories-data.js', 'leon::volcan telica', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-hervideros-de-san-jacinto', 'hervideros-de-san-jacinto', 'Hervideros de San Jacinto', 'turismo_comunitario', null, 'Geología, educación ambiental y turismo comunitario', 'fa-temperature-high', 'leon', null, null, 'Campo de fumarolas y lodo hirviente al pie del Telica; la comunidad de San Jacinto guía el recorrido por senderos seguros.', 'Campo de fumarolas y lodo hirviente al pie del Telica; la comunidad de San Jacinto guía el recorrido por senderos seguros.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'leon::hervideros de san jacinto', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-volcan-el-hoyo', 'volcan-el-hoyo', 'Volcán El Hoyo', 'volcan', null, 'Senderismo, campamento y aventura', 'fa-mountain', 'leon', null, null, 'Volcán de los Maribios con travesías de senderismo y campamento, conocido por su gran agujero en la ladera.', 'Volcán de los Maribios con travesías de senderismo y campamento, conocido por su gran agujero en la ladera.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'leon::volcan el hoyo', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-volcan-momotombo', 'volcan-momotombo', 'Volcán Momotombo', 'volcan', null, 'Paisaje volcánico, historia y lago Xolotlán', 'fa-volcano', 'leon', null, null, 'Volcán de cono casi perfecto a orillas del lago Xolotlán, símbolo de León y vecino de las Ruinas de León Viejo.', 'Volcán de cono casi perfecto a orillas del lago Xolotlán, símbolo de León y vecino de las Ruinas de León Viejo.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'leon::volcan momotombo', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-ruinas-de-leon-viejo', 'ruinas-de-leon-viejo', 'Ruinas de León Viejo', 'sitio_historico', null, 'Patrimonio Mundial y arqueología colonial', 'fa-landmark', 'leon', null, null, 'Restos de la primera ciudad de León, a orillas del Xolotlán y frente al Momotombo; Patrimonio de la Humanidad.', 'Restos de la primera ciudad de León, a orillas del Xolotlán y frente al Momotombo; Patrimonio de la Humanidad.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'leon::ruinas de leon viejo', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-las-penitas-y-poneloya', 'las-penitas-y-poneloya', 'Las Peñitas y Poneloya', 'playa', null, 'Playa, surf, gastronomía marina y atardeceres', 'fa-umbrella-beach', 'leon', null, null, 'Playas del Pacífico a pocos minutos de León, con pueblos de pescadores, olas para surf y atardeceres.', 'Playas del Pacífico a pocos minutos de León, con pueblos de pescadores, olas para surf y atardeceres.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'leon::las penitas y poneloya', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-isla-juan-venado', 'isla-juan-venado', 'Isla Juan Venado', 'isla', null, 'Manglares, fauna, lancha y kayak', 'fa-water', 'leon', 'leon__leon', null, 'Reserva de estero y manglares frente a Las Peñitas, con aves acuáticas y playas de anidación de tortugas; se recorre en lancha.', 'Reserva de estero y manglares frente a Las Peñitas, con aves acuáticas y playas de anidación de tortugas; se recorre en lancha.', 12.31306, -86.94889, 'approximate', false, null, 'verified', '2026-10-05'::timestamptz, 'Wikidata / Mapa Nacional de Turismo', 'https://www.mapanicaragua.com/sol-y-playa/', 'other', '{"activities":"Lancha, kayak, manglares y observación de fauna.","facts":"Isla y reserva natural paralela a la costa del Pacífico leonés, con manglares, fauna y playas de anidación de tortugas."}'::jsonb, true, 'territories-data.js', 'leon::isla juan venado', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-rancho-los-alpes', 'rancho-los-alpes', 'Rancho Los Alpes', 'turismo_rural', null, 'Turismo rural · Senderos', 'fa-house-chimney', 'leon', null, null, 'Rancho de descanso en la comarca San Carlos con balsas de bambú, kayak, tirolesa y taller de tortillas.', 'Rancho de descanso en la comarca San Carlos con balsas de bambú, kayak, tirolesa y taller de tortillas.', null, null, 'missing', false, 'Km 99 carretera León–Poneloya, 1.5 km a la derecha por camino de macadán hacia el Centro de Salud de la comarca San Carlos.', 'verified', '2026-10-05'::timestamptz, 'INTUR · Catálogo de Iniciativas de Turismo Rural y Comunitario (2026)', null, 'other', '{"activities":"Senderos, balsas de bambú, kayak y neumáticos, cabalgatas, tours ambientales, taller de tortillas, cultivo de peces y tirolesa.","services":"Hospedaje, camping, alimentación y local para eventos.","hours":"Lunes a domingo, 8:00 a. m.–7:00 p. m. (reservar con 48 horas).","modality":"Turismo rural","facts":"Rancho de descanso en la comarca San Carlos con balsas de bambú, kayak, tirolesa y taller de tortillas.","map":"https://www.google.com/maps/d/u/0/edit?mid=11yDJH2RrUdILT1SCPfF0UDlJWg1CJlM&usp=sharing","contact_note":"Contacto publicado por INTUR en el catálogo 2026; confirmar antes de viajar."}'::jsonb, true, 'territories-data.js', 'leon::rancho los alpes', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-playa-las-penitas', 'playa-las-penitas', 'Playa Las Peñitas', 'playa', null, 'Playa · Surf', 'fa-umbrella-beach', 'leon', 'leon__leon', null, 'Playa y comunidad pesquera cercana a León, junto a la Reserva Natural Isla Juan Venado; popular entre surfistas.', 'Playa y comunidad pesquera cercana a León, junto a la Reserva Natural Isla Juan Venado; popular entre surfistas.', 12.3614, -87.0215, 'exact', true, null, 'verified', '2026-10-05'::timestamptz, 'Mapa Nacional de Turismo / GeoNames', 'https://www.mapanicaragua.com/sol-y-playa/', 'other', '{"activities":"Surf, gastronomía marina, paseos en lancha y acceso a Juan Venado.","modality":"Playas","facts":"Playa y comunidad pesquera cercana a León, junto a la Reserva Natural Isla Juan Venado; popular entre surfistas."}'::jsonb, true, 'territories-data.js', 'leon::playa las penitas', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-playa-poneloya', 'playa-poneloya', 'Playa Poneloya', 'playa', null, 'Playa · Baño', 'fa-umbrella-beach', 'leon', 'leon__leon', null, 'Tradicional balneario del litoral leonés y comunidad pesquera cercana a Las Peñitas.', 'Tradicional balneario del litoral leonés y comunidad pesquera cercana a Las Peñitas.', 12.3783, -87.0422, 'exact', true, null, 'verified', '2026-10-05'::timestamptz, 'Mapa Nacional de Turismo / GeoNames', 'https://www.mapanicaragua.com/videos/', 'other', '{"activities":"Baño, gastronomía, pesca y atardecer.","modality":"Playas","facts":"Tradicional balneario del litoral leonés y comunidad pesquera cercana a Las Peñitas."}'::jsonb, true, 'territories-data.js', 'leon::playa poneloya', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-reserva-de-biosfera-isla-de-ometepe', 'reserva-de-biosfera-isla-de-ometepe', 'Reserva de Biosfera Isla de Ometepe', 'isla', null, 'Dos volcanes, naturaleza, arqueología y turismo rural', 'fa-mountain-sun', 'rivas', null, null, 'Dos volcanes, Concepción y Maderas, unidos por un istmo en medio del Cocibolca; Reserva de Biosfera con petroglifos y comunidades rurales.', 'Dos volcanes, Concepción y Maderas, unidos por un istmo en medio del Cocibolca; Reserva de Biosfera con petroglifos y comunidades rurales.', 11.491051, -85.554472, 'approximate', false, null, 'verified', '2026-10-05'::timestamptz, 'INTUR', 'https://www.intur.gob.ni/recinto/isla-de-ometepe/', 'other', '{"facts":"Destino oficial de Nicaragua formado por los volcanes Concepción y Maderas. Visit Nicaragua destaca senderismo, la laguna del cráter del Maderas y la Cascada de San Ramón.","contact_note":"INTUR cuenta con delegación en la Isla de Ometepe; los servicios privados se verifican uno por uno.","price_note":{"text":"Cada servicio tiene proveedor y precio distinto; no hay una tarifa única.","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, true, 'territories-data.js', 'rivas::reserva de biosfera isla de ometepe', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-volcan-concepcion', 'volcan-concepcion', 'Volcán Concepción', 'volcan', null, 'Senderismo regulado, geología, fotografía y naturaleza', 'fa-volcano', 'rivas', null, 'Isla de Ometepe', 'El volcán más alto de Ometepe, activo; su ascenso es exigente y se hace solo con guía autorizado.', 'El volcán más alto de Ometepe, activo; su ascenso es exigente y se hace solo con guía autorizado.', 11.53901, -85.62258, 'reference', false, null, 'verified', '2026-10-05'::timestamptz, 'Visit Nicaragua / OpenStreetMap (catálogo de naturaleza 2026)', null, 'other', '{"activities":"Ascenso exigente con guía experimentado, fotografía y geoturismo.","facts":"Uno de los dos grandes volcanes de Ometepe y uno de los volcanes activos más representativos de Nicaragua."}'::jsonb, true, 'territories-data.js', 'rivas::volcan concepcion', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-volcan-maderas', 'volcan-maderas', 'Volcán Maderas', 'volcan', null, 'Bosque, biodiversidad, senderismo y vida rural', 'fa-mountain', 'rivas', 'rivas__altagracia', null, 'Volcán inactivo de Ometepe cubierto de bosque nuboso, con una laguna en el cráter y fincas en sus faldas.', 'Volcán inactivo de Ometepe cubierto de bosque nuboso, con una laguna en el cráter y fincas en sus faldas.', 11.44452, -85.51197, 'reference', false, null, 'verified', '2026-10-05'::timestamptz, 'Visit Nicaragua / OpenStreetMap (catálogo de naturaleza 2026)', null, 'other', '{"activities":"Senderismo con guía, bosque nuboso, laguna cratérica y fotografía.","facts":"Volcán cubierto por bosque húmedo y nuboso; su entorno forma parte de la Reserva de Biosfera Isla de Ometepe."}'::jsonb, true, 'territories-data.js', 'rivas::volcan maderas', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-punta-jesus-maria', 'punta-jesus-maria', 'Punta Jesús María', 'atractivo', null, 'Atardecer, fotografía y vistas del Cocibolca', 'fa-camera', 'rivas', null, null, 'Lengua de arena en Ometepe que se adentra en el Lago Cocibolca; famosa por sus atardeceres.', 'Lengua de arena en Ometepe que se adentra en el Lago Cocibolca; famosa por sus atardeceres.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'rivas::punta jesus maria', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-reserva-natural-charco-verde', 'reserva-natural-charco-verde', 'Reserva Natural Charco Verde', 'lago', null, 'Mariposario, senderos, aves, bosque y lago', 'fa-feather', 'rivas', null, null, 'Reserva en Ometepe con laguna, senderos, mariposario y monos aulladores, frente a playas del lago.', 'Reserva en Ometepe con laguna, senderos, mariposario y monos aulladores, frente a playas del lago.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'rivas::reserva natural charco verde', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-ojo-de-agua-y-playa-santo-domingo', 'ojo-de-agua-y-playa-santo-domingo', 'Ojo de Agua y Playa Santo Domingo', 'playa', null, 'Naturaleza, descanso, ciclismo y corredor turístico', 'fa-droplet', 'rivas', null, null, 'Ojo de Agua es un balneario de agua cristalina entre árboles; Playa Santo Domingo es la franja de arena volcánica del istmo de Ometepe.', 'Ojo de Agua es un balneario de agua cristalina entre árboles; Playa Santo Domingo es la franja de arena volcánica del istmo de Ometepe.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'rivas::ojo de agua y playa santo domingo', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-cascada-de-san-ramon', 'cascada-de-san-ramon', 'Cascada de San Ramón', 'cascada', null, 'Caminata, bosque y paisaje natural de Altagracia', 'fa-water', 'rivas', null, null, 'Cascada en la ladera del Volcán Maderas a la que se llega con una caminata por bosque.', 'Cascada en la ladera del Volcán Maderas a la que se llega con una caminata por bosque.', 11.43424, -85.51924, 'exact', true, null, 'verified', '2026-10-05'::timestamptz, 'Visit Nicaragua', 'https://www.visitanicaragua.com/islas/isla-de-ometepe/', 'other', '{"facts":"Atractivo reconocido por Visit Nicaragua, en la comunidad de San Ramón (Altagracia), en las faldas del volcán Maderas; se llega caminando.","price_note":{"text":"Consultar la tarifa vigente en el acceso.","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, true, 'territories-data.js', 'rivas::cascada de san ramon', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-museo-el-ceibo-y-petroglifos-de-ometepe', 'museo-el-ceibo-y-petroglifos-de-ometepe', 'Museo El Ceibo y petroglifos de Ometepe', 'museo', null, 'Arqueología, cerámica e historia precolombina', 'fa-landmark', 'rivas', null, null, 'Museo en Ometepe con colecciones precolombinas y numismáticas; la isla conserva numerosos petroglifos en sus fincas y senderos.', 'Museo en Ometepe con colecciones precolombinas y numismáticas; la isla conserva numerosos petroglifos en sus fincas y senderos.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'rivas::museo el ceibo y petroglifos de ometepe', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-san-juan-del-sur-y-cristo-de-la-misericordia', 'san-juan-del-sur-y-cristo-de-la-misericordia', 'San Juan del Sur y Cristo de la Misericordia', 'atractivo', null, 'Bahía, paisaje, gastronomía y atardeceres', 'fa-anchor', 'rivas', null, null, 'Bahía de pescadores rodeada de playas para surf y navegación, vigilada por el mirador del Cristo de la Misericordia.', 'Bahía de pescadores rodeada de playas para surf y navegación, vigilada por el mirador del Cristo de la Misericordia.', null, null, 'missing', false, null, 'verified', '2026-10-05'::timestamptz, 'Mapa Nacional de Turismo', 'https://www.mapanicaragua.com/municipio-de-san-juan-del-sur/', 'other', '{"facts":"La bahía es uno de los principales atractivos del municipio. El Cristo de la Misericordia es una escultura de 15 m sobre un pedestal de 9 m y funciona como mirador panorámico.","price_note":{"text":"Consultar la tarifa vigente en el sitio.","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, true, 'territories-data.js', 'rivas::san juan del sur y cristo de la misericordia', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-maderas-marsella-remanso-hermosa-y-el-coco', 'maderas-marsella-remanso-hermosa-y-el-coco', 'Maderas, Marsella, Remanso, Hermosa y El Coco', 'playa', null, 'Playas, surf, recreación y naturaleza', 'fa-water', 'rivas', null, null, 'Playas del Pacífico alrededor de San Juan del Sur, buscadas para surf, baño y descanso.', 'Playas del Pacífico alrededor de San Juan del Sur, buscadas para surf, baño y descanso.', null, null, 'missing', false, null, 'verified', '2026-10-05'::timestamptz, 'INTUR', 'https://www.intur.gob.ni/2021/09/13/torneo-centroamericano-de-surf-se-despide-de-playa-maderas/', 'other', '{"facts":"Playa Maderas está reconocida oficialmente por INTUR y el Mapa Nacional de Turismo; destaca por sus olas y la práctica de surf.","contact_note":"Sin escuela ni teléfono asociado hasta tener ficha comercial verificada.","price_note":{"text":"Acceso y servicios de surf: consultar con el proveedor.","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, true, 'territories-data.js', 'rivas::maderas marsella remanso hermosa y el coco', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-refugio-de-vida-silvestre-la-flor', 'refugio-de-vida-silvestre-la-flor', 'Refugio de Vida Silvestre La Flor', 'reserva', null, 'Conservación de tortugas y experiencias reguladas', 'fa-shield-heart', 'rivas', null, null, 'Playa protegida donde llegan a desovar tortugas marinas, con visitas reguladas por guardaparques.', 'Playa protegida donde llegan a desovar tortugas marinas, con visitas reguladas por guardaparques.', null, null, 'missing', false, null, 'verified', '2026-10-05'::timestamptz, 'MARENA', 'https://www.marena.gob.ni/2026/09/08/ii-arribada-de-tortugas-en-la-flor/', 'other', '{"facts":"Área protegida de 7,349 hectáreas y uno de los principales sitios de anidación de tortugas marinas. MARENA reportó una arribada de 30,388 hembras paslama en septiembre de 2026.","contact_note":"Información institucional: MARENA.","price_note":{"text":"MARENA (15/04/2025): C$100 nacionales y C$200 visitantes de otras nacionalidades; niños pagan la mitad. Horario especial publicado en septiembre de 2026: 8:30 a. m.–5:00 p. m. Revalidar.","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, true, 'territories-data.js', 'rivas::refugio de vida silvestre la flor', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-corredor-de-playas-de-tola', 'corredor-de-playas-de-tola', 'Corredor de playas de Tola', 'turismo_comunitario', null, 'Popoyo, Guasacate, Santana, Colorado, Gigante y comunidades', 'fa-umbrella-beach', 'rivas', null, null, 'Costa del municipio de Tola con playas como Popoyo, Guasacate, Santana, Colorado y Gigante, reconocidas por el surf.', 'Costa del municipio de Tola con playas como Popoyo, Guasacate, Santana, Colorado y Gigante, reconocidas por el surf.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'rivas::corredor de playas de tola', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-puerto-de-san-jorge', 'puerto-de-san-jorge', 'Puerto de San Jorge', 'atractivo', null, 'Puerta lacustre, ferris y transporte hacia Ometepe', 'fa-ship', 'rivas', null, null, 'Puerto lacustre de Rivas desde donde salen los ferris y lanchas hacia la Isla de Ometepe.', 'Puerto lacustre de Rivas desde donde salen los ferris y lanchas hacia la Isla de Ometepe.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'rivas::puerto de san jorge', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-ciudad-de-rivas', 'ciudad-de-rivas', 'Ciudad de Rivas', 'sitio_historico', null, 'Historia, mercados, arquitectura, gastronomía y servicios', 'fa-building-columns', 'rivas', null, null, 'Cabecera departamental con iglesias, mercado y servicios; punto de paso entre San Juan del Sur, San Jorge y la frontera sur.', 'Cabecera departamental con iglesias, mercado y servicios; punto de paso entre San Juan del Sur, San Jorge y la frontera sur.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'rivas::ciudad de rivas', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-hostal-puesta-del-sol-ometepe', 'hostal-puesta-del-sol-ometepe', 'Hostal Puesta del Sol (Ometepe)', 'turismo_comunitario', null, 'Turismo rural y comunitario · Senderismo', 'fa-people-group', 'rivas', null, null, 'Hostal familiar en La Paloma, Moyogalpa, con habitaciones sencillas, playa del lago y clases de cocina nicaragüense.', 'Hostal familiar en La Paloma, Moyogalpa, con habitaciones sencillas, playa del lago y clases de cocina nicaragüense.', null, null, 'missing', false, 'Puerto de Moyogalpa 1½ al sur, comunidad La Paloma, escuela 400 m al lago y 175 vrs al sur.', 'verified', '2026-10-05'::timestamptz, 'INTUR · Catálogo de Iniciativas de Turismo Rural y Comunitario (2026)', null, 'other', '{"activities":"Senderismo, kayak, bicicleta, tours a los volcanes, proceso del vino de jamaica y clases de cocina.","services":"Alimentación, hospedaje y playa.","hours":"Lunes a sábado, 8:00 a. m.–6:00 p. m.","modality":"Turismo rural y comunitario","facts":"Hostal familiar en La Paloma, Moyogalpa, con habitaciones sencillas, playa del lago y clases de cocina nicaragüense.","map":"https://www.google.com/maps/d/u/0/edit?mid=12UuBdxsAO5ic69l9X7e_p1__cV1c_6c&usp=sharing","contact_note":"Contacto publicado por INTUR en el catálogo 2026; confirmar antes de viajar."}'::jsonb, true, 'territories-data.js', 'rivas::hostal puesta del sol ometepe', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-finca-magdalena-ometepe', 'finca-magdalena-ometepe', 'Finca Magdalena (Ometepe)', 'turismo_comunitario', null, 'Turismo rural y comunitario · Senderismo', 'fa-people-group', 'rivas', null, null, 'Finca agroturística emblemática de Altagracia, ejemplo de desarrollo comunitario, con café y petroglifos.', 'Finca agroturística emblemática de Altagracia, ejemplo de desarrollo comunitario, con café y petroglifos.', null, null, 'missing', false, 'Café Campestre 20 m al este, 1 km al sur, Altagracia.', 'verified', '2026-10-05'::timestamptz, 'INTUR · Catálogo de Iniciativas de Turismo Rural y Comunitario (2026)', null, 'other', '{"activities":"Senderismo, tours a petroglifos y tours del café.","services":"Alimentación, hospedaje y piscina natural.","hours":"Lunes a sábado, 6:00 a. m.–9:00 p. m.","modality":"Turismo rural y comunitario","facts":"Finca agroturística emblemática de Altagracia, ejemplo de desarrollo comunitario, con café y petroglifos.","map":"https://www.google.com/maps/d/u/0/edit?mid=1HaFUqB9NbLmGlUOTiRw8Ih8Z8COdp2o&usp=sharing","contact_note":"Contacto publicado por INTUR en el catálogo 2026; confirmar antes de viajar."}'::jsonb, true, 'territories-data.js', 'rivas::finca magdalena ometepe', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-playa-san-juan-del-sur', 'playa-san-juan-del-sur', 'Playa San Juan del Sur', 'playa', null, 'Playa · Natación', 'fa-umbrella-beach', 'rivas', 'rivas__san_juan_del_sur', null, 'Bahía en forma de herradura, de oleaje generalmente suave y amplia infraestructura turística; uno de los destinos costeros más visitados del país.', 'Bahía en forma de herradura, de oleaje generalmente suave y amplia infraestructura turística; uno de los destinos costeros más visitados del país.', 11.2548, -85.8729, 'exact', true, null, 'verified', '2026-10-05'::timestamptz, 'Visit Nicaragua / Mapcarta-OSM', 'https://visitanicaragua.com/en/beaches/San-Juan-del-Sur-beach/', 'other', '{"activities":"Natación, kayak, paseos en lancha, gastronomía y atardecer.","modality":"Playas","facts":"Bahía en forma de herradura, de oleaje generalmente suave y amplia infraestructura turística; uno de los destinos costeros más visitados del país."}'::jsonb, true, 'territories-data.js', 'rivas::playa san juan del sur', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-playa-maderas', 'playa-maderas', 'Playa Maderas', 'playa', null, 'Playa · Surf', 'fa-umbrella-beach', 'rivas', 'rivas__san_juan_del_sur', null, 'Playa reconocida por el surf, con oleaje consistente, acantilados y vegetación tropical, a unos minutos al norte de San Juan del Sur.', 'Playa reconocida por el surf, con oleaje consistente, acantilados y vegetación tropical, a unos minutos al norte de San Juan del Sur.', 11.295, -85.91, 'exact', true, null, 'verified', '2026-10-05'::timestamptz, 'Visit Nicaragua / OpenStreetMap', 'https://www.visitanicaragua.com/playas/playa-maderas/', 'other', '{"activities":"Surf, caminata, atardecer y fotografía.","modality":"Playas","facts":"Playa reconocida por el surf, con oleaje consistente, acantilados y vegetación tropical, a unos minutos al norte de San Juan del Sur."}'::jsonb, true, 'territories-data.js', 'rivas::playa maderas', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
commit;
