-- BAQUEANO · Importación territories-data.js → Supabase · parte 02 de 07
-- Generado desde supabase/imports/20261005_territories_import.sql. Ejecutar las partes EN ORDEN en el SQL Editor.
-- Idempotente: si una parte se ejecuta dos veces, no duplica (ON CONFLICT).
begin;
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-playa-remanso', 'playa-remanso', 'Playa Remanso', 'playa', null, 'Playa · Surf', 'fa-umbrella-beach', 'rivas', 'rivas__san_juan_del_sur', null, 'Pequeña bahía al sur de San Juan del Sur, conocida por el surf y su ambiente tranquilo; el Mapa Nacional de Turismo la incluye entre las playas del municipio.', 'Pequeña bahía al sur de San Juan del Sur, conocida por el surf y su ambiente tranquilo; el Mapa Nacional de Turismo la incluye entre las playas del municipio.', 11.22249, -85.84622, 'exact', true, null, 'verified', '2026-10-05'::timestamptz, 'Mapa Nacional de Turismo / OpenStreetMap', 'https://www.mapanicaragua.com/municipio-de-san-juan-del-sur/', 'other', '{"activities":"Surf, baño, descanso y gastronomía local.","modality":"Playas","facts":"Pequeña bahía al sur de San Juan del Sur, conocida por el surf y su ambiente tranquilo; el Mapa Nacional de Turismo la incluye entre las playas del municipio."}'::jsonb, true, 'territories-data.js', 'rivas::playa remanso', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-playa-el-coco', 'playa-el-coco', 'Playa El Coco', 'playa', null, 'Playa · Baño', 'fa-umbrella-beach', 'rivas', 'rivas__san_juan_del_sur', null, 'Amplia playa de arena fina y oleaje relativamente tranquilo, ubicada al sur de San Juan del Sur.', 'Amplia playa de arena fina y oleaje relativamente tranquilo, ubicada al sur de San Juan del Sur.', 11.1559, -85.7998, 'exact', true, null, 'verified', '2026-10-05'::timestamptz, 'Mapa Nacional de Turismo', 'https://www.mapanicaragua.com/sol-y-playa/', 'other', '{"activities":"Baño, caminata, paseo a caballo y observación de aves.","modality":"Playas","facts":"Amplia playa de arena fina y oleaje relativamente tranquilo, ubicada al sur de San Juan del Sur."}'::jsonb, true, 'territories-data.js', 'rivas::playa el coco', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-popoyo-y-guasacate', 'popoyo-y-guasacate', 'Popoyo y Guasacate', 'playa', null, 'Playa · Surf avanzado', 'fa-umbrella-beach', 'rivas', 'rivas__tola', null, 'Zona costera de Tola reconocida internacionalmente por el surf; Popoyo destaca por la consistencia y la potencia de sus olas.', 'Zona costera de Tola reconocida internacionalmente por el surf; Popoyo destaca por la consistencia y la potencia de sus olas.', 11.473, -86.1279, 'exact', true, null, 'verified', '2026-10-05'::timestamptz, 'Mapa Nacional de Turismo / OpenStreetMap', 'https://www.mapanicaragua.com/sol-y-playa/', 'other', '{"activities":"Surf avanzado, fotografía, descanso y gastronomía.","modality":"Playas","facts":"Zona costera de Tola reconocida internacionalmente por el surf; Popoyo destaca por la consistencia y la potencia de sus olas."}'::jsonb, true, 'territories-data.js', 'rivas::popoyo y guasacate', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-playa-gigante', 'playa-gigante', 'Playa Gigante', 'playa', null, 'Playa · Baño', 'fa-umbrella-beach', 'rivas', 'rivas__tola', null, 'Bahía y comunidad costera de Tola incluida en la oferta turística oficial de la Costa Esmeralda.', 'Bahía y comunidad costera de Tola incluida en la oferta turística oficial de la Costa Esmeralda.', 11.3911, -86.0326, 'exact', true, null, 'verified', '2026-10-05'::timestamptz, 'Mapa Nacional de Turismo / Wikidata-OSM', 'https://www.mapanicaragua.com/videos/', 'other', '{"activities":"Baño, pesca, paseos en lancha, gastronomía y atardecer.","modality":"Playas","facts":"Bahía y comunidad costera de Tola incluida en la oferta turística oficial de la Costa Esmeralda."}'::jsonb, true, 'territories-data.js', 'rivas::playa gigante', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-cascada-la-luna-el-cua', 'cascada-la-luna-el-cua', 'Cascada La Luna & El Cuá', 'cascada', null, 'Nebliselva & Canopy', 'fa-cloud-rain', 'jinotega', null, null, 'Cascada rodeada de bosque húmedo en la zona de El Cuá, en el norte montañoso de Jinotega.', 'Cascada rodeada de bosque húmedo en la zona de El Cuá, en el norte montañoso de Jinotega.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'jinotega::cascada la luna el cua', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-lago-de-apanas', 'lago-de-apanas', 'Lago de Apanás', 'laguna', null, 'Humedal Ramsar', 'fa-water', 'jinotega', 'jinotega__jinotega', null, 'Lago artificial entre montañas al norte de Jinotega, con comunidades de pescadores y paisajes de neblina.', 'Lago artificial entre montañas al norte de Jinotega, con comunidades de pescadores y paisajes de neblina.', 13.194444, -85.976389, 'centroid', false, null, 'verified', '2026-10-05'::timestamptz, 'Wikidata / OpenStreetMap (catálogo de naturaleza 2026)', null, 'other', '{"activities":"Paisaje, pesca recreativa donde esté autorizada, observación de aves y turismo rural.","facts":"Lago artificial de gran importancia hidroeléctrica y ambiental en Jinotega, reconocido como sitio Ramsar."}'::jsonb, true, 'territories-data.js', 'jinotega::lago de apanas', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-pena-de-la-cruz', 'pena-de-la-cruz', 'Peña de La Cruz', 'mirador', null, 'Mirador Panorámico', 'fa-mountain', 'jinotega', null, null, 'Cerro con una cruz que domina la ciudad de Jinotega; la subida ofrece vista a todo el valle.', 'Cerro con una cruz que domina la ciudad de Jinotega; la subida ofrece vista a todo el valle.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'jinotega::pena de la cruz', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-reserva-natural-macizo-de-penas-blancas', 'reserva-natural-macizo-de-penas-blancas', 'Reserva Natural Macizo de Peñas Blancas', 'reserva', null, 'Bosque Nuboso Prístino', 'fa-tree', 'jinotega', null, null, 'Macizo rocoso con bosque nuboso, nacientes de agua y cascadas, parte de la zona de amortiguamiento de Bosawás.', 'Macizo rocoso con bosque nuboso, nacientes de agua y cascadas, parte de la zona de amortiguamiento de Bosawás.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'jinotega::reserva natural macizo de penas blancas', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-fincas-agroecologicas-de-san-rafael-del-norte', 'fincas-agroecologicas-de-san-rafael-del-norte', 'Fincas Agroecológicas de San Rafael del Norte', 'agroturismo', null, 'Ruta del Café', 'fa-mug-hot', 'jinotega', null, null, 'Fincas familiares de café y cultivos diversos en San Rafael del Norte que reciben visitantes con turismo rural.', 'Fincas familiares de café y cultivos diversos en San Rafael del Norte que reciben visitantes con turismo rural.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'jinotega::fincas agroecologicas de san rafael del norte', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-reserva-natural-cerro-datanli-el-diablo', 'reserva-natural-cerro-datanli-el-diablo', 'Reserva Natural Cerro Datanlí–El Diablo', 'reserva', null, 'Bosque nuboso, aviturismo, café y comunidades', 'fa-tree', 'jinotega', 'jinotega__jinotega', null, 'Reserva de bosque nuboso entre Jinotega y Matagalpa, con fincas de café, senderos y fuentes de agua.', 'Reserva de bosque nuboso entre Jinotega y Matagalpa, con fincas de café, senderos y fuentes de agua.', 13.11941, -85.87948, 'reference', false, null, 'verified', '2026-10-05'::timestamptz, 'Mapa Nacional de Turismo (catálogo de naturaleza 2026)', null, 'other', '{"activities":"Senderismo, aves, cascadas, paisaje y camping controlado.","facts":"Área protegida de nebliselva a unos 15 km de Jinotega, con elevaciones de alrededor de 1,650 m y alta biodiversidad.","note":"Incluye el registro \"Cerro Datanlí - El Diablo\" (mismo punto, cumbre del Cerro El Diablo)."}'::jsonb, true, 'territories-data.js', 'jinotega::reserva natural cerro datanli el diablo', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-salto-la-mocuana', 'salto-la-mocuana', 'Salto La Mocuana', 'cascada', null, 'Cascada y naturaleza en La Fundadora', 'fa-water', 'jinotega', null, null, 'Cascada cercana a la comunidad de La Fundadora, en Jinotega, conocida por la leyenda de La Mocuana.', 'Cascada cercana a la comunidad de La Fundadora, en Jinotega, conocida por la leyenda de La Mocuana.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'jinotega::salto la mocuana', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-cascadas-arco-iris-la-pavona-y-la-sonora', 'cascadas-arco-iris-la-pavona-y-la-sonora', 'Cascadas Arco Iris, La Pavona y La Sonora', 'cascada', null, 'Agua y senderismo en Peñas Blancas', 'fa-cloud-rain', 'jinotega', null, null, 'Conjunto de caídas de agua en Peñas Blancas, unidas por senderos de montaña.', 'Conjunto de caídas de agua en Peñas Blancas, unidas por senderos de montaña.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'jinotega::cascadas arco iris la pavona y la sonora', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-cerro-kilambe-y-aguas-termales-de-el-cano', 'cerro-kilambe-y-aguas-termales-de-el-cano', 'Cerro Kilambé y aguas termales de El Caño', 'reserva', null, 'Montaña, termalismo y vida rural en El Cuá', 'fa-mountain-sun', 'jinotega', null, 'El Cuá / San José de Bocay / Wiwilí', 'Montaña de las más altas del norte del país y fuentes termales en la zona rural de El Cuá.', 'Montaña de las más altas del norte del país y fuentes termales en la zona rural de El Cuá.', 13.58178, -85.69313, 'reference', false, null, 'verified', '2026-10-05'::timestamptz, 'Mapa Nacional de Turismo (catálogo de naturaleza 2026)', null, 'other', '{"activities":"Senderismo especializado, biodiversidad, aves y paisaje.","facts":"Reserva montañosa de origen volcánico con bosque de nebliselva y una importante red de nacientes y ríos.","note":"Incluye el registro \"Cerro Kilambé\" (mismo punto, cumbre)."}'::jsonb, true, 'territories-data.js', 'jinotega::cerro kilambe y aguas termales de el cano', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-salto-de-kayaska', 'salto-de-kayaska', 'Salto de Kayaska', 'cascada', null, 'Naturaleza y acceso hacia Bosawás desde Bocay', 'fa-water', 'jinotega', null, null, 'Cascada en la zona de Bocay, puerta de acceso a la Reserva de Biosfera Bosawás.', 'Cascada en la zona de Bocay, puerta de acceso a la Reserva de Biosfera Bosawás.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'jinotega::salto de kayaska', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-cascada-la-bujona', 'cascada-la-bujona', 'Cascada La Bujona', 'cascada', null, 'Cascada · Senderismo', 'fa-droplet', 'jinotega', 'jinotega__jinotega', null, 'Caída de agua registrada en OpenStreetMap en el departamento de Jinotega, próxima al sector de Paso El Limón.', 'Caída de agua registrada en OpenStreetMap en el departamento de Jinotega, próxima al sector de Paso El Limón.', 13.08037, -85.87418, 'exact', true, null, 'verified', '2026-10-05'::timestamptz, 'OpenStreetMap', 'https://mapcarta.com/es/N6907277586', 'other', '{"activities":"Senderismo, fotografía y naturaleza.","modality":"Cascadas","facts":"Caída de agua registrada en OpenStreetMap en el departamento de Jinotega, próxima al sector de Paso El Limón."}'::jsonb, true, 'territories-data.js', 'jinotega::cascada la bujona', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-parque-nacional-volcan-masaya', 'parque-nacional-volcan-masaya', 'Parque Nacional Volcán Masaya', 'parque', null, 'Vulcanología, miradores, senderos autorizados y educación ambiental', 'fa-fire', 'masaya', null, null, 'Volcán activo con miradores al cráter Santiago, del que salen gases y donde anidan chocoyos; las visitas nocturnas muestran su resplandor.', 'Volcán activo con miradores al cráter Santiago, del que salen gases y donde anidan chocoyos; las visitas nocturnas muestran su resplandor.', 11.983333, -86.15, 'centroid', false, null, 'verified', '2026-10-05'::timestamptz, 'MARENA', 'https://www.marena.gob.ni/2026/07/17/mas-visitas-en-volcan-masaya/', 'other', '{"facts":"Área administrada por MARENA (aprox. km 23 carretera Managua–Masaya). La Plaza Oviedo reabrió en diciembre de 2025 y permite apreciar la incandescencia del volcán Santiago bajo medidas de seguridad.","contact_note":"Información institucional: MARENA.","price_note":{"text":"Horario general reportado por MARENA (17/07/2026): lunes a domingo, 8:30 a. m. a 7:00 p. m.; puede cambiar por actividad volcánica. Tarifa: consultar publicación oficial vigente.","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, true, 'territories-data.js', 'masaya::parque nacional volcan masaya', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-laguna-de-masaya', 'laguna-de-masaya', 'Laguna de Masaya', 'volcan', null, 'Naturaleza, paisaje volcánico y fotografía', 'fa-water', 'masaya', null, null, 'Laguna de origen volcánico al pie de la ciudad de Masaya, con miradores desde el malecón.', 'Laguna de origen volcánico al pie de la ciudad de Masaya, con miradores desde el malecón.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'masaya::laguna de masaya', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-monimbo', 'monimbo', 'Monimbó', 'sitio_historico', null, 'Identidad indígena, talleres, gastronomía y memoria comunitaria', 'fa-hands-holding', 'masaya', null, null, 'Barrio indígena de Masaya, corazón de la artesanía y del folclore, con talleres de cuero, madera y máscaras.', 'Barrio indígena de Masaya, corazón de la artesanía y del folclore, con talleres de cuero, madera y máscaras.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'masaya::monimbo', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-mercado-de-artesanias-de-masaya', 'mercado-de-artesanias-de-masaya', 'Mercado de Artesanías de Masaya', 'mercado', null, 'Artesanía, cultura, gastronomía y economía local', 'fa-store', 'masaya', null, null, 'Edificio histórico con hamacas, cerámica, madera, cuero y textiles de todo el país.', 'Edificio histórico con hamacas, cerámica, madera, cuero y textiles de todo el país.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'masaya::mercado de artesanias de masaya', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-mirador-de-catarina', 'mirador-de-catarina', 'Mirador de Catarina', 'mirador', null, 'Paisaje, viveros, música y gastronomía', 'fa-eye', 'masaya', 'masaya__catarina', null, 'Balcón natural sobre la Laguna de Apoyo, con viveros, comida y artesanía.', 'Balcón natural sobre la Laguna de Apoyo, con viveros, comida y artesanía.', 11.91318, -86.06903, 'exact', true, null, 'verified', '2026-10-05'::timestamptz, 'Visit Nicaragua (catálogo de naturaleza 2026)', null, 'other', '{"activities":"Paisaje, fotografía, artesanía, gastronomía, senderos y actividades de aventura.","facts":"Uno de los miradores más visitados del país, con vistas hacia la Laguna de Apoyo, el Lago Cocibolca, Granada y el Volcán Mombacho."}'::jsonb, true, 'territories-data.js', 'masaya::mirador de catarina', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-san-juan-de-oriente', 'san-juan-de-oriente', 'San Juan de Oriente', 'centro_cultural', null, 'Cerámica artesanal y experiencias directas con productores', 'fa-hands', 'masaya', null, null, 'Pueblo alfarero de los Pueblos Blancos donde la cerámica se tornea y pinta a mano con motivos precolombinos.', 'Pueblo alfarero de los Pueblos Blancos donde la cerámica se tornea y pinta a mano con motivos precolombinos.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'masaya::san juan de oriente', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-niquinohomo-y-casa-museo-de-sandino', 'niquinohomo-y-casa-museo-de-sandino', 'Niquinohomo y Casa Museo de Sandino', 'museo', null, 'Memoria histórica y patrimonio cultural', 'fa-landmark', 'masaya', null, null, 'Pueblo natal de Augusto C. Sandino; la casa donde nació funciona como museo y biblioteca.', 'Pueblo natal de Augusto C.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'masaya::niquinohomo y casa museo de sandino', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-reserva-natural-laguna-de-tisma', 'reserva-natural-laguna-de-tisma', 'Reserva Natural Laguna de Tisma', 'laguna', null, 'Humedal Ramsar, biodiversidad y observación responsable', 'fa-binoculars', 'masaya', null, null, 'Humedal de importancia internacional (sitio Ramsar) con gran diversidad de aves acuáticas.', 'Humedal de importancia internacional (sitio Ramsar) con gran diversidad de aves acuáticas.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'masaya::reserva natural laguna de tisma', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-petroglifos-de-el-cailagua', 'petroglifos-de-el-cailagua', 'Petroglifos de El Cailagua', 'sitio_historico', null, 'Arqueología, símbolos ancestrales e interpretación comunitaria', 'fa-monument', 'masaya', null, null, 'Grabados precolombinos en las paredes de una cañada cerca de Masaya, interpretados por guías comunitarios.', 'Grabados precolombinos en las paredes de una cañada cerca de Masaya, interpretados por guías comunitarios.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'masaya::petroglifos de el cailagua', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-taller-escuela-valentin-lopez-y-palo-solo', 'taller-escuela-valentin-lopez-y-palo-solo', 'Taller Escuela Valentín López y Palo Solo', 'centro_cultural', null, 'Artesanía, cultura y experiencias comunitarias', 'fa-hands', 'masaya', null, null, 'Espacios de artesanía y tradición en Masaya donde se aprende de los oficios locales y se compra directo.', 'Espacios de artesanía y tradición en Masaya donde se aprende de los oficios locales y se compra directo.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'masaya::taller escuela valentin lopez y palo solo', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-posada-ecologica-la-abuela-laguna-de-apoyo', 'posada-ecologica-la-abuela-laguna-de-apoyo', 'Posada Ecológica La Abuela – Laguna de Apoyo', 'laguna', null, 'Hotel-restaurante y pase de día en la laguna', 'fa-water', 'masaya', null, null, 'Hotel-restaurante a orillas de la Laguna de Apoyo con cabañas y pase de día para disfrutar del agua y el bosque.', 'Hotel-restaurante a orillas de la Laguna de Apoyo con cabañas y pase de día para disfrutar del agua y el bosque.', null, null, 'missing', false, null, 'verified', '2026-10-05'::timestamptz, 'Sitio oficial', 'https://www.posadaecologicalaabuela.com.ni/Page/Contacto', 'other', '{"facts":"Hotel-restaurante real en el entorno de la Laguna de Apoyo; acceso principal en el km 37.9, 2 km al norte desde el triángulo.","price_note":{"text":"Sitio oficial (2026): pase de día adulto US$17.25 (US$12.25 consumibles); cabaña para 2 personas US$81.90 con impuestos. Revalidar antes de comprar.","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, true, 'territories-data.js', 'masaya::posada ecologica la abuela laguna de apoyo', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-volcan-masaya-caldera-santiago', 'volcan-masaya-caldera-santiago', 'Volcán Masaya (caldera Santiago)', 'volcan', null, 'Volcán o cerro · Geoturismo', 'fa-volcano', 'masaya', null, 'Nindirí / Masaya', 'Caldera volcánica activa dentro del Parque Nacional Volcán Masaya; INETER reporta actividad volcánica y monitoreo permanente.', 'Caldera volcánica activa dentro del Parque Nacional Volcán Masaya; INETER reporta actividad volcánica y monitoreo permanente.', 11.9822, -86.1621, 'reference', false, null, 'verified', '2026-10-05'::timestamptz, 'INETER / Visit Nicaragua (catálogo de naturaleza 2026)', null, 'other', '{"activities":"Geoturismo, observación volcánica bajo condiciones oficiales y fotografía.","facts":"Caldera volcánica activa dentro del Parque Nacional Volcán Masaya; INETER reporta actividad volcánica y monitoreo permanente."}'::jsonb, true, 'territories-data.js', 'masaya::volcan masaya caldera santiago', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-centro-historico-y-calle-la-calzada', 'centro-historico-y-calle-la-calzada', 'Centro Histórico y Calle La Calzada', 'sitio_historico', null, 'Arquitectura, plazas, iglesias, museos y gastronomía', 'fa-building-columns', 'granada', null, null, 'Recorrido a pie por el centro colonial de Granada y su calle peatonal La Calzada, que baja hasta el lago.', 'Recorrido a pie por el centro colonial de Granada y su calle peatonal La Calzada, que baja hasta el lago.', null, null, 'missing', false, null, 'verified', '2026-10-05'::timestamptz, 'Mapa Nacional de Turismo', 'https://www.mapanicaragua.com/local/calle-la-calzada/', 'other', '{"facts":"Eje emblemático del centro histórico con edificios coloniales que comunica el centro con el Lago Cocibolca. El Mapa Nacional de Turismo la identifica como uno de los principales puntos de vida nocturna de Granada.","contact_note":"No existe un teléfono único de la calle ni una asociación que represente toda la oferta.","price_note":{"text":"Cada restaurante, bar y comercio maneja su propia ficha y precios.","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, true, 'territories-data.js', 'granada::centro historico y calle la calzada', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-catedral-de-granada-y-parque-colon', 'catedral-de-granada-y-parque-colon', 'Catedral de Granada y Parque Colón', 'parque', null, 'Patrimonio, vida urbana, religión y fotografía', 'fa-church', 'granada', null, null, 'La catedral amarilla de Granada frente al Parque Colón, el punto de partida para recorrer la ciudad colonial.', 'La catedral amarilla de Granada frente al Parque Colón, el punto de partida para recorrer la ciudad colonial.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'granada::catedral de granada y parque colon', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-iglesia-y-torre-de-la-merced', 'iglesia-y-torre-de-la-merced', 'Iglesia y Torre de La Merced', 'sitio_historico', null, 'Arquitectura, historia y vistas urbanas', 'fa-church', 'granada', null, null, 'Iglesia colonial de Granada cuyo campanario ofrece una de las mejores vistas de los techos de la ciudad y del lago.', 'Iglesia colonial de Granada cuyo campanario ofrece una de las mejores vistas de los techos de la ciudad y del lago.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'granada::iglesia y torre de la merced', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-convento-e-iglesia-san-francisco', 'convento-e-iglesia-san-francisco', 'Convento e Iglesia San Francisco', 'sitio_historico', null, 'Historia, arquitectura y espacios museísticos', 'fa-landmark', 'granada', null, null, 'Convento-museo que guarda estatuas precolombinas de la isla Zapatera, hoy parque nacional.', 'Convento-museo que guarda estatuas precolombinas de la isla Zapatera, hoy parque nacional.', null, null, 'missing', false, null, 'verified', '2026-10-05'::timestamptz, 'Mapa Nacional de Turismo', 'https://www.mapanicaragua.com/municipio-de-granada/', 'other', '{"facts":"Conjunto histórico fundado en 1529 como Inmaculada Concepción. Hoy funciona como Centro Cultural Museo Convento San Francisco, con arte precolombino, pintura primitivista, arte religioso y mobiliario tradicional.","price_note":{"text":"Consultar la tarifa vigente en el museo.","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, true, 'territories-data.js', 'granada::convento e iglesia san francisco', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-casa-de-los-leones', 'casa-de-los-leones', 'Casa de los Leones', 'sitio_historico', null, 'Patrimonio cultural y ciudades históricas', 'fa-house', 'granada', null, null, 'Casona colonial frente al Parque Colón de Granada, hoy centro cultural con exposiciones y actividades.', 'Casona colonial frente al Parque Colón de Granada, hoy centro cultural con exposiciones y actividades.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'granada::casa de los leones', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-antigua-estacion-del-ferrocarril', 'antigua-estacion-del-ferrocarril', 'Antigua Estación del Ferrocarril', 'sitio_historico', null, 'Memoria ferroviaria y patrimonio', 'fa-train', 'granada', null, null, 'Edificio histórico de la estación de trenes de Granada, testimonio de la época del ferrocarril en el Pacífico.', 'Edificio histórico de la estación de trenes de Granada, testimonio de la época del ferrocarril en el Pacífico.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'granada::antigua estacion del ferrocarril', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-isletas-de-granada', 'isletas-de-granada', 'Isletas de Granada', 'isla', null, 'Lancha, kayak, fauna, paisaje y fotografía', 'fa-ship', 'granada', 'granada__granada', null, 'Cientos de pequeñas islas formadas por una antigua erupción del Mombacho, con aves y comunidades; se recorren en lancha.', 'Cientos de pequeñas islas formadas por una antigua erupción del Mombacho, con aves y comunidades; se recorren en lancha.', 11.89911, -85.88519, 'approximate', false, null, 'verified', '2026-10-05'::timestamptz, 'Visit Nicaragua / GeoNames', 'https://www.visitanicaragua.com/atractivos/islas/', 'other', '{"activities":"Paseo en lancha, kayak, observación de aves y fotografía.","facts":"Archipiélago lacustre de numerosos islotes al sureste de Granada, en el Lago Cocibolca."}'::jsonb, true, 'territories-data.js', 'granada::isletas de granada', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-lago-cocibolca', 'lago-cocibolca', 'Lago Cocibolca', 'laguna', null, 'Agua, navegación, biodiversidad e historia', 'fa-water', 'granada', 'granada__granada', null, 'El lago más grande de Centroamérica, frente a Granada, con islas, playas lacustres y paseos en lancha.', 'El lago más grande de Centroamérica, frente a Granada, con islas, playas lacustres y paseos en lancha.', 11.6873, -85.47863, 'centroid', false, null, 'verified', '2026-10-05'::timestamptz, 'OpenStreetMap / GeoNames (catálogo de naturaleza 2026)', null, 'other', '{"activities":"Navegación, islas, pesca, kayak, fotografía y turismo comunitario.","facts":"El mayor lago de Centroamérica, con islas, archipiélagos, comunidades pesqueras y gran diversidad de paisajes y actividades."}'::jsonb, true, 'territories-data.js', 'granada::lago cocibolca', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-aguas-agrias-la-nanda', 'aguas-agrias-la-nanda', 'Aguas Agrias–La Nanda', 'turismo_rural', null, 'Turismo rural comunitario, senderos y cocina local', 'fa-people-group', 'granada', null, null, 'Experiencia de turismo rural comunitario en Nandaime, con senderos, ríos y cocina local.', 'Experiencia de turismo rural comunitario en Nandaime, con senderos, ríos y cocina local.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'granada::aguas agrias la nanda', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-reserva-natural-laguna-de-apoyo', 'reserva-natural-laguna-de-apoyo', 'Reserva Natural Laguna de Apoyo', 'laguna', null, 'Kayak, baño, senderismo, fotografía y aves', 'fa-person-swimming', 'granada', null, null, 'Laguna de cráter de agua templada entre Granada y Masaya, ideal para nadar, remar en kayak y observar aves.', 'Laguna de cráter de agua templada entre Granada y Masaya, ideal para nadar, remar en kayak y observar aves.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'granada::reserva natural laguna de apoyo', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-finca-el-rayo', 'finca-el-rayo', 'Finca El Rayo', 'agroturismo', null, 'Turismo rural · Caminatas por senderos naturales', 'fa-house-chimney', 'granada', null, null, 'Finca rural entre paisajes volcánicos, flora y fauna, con sendero de petroglifos que conecta con el pasado precolombino.', 'Finca rural entre paisajes volcánicos, flora y fauna, con sendero de petroglifos que conecta con el pasado precolombino.', null, null, 'missing', false, 'De la entrada El Astillero, El Diamante 4 km al este y 3.5 km al sur.', 'verified', '2026-10-05'::timestamptz, 'INTUR · Catálogo de Iniciativas de Turismo Rural y Comunitario (2026)', null, 'other', '{"activities":"Caminatas por senderos naturales, observación de aves y exploración de flora y fauna.","services":"Alimentos y bebidas, camping, kayak, natación y sendero de petroglifos.","hours":"Viernes a domingo, 9:00 a. m.–5:00 p. m.","modality":"Turismo rural","facts":"Finca rural entre paisajes volcánicos, flora y fauna, con sendero de petroglifos que conecta con el pasado precolombino.","map":"https://www.google.com/maps/d/u/0/edit?mid=1W6bI4kom2Cq-MvarHCYx08YyCXR2s7Q&usp=sharing","contact_note":"Contacto publicado por INTUR en el catálogo 2026; confirmar antes de viajar."}'::jsonb, true, 'territories-data.js', 'granada::finca el rayo', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-eco-finca-el-buen-pastor', 'eco-finca-el-buen-pastor', 'Eco Finca El Buen Pastor', 'agroturismo', null, 'Agroturismo · Caminatas', 'fa-seedling', 'granada', null, null, 'Casa de campo en Nandaime con cabañas, piscina y área de meditación, enfocada en la sostenibilidad.', 'Casa de campo en Nandaime con cabañas, piscina y área de meditación, enfocada en la sostenibilidad.', null, null, 'missing', false, 'Km 60.5 carretera Panamericana Sur, Nandaime.', 'verified', '2026-10-05'::timestamptz, 'INTUR · Catálogo de Iniciativas de Turismo Rural y Comunitario (2026)', null, 'other', '{"activities":"Caminatas, giras ecológicas, observación de aves y exploración de flora y fauna.","services":"Cabañas, alimentos y bebidas, juegos para niños, piscina, meditación y camping.","hours":"Viernes a domingo, 8:00 a. m.–5:00 p. m. (con reservación).","modality":"Agroturismo","facts":"Casa de campo en Nandaime con cabañas, piscina y área de meditación, enfocada en la sostenibilidad.","map":"https://www.google.com/maps/d/u/0/edit?mid=1YLbA-KdYFfgFE1x20ZCZsy9tL0hI9r4&usp=sharing","contact_note":"Contacto publicado por INTUR en el catálogo 2026; confirmar antes de viajar."}'::jsonb, true, 'territories-data.js', 'granada::eco finca el buen pastor', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-finca-maria-auxiliadora', 'finca-maria-auxiliadora', 'Finca María Auxiliadora', 'agroturismo', null, 'Turismo de naturaleza · Senderos', 'fa-tree', 'granada', null, null, 'Refugio rural entre Granada y Diriomo con frutales, maderas, tres senderos y siembra participativa.', 'Refugio rural entre Granada y Diriomo con frutales, maderas, tres senderos y siembra participativa.', null, null, 'missing', false, 'Carretera Granada–Diriomo km 53.5 (IMMSA), 800 m al oeste.', 'verified', '2026-10-05'::timestamptz, 'INTUR · Catálogo de Iniciativas de Turismo Rural y Comunitario (2026)', null, 'other', '{"activities":"Senderos, aves, siembra y cosecha de frutales y forestales, flora y fauna.","services":"Alimentos, bebidas, piscinas, camping, tres rutas de senderismo y aves.","hours":"Lunes a domingo, 6:00 a. m.–5:00 p. m. (con reservación).","modality":"Turismo de naturaleza","facts":"Refugio rural entre Granada y Diriomo con frutales, maderas, tres senderos y siembra participativa.","map":"https://www.google.com/maps/d/u/0/edit?mid=1_aF-9soYpiBy3mofkbdmA_qPaFtO22s&usp=sharing","contact_note":"Contacto publicado por INTUR en el catálogo 2026; confirmar antes de viajar."}'::jsonb, true, 'territories-data.js', 'granada::finca maria auxiliadora', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-rio-tipitapa', 'rio-tipitapa', 'Río Tipitapa', 'rio', null, 'Río · Paisaje', 'fa-water', 'granada', null, 'Tipitapa', 'Curso de agua natural que conecta el Lago Xolotlán con el Lago Cocibolca en condiciones hidrológicas favorables.', 'Curso de agua natural que conecta el Lago Xolotlán con el Lago Cocibolca en condiciones hidrológicas favorables.', 12.08333, -85.88333, 'approximate', false, null, 'verified', '2026-10-05'::timestamptz, 'GeoNames / Wikidata', 'https://mapcarta.com/es/19577744', 'other', '{"activities":"Paisaje, educación ambiental y observación de humedales.","modality":"Ríos","facts":"Curso de agua natural que conecta el Lago Xolotlán con el Lago Cocibolca en condiciones hidrológicas favorables."}'::jsonb, true, 'territories-data.js', 'granada::rio tipitapa', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-isla-zapatera', 'isla-zapatera', 'Isla Zapatera', 'isla', null, 'Isla · Arqueología', 'fa-mountain-sun', 'granada', 'granada__granada', null, 'Isla volcánica del Lago Cocibolca, núcleo del Parque Nacional Archipiélago Zapatera y relevante por su patrimonio arqueológico.', 'Isla volcánica del Lago Cocibolca, núcleo del Parque Nacional Archipiélago Zapatera y relevante por su patrimonio arqueológico.', 11.739, -85.835, 'approximate', false, null, 'verified', '2026-10-05'::timestamptz, 'MARENA / GeoNames', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/11-Plan-de-Manejo-Parque-Nacional-Archipielago-Zapatera.pdf', 'other', '{"activities":"Arqueología, senderismo, navegación y naturaleza.","modality":"Islas","facts":"Isla volcánica del Lago Cocibolca, núcleo del Parque Nacional Archipiélago Zapatera y relevante por su patrimonio arqueológico."}'::jsonb, true, 'territories-data.js', 'granada::isla zapatera', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-reserva-silvestre-selva-negra', 'reserva-silvestre-selva-negra', 'Reserva Silvestre Selva Negra', 'reserva', null, 'Bosque Nuboso & Aves', 'fa-feather', 'matagalpa', null, null, 'Bosque nuboso, senderos y finca cafetalera en las montañas de Matagalpa.', 'Bosque nuboso, senderos y finca cafetalera en las montañas de Matagalpa.', null, null, 'missing', false, null, 'verified', '2026-10-05'::timestamptz, 'Sitio oficial', 'https://selvanegramatagalpa.wixsite.com/snpatrio2024/acerca-de', 'other', '{"facts":"Selva Negra Ecolodge, en el km 140 de la carretera Matagalpa–Jinotega: ecolodge y hacienda cafetalera real. Su sitio oficial indica operación desde 1975 y al menos 600 hectáreas entre área protegida y productiva.","price_note":{"text":"Consultar la tarifa vigente directamente con el establecimiento.","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, true, 'territories-data.js', 'matagalpa::reserva silvestre selva negra', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-comunidad-indigena-de-el-chile', 'comunidad-indigena-de-el-chile', 'Comunidad Indígena de El Chile', 'turismo_comunitario', null, 'Tejidos Tradicionales', 'fa-hands-holding', 'matagalpa', null, null, 'Comunidad indígena de Matagalpa reconocida por sus tejidos en telar; se visitan los talleres y se compra a las tejedoras.', 'Comunidad indígena de Matagalpa reconocida por sus tejidos en telar; se visitan los talleres y se compra a las tejedoras.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'matagalpa::comunidad indigena de el chile', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-cascada-santa-emilia', 'cascada-santa-emilia', 'Cascada Santa Emilia', 'cascada', null, 'Caída de Agua Mística', 'fa-water', 'matagalpa', null, null, 'Cascada entre bosque y cafetales en las montañas de Matagalpa, accesible con una caminata corta.', 'Cascada entre bosque y cafetales en las montañas de Matagalpa, accesible con una caminata corta.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'matagalpa::cascada santa emilia', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-cerro-apante-reserva-natural', 'cerro-apante-reserva-natural', 'Cerro Apante (Reserva Natural)', 'reserva', null, 'Senderismo de Altura', 'fa-mountain', 'matagalpa', null, null, 'Reserva que rodea la ciudad de Matagalpa, con senderos de bosque y miradores sobre el valle.', 'Reserva que rodea la ciudad de Matagalpa, con senderos de bosque y miradores sobre el valle.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'matagalpa::cerro apante reserva natural', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-museo-nacional-del-cafe', 'museo-nacional-del-cafe', 'Museo Nacional del Café', 'museo', null, 'Cultura Cafetalera', 'fa-mug-hot', 'matagalpa', null, null, 'Historia del café en Nicaragua contada desde Matagalpa, la ciudad que lo hizo identidad.', 'Historia del café en Nicaragua contada desde Matagalpa, la ciudad que lo hizo identidad.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'matagalpa::museo nacional del cafe', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
commit;
