-- BAQUEANO · Importación territories-data.js → Supabase · parte 03 de 07
-- Generado desde supabase/imports/20261005_territories_import.sql. Ejecutar las partes EN ORDEN en el SQL Editor.
-- Idempotente: si una parte se ejecuta dos veces, no duplica (ON CONFLICT).
begin;
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-museo-casa-natal-ruben-dario', 'museo-casa-natal-ruben-dario', 'Museo Casa Natal Rubén Darío', 'museo', null, 'Poesía, historia y patrimonio en Ciudad Darío', 'fa-book-open', 'matagalpa', null, null, 'Museo en la casa de Ciudad Darío (Matagalpa) donde nació Rubén Darío, el Príncipe de las Letras Castellanas.', 'Museo en la casa de Ciudad Darío (Matagalpa) donde nació Rubén Darío, el Príncipe de las Letras Castellanas.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'matagalpa::museo casa natal ruben dario', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-villa-chaguitillo', 'villa-chaguitillo', 'Villa Chagüitillo', 'sitio_historico', null, 'Arte rupestre, arqueología e interpretación histórica', 'fa-monument', 'matagalpa', null, null, 'Comunidad de Sébaco con petroglifos precolombinos a orillas de quebradas, interpretados por guías locales.', 'Comunidad de Sébaco con petroglifos precolombinos a orillas de quebradas, interpretados por guías locales.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'matagalpa::villa chaguitillo', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-cascada-blanca-y-cascada-la-luna', 'cascada-blanca-y-cascada-la-luna', 'Cascada Blanca y Cascada La Luna', 'cascada', null, 'Naturaleza, aventura y paisajes de agua', 'fa-water', 'matagalpa', null, null, 'Caídas de agua en Matagalpa con pozas y senderos, buenas para un día de naturaleza.', 'Caídas de agua en Matagalpa con pozas y senderos, buenas para un día de naturaleza.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'matagalpa::cascada blanca y cascada la luna', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-macizo-de-penas-blancas', 'macizo-de-penas-blancas', 'Macizo de Peñas Blancas', 'cascada', null, 'Café, senderismo, cascadas y conservación', 'fa-mountain-sun', 'matagalpa', null, null, 'Macizo de bosque nuboso compartido con Jinotega, con café, cascadas y conservación del agua.', 'Macizo de bosque nuboso compartido con Jinotega, con café, cascadas y conservación del agua.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'matagalpa::macizo de penas blancas', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-san-ramon', 'san-ramon', 'San Ramón', 'agroturismo', null, 'Turismo rural comunitario, café, cacao y fincas', 'fa-people-group', 'matagalpa', null, null, 'Municipio cafetalero cercano a Matagalpa con turismo rural comunitario en fincas de café y cacao.', 'Municipio cafetalero cercano a Matagalpa con turismo rural comunitario en fincas de café y cacao.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'matagalpa::san ramon', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-catedral-san-pedro', 'catedral-san-pedro', 'Catedral San Pedro', 'sitio_historico', null, 'Arquitectura, religión y patrimonio urbano', 'fa-church', 'matagalpa', null, null, 'Catedral de la ciudad de Matagalpa, de arquitectura colonial tardía y centro de la vida urbana.', 'Catedral de la ciudad de Matagalpa, de arquitectura colonial tardía y centro de la vida urbana.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'matagalpa::catedral san pedro', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-albergue-tierra-alta-ecolodge', 'albergue-tierra-alta-ecolodge', 'Albergue Tierra Alta Ecolodge', 'turismo_rural', null, 'Turismo rural · Senderos con frutos exóticos', 'fa-house-chimney', 'matagalpa', null, null, 'Ecolodge en San Ramón con alimentos orgánicos de la finca, plantas medicinales y tours nocturnos de fauna.', 'Ecolodge en San Ramón con alimentos orgánicos de la finca, plantas medicinales y tours nocturnos de fauna.', null, null, 'missing', false, 'Entrada a comunidad El Trentino, 1 km al norte de la Escuela San Ramón García, 400 m al norte, San Ramón.', 'verified', '2026-10-05'::timestamptz, 'INTUR · Catálogo de Iniciativas de Turismo Rural y Comunitario (2026)', null, 'other', '{"activities":"Senderos con frutos exóticos y cultivos orgánicos, tours nocturnos (murciélagos, búhos, perezosos) y cabalgatas.","services":"Alojamiento y alimentación.","hours":"Lunes a domingo, 8:00 a. m.–5:00 p. m.","modality":"Turismo rural","facts":"Ecolodge en San Ramón con alimentos orgánicos de la finca, plantas medicinales y tours nocturnos de fauna.","map":"https://www.google.com/maps/d/u/0/edit?mid=1xeQGLfuhxkFpkJWczFHe1DIUgFomB3o&usp=sharing","contact_note":"Contacto publicado por INTUR en el catálogo 2026; confirmar antes de viajar."}'::jsonb, true, 'territories-data.js', 'matagalpa::albergue tierra alta ecolodge', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-rio-tuma', 'rio-tuma', 'Río Tuma', 'rio', null, 'Río · Baño en zonas habilitadas', 'fa-water', 'matagalpa', 'matagalpa__el_tuma_la_dalia', null, 'Curso de agua importante de la región norte-central; el punto marca un sitio accesible cercano a El Tuma-La Dalia.', 'Curso de agua importante de la región norte-central; el punto marca un sitio accesible cercano a El Tuma-La Dalia.', 13.1025, -85.74323, 'exact', true, null, 'verified', '2026-10-05'::timestamptz, 'OpenStreetMap', 'https://mapcarta.com/es/N5135651522', 'other', '{"activities":"Baño en zonas habilitadas, fotografía y paisaje rural.","modality":"Ríos","facts":"Curso de agua importante de la región norte-central; el punto marca un sitio accesible cercano a El Tuma-La Dalia."}'::jsonb, true, 'territories-data.js', 'matagalpa::rio tuma', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-cascada-la-luna-el-tuma-la-dalia', 'cascada-la-luna-el-tuma-la-dalia', 'Cascada La Luna (El Tuma-La Dalia)', 'cascada', null, 'Cascada · Senderismo', 'fa-droplet', 'matagalpa', 'matagalpa__el_tuma_la_dalia', null, 'Cascada cercana a El Tuma-La Dalia, rodeada de vegetación y con actividades de aventura en su entorno.', 'Cascada cercana a El Tuma-La Dalia, rodeada de vegetación y con actividades de aventura en su entorno.', 13.11685, -85.75101, 'exact', true, null, 'verified', '2026-10-05'::timestamptz, 'OpenStreetMap / Mapa Nacional de Turismo', 'https://mapcarta.com/es/N5607799821', 'other', '{"activities":"Senderismo, fotografía y turismo de naturaleza.","modality":"Cascadas","facts":"Cascada cercana a El Tuma-La Dalia, rodeada de vegetación y con actividades de aventura en su entorno."}'::jsonb, true, 'territories-data.js', 'matagalpa::cascada la luna el tuma la dalia', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-cascada-blanca-rio-yasica', 'cascada-blanca-rio-yasica', 'Cascada Blanca (Río Yasica)', 'cascada', null, 'Cascada · Baño en zonas autorizadas', 'fa-droplet', 'matagalpa', 'matagalpa__san_ramon', null, 'Cascada del Río Yasica conocida como Cascada Blanca, en el corredor hacia El Tuma-La Dalia.', 'Cascada del Río Yasica conocida como Cascada Blanca, en el corredor hacia El Tuma-La Dalia.', 12.99124, -85.82931, 'exact', true, null, 'verified', '2026-10-05'::timestamptz, 'OpenStreetMap / UCC', 'https://mapcarta.com/es/N4904807522', 'other', '{"activities":"Baño en zonas autorizadas, senderismo y fotografía.","modality":"Cascadas","facts":"Cascada del Río Yasica conocida como Cascada Blanca, en el corredor hacia El Tuma-La Dalia."}'::jsonb, true, 'territories-data.js', 'matagalpa::cascada blanca rio yasica', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-reserva-natural-cerro-musun', 'reserva-natural-cerro-musun', 'Reserva Natural Cerro Musún', 'reserva', null, 'Reserva natural · Senderismo', 'fa-tree', 'matagalpa', null, 'Río Blanco / Matiguás / Paiwas', 'Área protegida de bosque húmedo tropical y bosque nuboso con cascadas y alta riqueza de flora y fauna.', 'Área protegida de bosque húmedo tropical y bosque nuboso con cascadas y alta riqueza de flora y fauna.', 12.98536, -85.24221, 'reference', false, null, 'verified', '2026-10-05'::timestamptz, 'Mapa Nacional de Turismo (catálogo de naturaleza 2026)', null, 'other', '{"activities":"Senderismo, cascadas, fotografía, camping y observación de fauna.","facts":"Área protegida de bosque húmedo tropical y bosque nuboso con cascadas y alta riqueza de flora y fauna.","note":"Incluye el registro \"Cerro Musún\" (mismo punto, cumbre)."}'::jsonb, true, 'territories-data.js', 'matagalpa::reserva natural cerro musun', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-reserva-natural-tisey-la-estanzuela', 'reserva-natural-tisey-la-estanzuela', 'Reserva Natural Tisey-La Estanzuela', 'reserva', null, 'Cascada & Esculturas', 'fa-water', 'esteli', null, 'Estelí / San Nicolás / El Sauce', 'Cascada, pinares, miradores y las esculturas talladas en piedra en la montaña de Estelí.', 'Cascada, pinares, miradores y las esculturas talladas en piedra en la montaña de Estelí.', 13.0222, -86.3884, 'reference', false, null, 'verified', '2026-10-05'::timestamptz, 'Mapa Nacional de Turismo / Wikidata (catálogo de naturaleza 2026)', null, 'other', '{"activities":"Senderismo, cascadas, miradores, arte en piedra y turismo rural.","facts":"Área protegida de pinares, robledales y montañas que incluye el Salto La Estanzuela, miradores y arte rural en piedra."}'::jsonb, true, 'territories-data.js', 'esteli::reserva natural tisey la estanzuela', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-galeria-de-esculturas-en-piedra-de-don-alberto', 'galeria-de-esculturas-en-piedra-de-don-alberto', 'Galería de Esculturas en Piedra de Don Alberto', 'centro_cultural', null, 'Arte Popular Rústico', 'fa-palette', 'esteli', null, null, 'Figuras talladas en la roca de la montaña por el artista Alberto Gutiérrez, dentro de la reserva Tisey.', 'Figuras talladas en la roca de la montaña por el artista Alberto Gutiérrez, dentro de la reserva Tisey.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'esteli::galeria de esculturas en piedra de don alberto', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-reserva-natural-miraflor', 'reserva-natural-miraflor', 'Reserva Natural Miraflor', 'reserva', null, 'Orquídeas & Turismo Rural', 'fa-seedling', 'esteli', 'esteli__esteli', null, 'Bosque nuboso, orquídeas, aves y familias campesinas que reciben visitantes en sus fincas.', 'Bosque nuboso, orquídeas, aves y familias campesinas que reciben visitantes en sus fincas.', 13.21, -86.28, 'centroid', false, null, 'verified', '2026-10-05'::timestamptz, 'OpenStreetMap / Wikidata (catálogo de naturaleza 2026)', null, 'other', '{"activities":"Agroturismo, senderismo, aves, café y turismo comunitario.","facts":"Paisaje protegido de montañas, fincas y bosques del norte, reconocido por turismo rural, biodiversidad y producción sostenible."}'::jsonb, true, 'territories-data.js', 'esteli::reserva natural miraflor', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-fabricas-de-puros-artesanales', 'fabricas-de-puros-artesanales', 'Fábricas de Puros Artesanales', 'centro_cultural', null, 'Ruta del Tabaco de Alta Gama', 'fa-fire', 'esteli', null, null, 'Recorridos por fábricas de Estelí donde el tabaco se enrolla a mano.', 'Recorridos por fábricas de Estelí donde el tabaco se enrolla a mano.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'esteli::fabricas de puros artesanales', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-murales-revolucionarios-y-urbanos', 'murales-revolucionarios-y-urbanos', 'Murales Revolucionarios y Urbanos', 'centro_cultural', null, 'Arte Público', 'fa-brush', 'esteli', null, null, 'Murales en las calles de Estelí que cuentan su historia social y política; se recorren a pie por el centro.', 'Murales en las calles de Estelí que cuentan su historia social y política; se recorren a pie por el centro.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'esteli::murales revolucionarios y urbanos', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-la-garnacha', 'la-garnacha', 'La Garnacha', 'turismo_comunitario', null, 'Comunidad, queso de cabra, producción sostenible y aves', 'fa-people-group', 'esteli', null, null, 'Comunidad en la Reserva Tisey-La Estanzuela que produce queso de cabra y recibe visitantes con turismo rural.', 'Comunidad en la Reserva Tisey-La Estanzuela que produce queso de cabra y recibe visitantes con turismo rural.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'esteli::la garnacha', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-condega-y-su-taller-comunal-de-ceramica', 'condega-y-su-taller-comunal-de-ceramica', 'Condega y su Taller Comunal de Cerámica', 'sitio_historico', null, 'Arqueología, barro y artesanía', 'fa-hands', 'esteli', null, null, 'Condega es tierra de alfarería; en Ducualí Grande las mujeres trabajan el barro con técnicas tradicionales.', 'Condega es tierra de alfarería; en Ducualí Grande las mujeres trabajan el barro con técnicas tradicionales.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'esteli::condega y su taller comunal de ceramica', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-pueblo-nuevo', 'pueblo-nuevo', 'Pueblo Nuevo', 'sitio_historico', null, 'Paleontología, arqueología y memoria', 'fa-landmark', 'esteli', null, null, 'Municipio del norte de Estelí conocido por el Museo Paleontológico El Bosque, con fósiles de megafauna encontrados en la zona.', 'Municipio del norte de Estelí conocido por el Museo Paleontológico El Bosque, con fósiles de megafauna encontrados en la zona.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'esteli::pueblo nuevo', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-san-juan-de-limay', 'san-juan-de-limay', 'San Juan de Limay', 'centro_cultural', null, 'Gorditas de Limay, marmolina y talleres de escultura', 'fa-hammer', 'esteli', null, null, 'Pueblo de Estelí famoso por sus artesanos que tallan piedra marmolina en figuras y animales.', 'Pueblo de Estelí famoso por sus artesanos que tallan piedra marmolina en figuras y animales.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'esteli::san juan de limay', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-mirador-san-luis', 'mirador-san-luis', 'Mirador San Luis', 'mirador', null, 'Paisaje, fotografía y artesanía', 'fa-eye', 'esteli', null, null, 'Mirador en las montañas de Estelí con paisaje amplio, fotografía y artesanía local.', 'Mirador en las montañas de Estelí con paisaje amplio, fotografía y artesanía local.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'esteli::mirador san luis', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-finca-lindos-ojos', 'finca-lindos-ojos', 'Finca Lindos Ojos', 'agroturismo', null, 'Turismo rural · Caminatas', 'fa-house-chimney', 'esteli', null, null, 'Finca de turismo rural dentro de la Reserva Natural Miraflor Moropotente, con bosques, aves y café orgánico.', 'Finca de turismo rural dentro de la Reserva Natural Miraflor Moropotente, con bosques, aves y café orgánico.', null, null, 'missing', false, 'Comunidad El Cebollal, de la rampa 2 km al oeste, Reserva Miraflor Moropotente.', 'verified', '2026-10-05'::timestamptz, 'INTUR · Catálogo de Iniciativas de Turismo Rural y Comunitario (2026)', null, 'other', '{"activities":"Caminatas, observación de aves, senderismo, ordeño, cabalgatas y demostración de agricultura orgánica de café.","services":"Bebidas, hospedería y cocina para huéspedes.","hours":"9:00 a. m.–6:00 p. m.","modality":"Turismo rural","facts":"Finca de turismo rural dentro de la Reserva Natural Miraflor Moropotente, con bosques, aves y café orgánico.","map":"https://www.google.com/maps/d/u/0/edit?mid=1D33pHCZSFRX8nlP8fizGDle4AO1L23Y&usp=sharing","contact_note":"Contacto publicado por INTUR en el catálogo 2026; confirmar antes de viajar."}'::jsonb, true, 'territories-data.js', 'esteli::finca lindos ojos', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-ecoposada-tisey', 'ecoposada-tisey', 'Ecoposada Tisey', 'turismo_rural', null, 'Turismo rural · Senderismo', 'fa-house-chimney', 'esteli', null, null, 'Posada ecológica en la Reserva Tisey-Estanzuela con miradores, senderos, cascadas y clima fresco de montaña.', 'Posada ecológica en la Reserva Tisey-Estanzuela con miradores, senderos, cascadas y clima fresco de montaña.', null, null, 'missing', false, 'Comunidad Almaciguera, 12 km al sureste de Estelí.', 'verified', '2026-10-05'::timestamptz, 'INTUR · Catálogo de Iniciativas de Turismo Rural y Comunitario (2026)', null, 'other', '{"activities":"Senderismo, observación de flora y fauna, miradores y recorrido por vivero.","services":"Alimentos, bebidas y hospedería.","hours":"Lunes a viernes 8:00 a. m.–6:00 p. m.; sábado y domingo 8:00 a. m.–9:00 p. m.","modality":"Turismo rural","facts":"Posada ecológica en la Reserva Tisey-Estanzuela con miradores, senderos, cascadas y clima fresco de montaña.","map":"https://www.google.com/maps/d/u/0/edit?mid=1vN25WegeowQTfD4M9Q-O4t8FQ-5Ko6U&usp=sharing","contact_note":"Contacto publicado por INTUR en el catálogo 2026; confirmar antes de viajar."}'::jsonb, true, 'territories-data.js', 'esteli::ecoposada tisey', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-albergue-familiar-neblina-del-bosque', 'albergue-familiar-neblina-del-bosque', 'Albergue Familiar Neblina del Bosque', 'turismo_rural', null, 'Turismo rural · Senderismo', 'fa-house-chimney', 'esteli', null, null, 'Albergue familiar en el bosque nublado de Miraflor Moropotente, con huertos, hongos y recorridos botánicos.', 'Albergue familiar en el bosque nublado de Miraflor Moropotente, con huertos, hongos y recorridos botánicos.', null, null, 'missing', false, 'De la rampa 400 metros al oeste, Reserva Miraflor Moropotente.', 'verified', '2026-10-05'::timestamptz, 'INTUR · Catálogo de Iniciativas de Turismo Rural y Comunitario (2026)', null, 'other', '{"activities":"Senderismo, cabalgatas, huertos, recorridos botánicos, tours de hongos y observación de flora y fauna.","services":"Alimentos, bebidas, hospedería y camping.","hours":"Lunes a domingo, 9:00 a. m.–6:00 p. m.","modality":"Turismo rural","facts":"Albergue familiar en el bosque nublado de Miraflor Moropotente, con huertos, hongos y recorridos botánicos.","map":"https://www.google.com/maps/d/u/0/edit?mid=1awmyyNPpcP5WSr60aDiI_WU6F-VotDA&usp=sharing","contact_note":"Contacto publicado por INTUR en el catálogo 2026; confirmar antes de viajar."}'::jsonb, true, 'territories-data.js', 'esteli::albergue familiar neblina del bosque', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-asopasn-programa-agricola-san-nicolas', 'asopasn-programa-agricola-san-nicolas', 'ASOPASN · Programa Agrícola San Nicolás', 'turismo_comunitario', null, 'Turismo rural y comunitario · Senderismo', 'fa-people-group', 'esteli', null, null, 'Iniciativa comunitaria en La Garnacha, San Nicolás, con paisajes de montaña, queso de cabra, hortalizas y miradores.', 'Iniciativa comunitaria en La Garnacha, San Nicolás, con paisajes de montaña, queso de cabra, hortalizas y miradores.', null, null, 'missing', false, 'Contiguo a la escuela de la comunidad La Garnacha, San Nicolás.', 'verified', '2026-10-05'::timestamptz, 'INTUR · Catálogo de Iniciativas de Turismo Rural y Comunitario (2026)', null, 'other', '{"activities":"Senderismo, tours de queso de cabra, artesanías, hortalizas, avistamiento de aves y miradores.","services":"Alimentos, bebidas y hospedaje.","hours":"Lunes a domingo, 8:00 a. m.–6:00 p. m.","modality":"Turismo rural y comunitario","facts":"Iniciativa comunitaria en La Garnacha, San Nicolás, con paisajes de montaña, queso de cabra, hortalizas y miradores.","map":"https://www.google.com/maps/d/u/0/edit?mid=1ZUb32cBf3i_gJSlNQNWp2Sprp7fBTYo&usp=sharing","contact_note":"Contacto publicado por INTUR en el catálogo 2026; confirmar antes de viajar."}'::jsonb, true, 'territories-data.js', 'esteli::asopasn programa agricola san nicolas', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-finca-agroturistica-fuente-de-vida', 'finca-agroturistica-fuente-de-vida', 'Finca Agroturística Fuente de Vida', 'agroturismo', null, 'Agroturismo · Senderismo', 'fa-seedling', 'esteli', null, null, 'Finca en Miraflor Moropotente para convivir con el campo: café, orquídeas, plantas medicinales, rosquillas y voluntariado.', 'Finca en Miraflor Moropotente para convivir con el campo: café, orquídeas, plantas medicinales, rosquillas y voluntariado.', null, null, 'missing', false, 'De la rampa 1½ km al noreste, comunidad El Cebollal.', 'verified', '2026-10-05'::timestamptz, 'INTUR · Catálogo de Iniciativas de Turismo Rural y Comunitario (2026)', null, 'other', '{"activities":"Senderismo, cabalgatas, aves, café, orquídeas y plantas medicinales, agricultura orgánica, granja y elaboración de rosquillas, queso y tortillas.","services":"Alimentos, bebidas y hospedería.","hours":"Lunes a domingo, 8:00 a. m.–6:00 p. m.","modality":"Agroturismo","facts":"Finca en Miraflor Moropotente para convivir con el campo: café, orquídeas, plantas medicinales, rosquillas y voluntariado.","map":"https://www.google.com/maps/d/u/0/edit?mid=1Ms7wbX6q9P3oAqtzQXfOp2EbgAe22cs&usp=sharing","contact_note":"Contacto publicado por INTUR en el catálogo 2026; confirmar antes de viajar."}'::jsonb, true, 'territories-data.js', 'esteli::finca agroturistica fuente de vida', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-salto-de-la-estanzuela', 'salto-de-la-estanzuela', 'Salto de La Estanzuela', 'cascada', null, 'Cascada · Senderismo', 'fa-droplet', 'esteli', 'esteli__esteli', null, 'Salto asociado al río Estelí y uno de los atractivos naturales más conocidos del municipio; su coordenada debe confirmarse en campo.', 'Salto asociado al río Estelí y uno de los atractivos naturales más conocidos del municipio; su coordenada debe confirmarse en campo.', 13.025, -86.39, 'approximate', false, null, 'verified', '2026-10-05'::timestamptz, 'Mapa Nacional de Turismo / referencia geográfica secundaria', 'https://www.mapanicaragua.com/category/atractivos-turisticos/', 'other', '{"activities":"Senderismo, fotografía y naturaleza.","modality":"Cascadas","facts":"Salto asociado al río Estelí y uno de los atractivos naturales más conocidos del municipio; su coordenada debe confirmarse en campo."}'::jsonb, true, 'territories-data.js', 'esteli::salto de la estanzuela', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-cuevas-y-mirador-de-apaguaji', 'cuevas-y-mirador-de-apaguaji', 'Cuevas y Mirador de Apaguají', 'cueva', null, 'Cueva o cañón · Senderismo', 'fa-mountain', 'esteli', 'esteli__san_nicolas', null, 'Sistema de cuevas y mirador en la parte alta de Tisey-La Estanzuela; Visit Nicaragua destaca su interés ecológico y la presencia de murciélagos.', 'Sistema de cuevas y mirador en la parte alta de Tisey-La Estanzuela; Visit Nicaragua destaca su interés ecológico y la presencia de murciélagos.', 12.96849, -86.37914, 'exact', true, null, 'verified', '2026-10-05'::timestamptz, 'Visit Nicaragua / OpenStreetMap (catálogo de naturaleza 2026)', null, 'other', '{"activities":"Senderismo, miradores, exploración guiada de cuevas y fotografía.","facts":"Sistema de cuevas y mirador en la parte alta de Tisey-La Estanzuela; Visit Nicaragua destaca su interés ecológico y la presencia de murciélagos.","note":"Incluye el registro \"Mirador Apaguají\" (mismo punto)."}'::jsonb, true, 'territories-data.js', 'esteli::cuevas y mirador de apaguaji', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-cueva-del-duende-tisey', 'cueva-del-duende-tisey', 'Cueva del Duende (Tisey)', 'cueva', null, 'Cueva o cañón · Senderismo', 'fa-mountain', 'esteli', 'esteli__san_nicolas', null, 'Cueva mencionada en el plan de manejo de Tisey-La Estanzuela, con un mirador panorámico próximo en la zona montañosa de la reserva.', 'Cueva mencionada en el plan de manejo de Tisey-La Estanzuela, con un mirador panorámico próximo en la zona montañosa de la reserva.', 12.97122, -86.38087, 'exact', true, null, 'verified', '2026-10-05'::timestamptz, 'Plan de Manejo Tisey-La Estanzuela / OpenStreetMap (catálogo de naturaleza 2026)', null, 'other', '{"activities":"Senderismo, paisaje y exploración solo con guía local y respeto a la fauna de cuevas.","facts":"Cueva mencionada en el plan de manejo de Tisey-La Estanzuela, con un mirador panorámico próximo en la zona montañosa de la reserva.","note":"Incluye el registro \"Mirador Cueva del Duende\" (mismo punto)."}'::jsonb, true, 'territories-data.js', 'esteli::cueva del duende tisey', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-mirador-el-ranchito-tisey', 'mirador-el-ranchito-tisey', 'Mirador El Ranchito (Tisey)', 'mirador', null, 'Mirador · Senderismo', 'fa-binoculars', 'esteli', 'esteli__san_nicolas', null, 'Mirador rural dentro del conjunto de puntos panorámicos de la zona de Apaguají, en Tisey-La Estanzuela.', 'Mirador rural dentro del conjunto de puntos panorámicos de la zona de Apaguají, en Tisey-La Estanzuela.', 12.97223, -86.37849, 'exact', true, null, 'verified', '2026-10-05'::timestamptz, 'OpenStreetMap (catálogo de naturaleza 2026)', null, 'other', '{"activities":"Senderismo, paisaje y fotografía.","facts":"Mirador rural dentro del conjunto de puntos panorámicos de la zona de Apaguají, en Tisey-La Estanzuela."}'::jsonb, true, 'territories-data.js', 'esteli::mirador el ranchito tisey', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-volcan-san-cristobal-1-745-msnm', 'volcan-san-cristobal-1-745-msnm', 'Volcán San Cristóbal (1,745 msnm)', 'volcan', null, 'Pico Más Alto del País', 'fa-volcano', 'chinandega', null, null, 'El volcán más alto de Nicaragua, activo; el ascenso es exigente y se hace solo con guía y buen estado físico.', 'El volcán más alto de Nicaragua, activo; el ascenso es exigente y se hace solo con guía y buen estado físico.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'chinandega::volcan san cristobal 1 745 msnm', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-volcan-cosiguina-y-laguna-crater', 'volcan-cosiguina-y-laguna-crater', 'Volcán Cosigüina y Laguna Cráter', 'volcan', null, 'Reserva Natural & Golfo', 'fa-mountain', 'chinandega', 'chinandega__el_viejo', null, 'Volcán en la península de Cosigüina con una laguna en el cráter y vistas al Golfo de Fonseca.', 'Volcán en la península de Cosigüina con una laguna en el cráter y vistas al Golfo de Fonseca.', 12.983333, -87.566667, 'reference', false, null, 'verified', '2026-10-05'::timestamptz, 'MARENA / Geographic Names (catálogo de naturaleza 2026)', null, 'other', '{"activities":"Senderismo, observación de la laguna cratérica y paisaje del Golfo de Fonseca.","facts":"Macizo volcánico aislado en la Península de Cosigüina; su gran erupción histórica de 1835 transformó la morfología de la caldera."}'::jsonb, true, 'territories-data.js', 'chinandega::volcan cosiguina y laguna crater', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-basilica-menor-de-nuestra-senora-del-trono', 'basilica-menor-de-nuestra-senora-del-trono', 'Basílica Menor de Nuestra Señora del Trono', 'atractivo', null, 'Santuario Nacional', 'fa-church', 'chinandega', null, null, 'Santuario de El Viejo, centro de la devoción a la Virgen del Trono y de la tradición de La Lavada de la Plata.', 'Santuario de El Viejo, centro de la devoción a la Virgen del Trono y de la tradición de La Lavada de la Plata.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'chinandega::basilica menor de nuestra senora del trono', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-playas-de-aserradores-jiquilillo', 'playas-de-aserradores-jiquilillo', 'Playas de Aserradores & Jiquilillo', 'playa', null, 'Surf & Esteros', 'fa-umbrella-beach', 'chinandega', null, null, 'Playas del Pacífico norte con olas para surf, esteros y pueblos de pescadores.', 'Playas del Pacífico norte con olas para surf, esteros y pueblos de pescadores.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'chinandega::playas de aserradores jiquilillo', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-estero-padre-ramos', 'estero-padre-ramos', 'Estero Padre Ramos', 'reserva', null, 'Santuario de Manglar & Tortugas', 'fa-tree', 'chinandega', 'chinandega__el_viejo', null, 'Reserva de manglares y esteros donde anidan tortugas marinas; se recorre en lancha con guías comunitarios.', 'Reserva de manglares y esteros donde anidan tortugas marinas; se recorre en lancha con guías comunitarios.', 12.78091, -87.48321, 'centroid', false, null, 'verified', '2026-10-05'::timestamptz, 'Mapa Nacional de Turismo (catálogo de naturaleza 2026)', null, 'other', '{"activities":"Kayak, observación de aves y fauna y recorridos por ramales del estero.","facts":"Área protegida de manglar en la costa del Pacífico norte, de gran importancia para la biodiversidad y los medios de vida comunitarios."}'::jsonb, true, 'territories-data.js', 'chinandega::estero padre ramos', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-rancho-maribel', 'rancho-maribel', 'Rancho Maribel', 'agroturismo', null, 'Turismo rural · Cabalgatas por la finca', 'fa-house-chimney', 'chinandega', null, null, 'Destino rural para vivir una auténtica experiencia campestre y la hospitalidad de la comunidad, cerca de Somotillo.', 'Destino rural para vivir una auténtica experiencia campestre y la hospitalidad de la comunidad, cerca de Somotillo.', null, null, 'missing', false, 'Km 180 carretera a Somotillo, Finca Los 2 Potrillos.', 'verified', '2026-10-05'::timestamptz, 'INTUR · Catálogo de Iniciativas de Turismo Rural y Comunitario (2026)', null, 'other', '{"activities":"Cabalgatas por la finca, ordeño de vacas y elaboración de productos lácteos.","services":"Alimentos y bebidas, venta de artesanía local y tours.","hours":"Lunes a domingo, 6:00 a. m.–9:00 p. m.","modality":"Turismo rural","facts":"Destino rural para vivir una auténtica experiencia campestre y la hospitalidad de la comunidad, cerca de Somotillo.","map":"https://www.google.com/maps/d/u/0/edit?mid=1x5feOCfIxE6COeQyObhJTXiAWriTH64&usp=sharing","contact_note":"Contacto publicado por INTUR en el catálogo 2026; confirmar antes de viajar."}'::jsonb, true, 'territories-data.js', 'chinandega::rancho maribel', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-campamento-ecologico-campuzano', 'campamento-ecologico-campuzano', 'Campamento Ecológico Campuzano', 'turismo_comunitario', null, 'Turismo rural y comunitario · Observación de flora', 'fa-people-group', 'chinandega', null, null, 'Campamento comunitario en Ranchería con piscinas naturales, bosque para observar fauna y ranchos de descanso.', 'Campamento comunitario en Ranchería con piscinas naturales, bosque para observar fauna y ranchos de descanso.', null, null, 'missing', false, 'Km 150 carretera a Somotillo, 2 km al oeste, comunidad Campuzano 1.', 'verified', '2026-10-05'::timestamptz, 'INTUR · Catálogo de Iniciativas de Turismo Rural y Comunitario (2026)', null, 'other', '{"activities":"Observación de flora y fauna, cancha deportiva, senderismo, tours, camping y cabalgata.","services":"Alimentos y bebidas, artesanía local y tours.","hours":"Lunes a domingo, 6:00 a. m.–6:00 p. m.","modality":"Turismo rural y comunitario","facts":"Campamento comunitario en Ranchería con piscinas naturales, bosque para observar fauna y ranchos de descanso.","map":"https://www.google.com/maps/d/u/0/edit?mid=19NEj9BlhGLQ0lvp0bn7lVl7_P7zfrDo&usp=sharing","contact_note":"Contacto publicado por INTUR en el catálogo 2026; confirmar antes de viajar."}'::jsonb, true, 'territories-data.js', 'chinandega::campamento ecologico campuzano', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-cabanas-el-manantial', 'cabanas-el-manantial', 'Cabañas El Manantial', 'atractivo', null, 'Turismo de naturaleza · Senderismo', 'fa-tree', 'chinandega', null, null, 'Reserva Silvestre Privada en Cinco Pinos con bosques, huertos y vivero, y cabañas para dormir en la naturaleza.', 'Reserva Silvestre Privada en Cinco Pinos con bosques, huertos y vivero, y cabañas para dormir en la naturaleza.', null, null, 'missing', false, 'APROSEDE 300 m al sur, comunidad El Espino, Cinco Pinos.', 'verified', '2026-10-05'::timestamptz, 'INTUR · Catálogo de Iniciativas de Turismo Rural y Comunitario (2026)', null, 'other', '{"activities":"Senderismo, cabalgatas, flora y fauna, huertos y vivero.","services":"Alojamiento, alimentos y bebidas.","hours":"Lunes a domingo, 6:00 a. m.–6:00 p. m.","modality":"Turismo de naturaleza","facts":"Reserva Silvestre Privada en Cinco Pinos con bosques, huertos y vivero, y cabañas para dormir en la naturaleza.","map":"https://www.google.com/maps/d/u/0/edit?mid=1RDeL_Ju0LBCMqnELjCZe5DC2S-iI978&usp=sharing","contact_note":"Contacto publicado por INTUR en el catálogo 2026; confirmar antes de viajar."}'::jsonb, true, 'territories-data.js', 'chinandega::cabanas el manantial', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-playa-jiquilillo', 'playa-jiquilillo', 'Playa Jiquilillo', 'playa', null, 'Playa · Baño', 'fa-umbrella-beach', 'chinandega', 'chinandega__el_viejo', null, 'Extensa playa del Pacífico norte que el Mapa Nacional de Turismo identifica entre los destinos favoritos de sol y playa del país.', 'Extensa playa del Pacífico norte que el Mapa Nacional de Turismo identifica entre los destinos favoritos de sol y playa del país.', 12.736, -87.451, 'exact', true, null, 'verified', '2026-10-05'::timestamptz, 'Mapa Nacional de Turismo', 'https://www.mapanicaragua.com/sol-y-playa/', 'other', '{"activities":"Baño, surf, pesca, descanso y naturaleza.","modality":"Playas","facts":"Extensa playa del Pacífico norte que el Mapa Nacional de Turismo identifica entre los destinos favoritos de sol y playa del país."}'::jsonb, true, 'territories-data.js', 'chinandega::playa jiquilillo', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-puerto-salvador-allende-y-lago-xolotlan', 'puerto-salvador-allende-y-lago-xolotlan', 'Puerto Salvador Allende y lago Xolotlán', 'lago', null, 'Gastronomía, navegación, familia, paisaje y entretenimiento', 'fa-ship', 'managua', null, null, 'Malecón de Managua a orillas del lago Xolotlán, con restaurantes, paseos en barco y espacios familiares.', 'Malecón de Managua a orillas del lago Xolotlán, con restaurantes, paseos en barco y espacios familiares.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'managua::puerto salvador allende y lago xolotlan', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-centro-historico-de-managua', 'centro-historico-de-managua', 'Centro Histórico de Managua', 'sitio_historico', null, 'Plaza de la Revolución, Antigua Catedral y patrimonio', 'fa-landmark', 'managua', null, null, 'Zona de la antigua Managua con la Catedral vieja, el Palacio de la Cultura y la plaza junto al lago Xolotlán.', 'Zona de la antigua Managua con la Catedral vieja, el Palacio de la Cultura y la plaza junto al lago Xolotlán.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'managua::centro historico de managua', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-teatro-nacional-ruben-dario', 'teatro-nacional-ruben-dario', 'Teatro Nacional Rubén Darío', 'centro_cultural', null, 'Artes escénicas, música, arquitectura y cultura', 'fa-masks-theater', 'managua', null, null, 'Principal escenario de artes escénicas del país, frente al lago Xolotlán, con conciertos, danza y teatro.', 'Principal escenario de artes escénicas del país, frente al lago Xolotlán, con conciertos, danza y teatro.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'managua::teatro nacional ruben dario', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-huellas-de-acahualinca', 'huellas-de-acahualinca', 'Huellas de Acahualinca', 'sitio_historico', null, 'Arqueología, geología e historia humana', 'fa-shoe-prints', 'managua', null, null, 'Huellas de personas y animales conservadas en ceniza volcánica, de más de dos milenios de antigüedad, protegidas en un museo.', 'Huellas de personas y animales conservadas en ceniza volcánica, de más de dos milenios de antigüedad, protegidas en un museo.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'managua::huellas de acahualinca', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-laguna-de-tiscapa', 'laguna-de-tiscapa', 'Laguna de Tiscapa', 'laguna', null, 'Laguna cratérica, miradores, historia y fotografía', 'fa-camera', 'managua', 'managua__managua', null, 'Laguna cratérica en el corazón de Managua, con miradores, historia y canopy.', 'Laguna cratérica en el corazón de Managua, con miradores, historia y canopy.', 12.13943, -86.27034, 'centroid', false, null, 'verified', '2026-10-05'::timestamptz, 'Mapa Nacional de Turismo / MARENA (catálogo de naturaleza 2026)', null, 'other', '{"activities":"Paisaje urbano, fotografía e interpretación ambiental e histórica.","facts":"Laguna cratérica dentro de Managua; la reserva comprende la laguna y la Loma de Tiscapa y fue declarada área protegida en 1991."}'::jsonb, true, 'territories-data.js', 'managua::laguna de tiscapa', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-laguna-de-xiloa-y-apoyeque', 'laguna-de-xiloa-y-apoyeque', 'Laguna de Xiloá y Apoyeque', 'laguna', null, 'Recreación autorizada, paisaje volcánico y naturaleza', 'fa-water', 'managua', 'managua__mateare', null, 'Lagunas de origen volcánico en la península de Chiltepe; Xiloá es balneario y Apoyeque una reserva natural.', 'Lagunas de origen volcánico en la península de Chiltepe; Xiloá es balneario y Apoyeque una reserva natural.', 12.22151, -86.32196, 'centroid', false, null, 'verified', '2026-10-05'::timestamptz, 'Visit Nicaragua / OpenStreetMap (catálogo de naturaleza 2026)', null, 'other', '{"activities":"Baño en sectores habilitados, paisaje, recreación y fotografía.","facts":"Laguna de cráter volcánico en la Península de Chiltepe, dentro de un entorno protegido cercano a Managua."}'::jsonb, true, 'territories-data.js', 'managua::laguna de xiloa y apoyeque', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
commit;
