-- BAQUEANO · Importación territories-data.js → Supabase · parte 04 de 07
-- Generado desde supabase/imports/20261005_territories_import.sql. Ejecutar las partes EN ORDEN en el SQL Editor.
-- Idempotente: si una parte se ejecuta dos veces, no duplica (ON CONFLICT).
begin;
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-laguna-de-asososca', 'laguna-de-asososca', 'Laguna de Asososca', 'laguna', null, 'Paisaje natural y observación desde áreas permitidas', 'fa-droplet', 'managua', 'managua__managua', null, 'Laguna cratérica que abastece de agua a Managua; se observa solo desde los miradores permitidos.', 'Laguna cratérica que abastece de agua a Managua; se observa solo desde los miradores permitidos.', 12.137778, -86.313611, 'centroid', false, null, 'verified', '2026-10-05'::timestamptz, 'Mapa Nacional de Turismo / MARENA (catálogo de naturaleza 2026)', null, 'other', '{"activities":"Paisaje y educación ambiental; acceso condicionado por su función de abastecimiento.","facts":"Laguna cratérica y reserva natural al oeste de Managua; reservorio estratégico de agua para la ciudad, con acceso condicionado."}'::jsonb, true, 'territories-data.js', 'managua::laguna de asososca', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-reserva-natural-chocoyero-el-brujo', 'reserva-natural-chocoyero-el-brujo', 'Reserva Natural Chocoyero–El Brujo', 'cascada', null, 'Senderismo, bosque, aves e interpretación ambiental', 'fa-feather', 'managua', 'managua__ticuantepe', null, 'Cascadas y paredes donde anidan miles de chocoyos, a poca distancia de la capital.', 'Cascadas y paredes donde anidan miles de chocoyos, a poca distancia de la capital.', 11.99, -86.25, 'approximate', false, null, 'verified', '2026-10-05'::timestamptz, 'Mapa Nacional de Turismo / KBA', 'https://www.mapanicaragua.com/reserva-natural-chocoyero-el-brujo/', 'other', '{"activities":"Senderismo, aves, naturaleza y educación ambiental.","facts":"Dos saltos de agua de más de 20 metros dentro de la Reserva Natural Chocoyero-El Brujo, área protegida de Ticuantepe."}'::jsonb, true, 'territories-data.js', 'managua::reserva natural chocoyero el brujo', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-ticuantepe-y-el-crucero', 'ticuantepe-y-el-crucero', 'Ticuantepe y El Crucero', 'turismo_rural', null, 'Agricultura, café, clima fresco, miradores y turismo rural', 'fa-seedling', 'managua', null, null, 'Municipios de altura al sur de Managua: Ticuantepe con fincas de piña y El Crucero con clima fresco y miradores.', 'Municipios de altura al sur de Managua: Ticuantepe con fincas de piña y El Crucero con clima fresco y miradores.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'managua::ticuantepe y el crucero', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-pochomil-y-masachapa', 'pochomil-y-masachapa', 'Pochomil y Masachapa', 'playa', null, 'Playa, pesca, gastronomía, familia y atardecer', 'fa-umbrella-beach', 'managua', null, null, 'Playas del Pacífico de Managua con pesca, comedores de mariscos y atardeceres.', 'Playas del Pacífico de Managua con pesca, comedores de mariscos y atardeceres.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'managua::pochomil y masachapa', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-mercado-roberto-huembes', 'mercado-roberto-huembes', 'Mercado Roberto Huembes', 'mercado', null, 'Artesanía, textiles, comida y comercio local', 'fa-store', 'managua', null, null, 'Mercado de Managua con una gran sección de artesanía nicaragüense, textiles y comida típica.', 'Mercado de Managua con una gran sección de artesanía nicaragüense, textiles y comida típica.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'managua::mercado roberto huembes', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-parque-luis-alfonso-velasquez-flores', 'parque-luis-alfonso-velasquez-flores', 'Parque Luis Alfonso Velásquez Flores', 'parque', null, 'Turismo familiar y recreación al aire libre', 'fa-children', 'managua', null, null, 'Parque urbano familiar de Managua con áreas verdes, juegos y espacios recreativos.', 'Parque urbano familiar de Managua con áreas verdes, juegos y espacios recreativos.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'managua::parque luis alfonso velasquez flores', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-tipitapa-y-centro-turistico-el-trapiche', 'tipitapa-y-centro-turistico-el-trapiche', 'Tipitapa y Centro Turístico El Trapiche', 'sitio_historico', null, 'Termalismo, recreación, historia y gastronomía', 'fa-hot-tub-person', 'managua', null, null, 'Tipitapa, entre los dos grandes lagos, es conocida por sus aguas termales; El Trapiche ofrece piscinas y comida típica.', 'Tipitapa, entre los dos grandes lagos, es conocida por sus aguas termales; El Trapiche ofrece piscinas y comida típica.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'managua::tipitapa y centro turistico el trapiche', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-hotel-bosque-las-nubes', 'hotel-bosque-las-nubes', 'Hotel Bosque Las Nubes', 'agroturismo', null, 'Agroturismo · Senderismo', 'fa-seedling', 'managua', null, null, 'Bosque nuboso de clima fresco en El Crucero, con árboles centenarios, senderos entre la niebla y café de la finca.', 'Bosque nuboso de clima fresco en El Crucero, con árboles centenarios, senderos entre la niebla y café de la finca.', null, null, 'missing', false, 'Del parque 1.5 km al este, El Crucero.', 'verified', '2026-10-05'::timestamptz, 'INTUR · Catálogo de Iniciativas de Turismo Rural y Comunitario (2026)', null, 'other', '{"activities":"Senderismo, cabalgata, flora y fauna, tour por cafetales, exposición y venta de café.","services":"Alimentos, bebidas y hospedería.","hours":"6:00 a. m.–5:00 p. m.","modality":"Agroturismo","facts":"Bosque nuboso de clima fresco en El Crucero, con árboles centenarios, senderos entre la niebla y café de la finca.","map":"https://www.google.com/maps/d/u/0/edit?mid=1a2meFNl_1jJg3C6UT66jdt3QRxFNjuo&usp=sharing","contact_note":"Contacto publicado por INTUR en el catálogo 2026; confirmar antes de viajar."}'::jsonb, true, 'territories-data.js', 'managua::hotel bosque las nubes', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-finca-las-delicias', 'finca-las-delicias', 'Finca Las Delicias', 'agroturismo', null, 'Agroturismo · Senderismo', 'fa-seedling', 'managua', null, null, 'Finca cafetalera entre montañas y neblina con vistas al lago Xolotlán, el volcán Momotombo y Chiltepe.', 'Finca cafetalera entre montañas y neblina con vistas al lago Xolotlán, el volcán Momotombo y Chiltepe.', null, null, 'missing', false, 'Parque de El Crucero, Los Guatuzos, 3.5 km Las Nubes, 600 m al noroeste.', 'verified', '2026-10-05'::timestamptz, 'INTUR · Catálogo de Iniciativas de Turismo Rural y Comunitario (2026)', null, 'other', '{"activities":"Senderismo, observación de aves y tours por cafetales.","services":"Hospedería, alimentación y venta de café.","hours":"6:00 a. m.–6:00 p. m.","modality":"Agroturismo","facts":"Finca cafetalera entre montañas y neblina con vistas al lago Xolotlán, el volcán Momotombo y Chiltepe.","map":"https://www.google.com/maps/d/u/0/edit?mid=1r09KfSNCICLZkkdyLr-zg-6dGe2wgSU&usp=sharing","contact_note":"Contacto publicado por INTUR en el catálogo 2026; confirmar antes de viajar."}'::jsonb, true, 'territories-data.js', 'managua::finca las delicias', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-reserva-silvestre-privada-montibelli', 'reserva-silvestre-privada-montibelli', 'Reserva Silvestre Privada Montibelli', 'reserva', null, 'Turismo de naturaleza · Senderismo', 'fa-tree', 'managua', null, null, 'Reserva de bosque con seis miradores hacia las sierras de Managua y los volcanes Masaya y Mombacho.', 'Reserva de bosque con seis miradores hacia las sierras de Managua y los volcanes Masaya y Mombacho.', null, null, 'missing', false, 'Km 18.5 carretera Ticuantepe–La Concha, 3 km al oeste, comunidad Enramada N.º 2.', 'verified', '2026-10-05'::timestamptz, 'INTUR · Catálogo de Iniciativas de Turismo Rural y Comunitario (2026)', null, 'other', '{"activities":"Senderismo, monitoreo de flora y fauna, tours nocturnos y camping.","services":"Alimentos y bebidas, hospedería y actividades al aire libre.","hours":"8:00 a. m.–5:00 p. m. (con reservación).","modality":"Turismo de naturaleza","facts":"Reserva de bosque con seis miradores hacia las sierras de Managua y los volcanes Masaya y Mombacho.","contact_note":"Contacto publicado por INTUR en el catálogo 2026; confirmar antes de viajar."}'::jsonb, true, 'territories-data.js', 'managua::reserva silvestre privada montibelli', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-playa-pochomil', 'playa-pochomil', 'Playa Pochomil', 'playa', null, 'Playa · Baño', 'fa-umbrella-beach', 'managua', 'managua__san_rafael_del_sur', null, 'Playa amplia, plana y alargada; una de las más cercanas a Managua y con servicios turísticos.', 'Playa amplia, plana y alargada; una de las más cercanas a Managua y con servicios turísticos.', 11.77244, -86.50435, 'exact', true, null, 'verified', '2026-10-05'::timestamptz, 'Mapa Nacional de Turismo / GeoNames', 'https://www.mapanicaragua.com/sol-y-playa/', 'other', '{"activities":"Baño, caminata, paseo a caballo y gastronomía.","modality":"Playas","facts":"Playa amplia, plana y alargada; una de las más cercanas a Managua y con servicios turísticos."}'::jsonb, true, 'territories-data.js', 'managua::playa pochomil', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-playa-masachapa', 'playa-masachapa', 'Playa Masachapa', 'playa', null, 'Playa · Baño', 'fa-umbrella-beach', 'managua', 'managua__san_rafael_del_sur', null, 'Pueblo pesquero y playa del Pacífico cercana a Pochomil, con formaciones rocosas y pesca artesanal.', 'Pueblo pesquero y playa del Pacífico cercana a Pochomil, con formaciones rocosas y pesca artesanal.', 11.78467, -86.51594, 'exact', true, null, 'verified', '2026-10-05'::timestamptz, 'Mapa Nacional de Turismo / GeoNames', 'https://www.mapanicaragua.com/sol-y-playa/', 'other', '{"activities":"Baño, compra de mariscos, caminata y fotografía.","modality":"Playas","facts":"Pueblo pesquero y playa del Pacífico cercana a Pochomil, con formaciones rocosas y pesca artesanal."}'::jsonb, true, 'territories-data.js', 'managua::playa masachapa', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-laguna-de-apoyeque', 'laguna-de-apoyeque', 'Laguna de Apoyeque', 'laguna', null, 'Laguna o lago · Senderismo de aventura', 'fa-water', 'managua', 'managua__mateare', null, 'Laguna en la caldera del volcán Apoyeque, rodeada de vegetación y paisajes volcánicos; el acceso requiere planificación y guía local.', 'Laguna en la caldera del volcán Apoyeque, rodeada de vegetación y paisajes volcánicos; el acceso requiere planificación y guía local.', 12.244931, -86.341497, 'centroid', false, null, 'verified', '2026-10-05'::timestamptz, 'Visit Nicaragua (catálogo de naturaleza 2026)', null, 'other', '{"activities":"Senderismo de aventura, geoturismo y observación panorámica.","facts":"Laguna en la caldera del volcán Apoyeque, rodeada de vegetación y paisajes volcánicos; el acceso requiere planificación y guía local."}'::jsonb, true, 'territories-data.js', 'managua::laguna de apoyeque', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-lago-xolotlan-lago-de-managua', 'lago-xolotlan-lago-de-managua', 'Lago Xolotlán (Lago de Managua)', 'laguna', null, 'Laguna o lago · Paseos lacustres autorizados', 'fa-water', 'managua', 'managua__managua', null, 'Segundo gran lago de Nicaragua, ligado al paisaje de Managua y a la cadena volcánica del Pacífico.', 'Segundo gran lago de Nicaragua, ligado al paisaje de Managua y a la cadena volcánica del Pacífico.', 12.339722, -86.350556, 'centroid', false, null, 'verified', '2026-10-05'::timestamptz, 'Mapa Nacional de Turismo / Geographic Names (catálogo de naturaleza 2026)', null, 'other', '{"activities":"Paseos lacustres autorizados, fotografía y paisaje urbano y volcánico.","facts":"Segundo gran lago de Nicaragua, ligado al paisaje de Managua y a la cadena volcánica del Pacífico."}'::jsonb, true, 'territories-data.js', 'managua::lago xolotlan lago de managua', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-reserva-natural-peninsula-de-chiltepe', 'reserva-natural-peninsula-de-chiltepe', 'Reserva Natural Península de Chiltepe', 'reserva', null, 'Reserva natural · Senderismo', 'fa-tree', 'managua', 'managua__mateare', null, 'Área protegida cercana a Managua que integra las calderas y lagunas de Apoyeque y Xiloá.', 'Área protegida cercana a Managua que integra las calderas y lagunas de Apoyeque y Xiloá.', 12.24928, -86.35086, 'centroid', false, null, 'verified', '2026-10-05'::timestamptz, 'Mapa Nacional de Turismo (catálogo de naturaleza 2026)', null, 'other', '{"activities":"Senderismo, geoturismo y paisaje volcánico y lacustre.","facts":"Área protegida cercana a Managua que integra las calderas y lagunas de Apoyeque y Xiloá."}'::jsonb, true, 'territories-data.js', 'managua::reserva natural peninsula de chiltepe', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-diriamba-y-basilica-de-san-sebastian', 'diriamba-y-basilica-de-san-sebastian', 'Diriamba y Basílica de San Sebastián', 'sitio_historico', null, 'El Güegüense, patrimonio, fiestas, arquitectura y fotografía', 'fa-church', 'carazo', null, null, 'Ciudad de Carazo donde, en las fiestas de San Sebastián, el Güegüense, el Toro Huaco y el Gigante bailan en las calles.', 'Ciudad de Carazo donde, en las fiestas de San Sebastián, el Güegüense, el Toro Huaco y el Gigante bailan en las calles.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'carazo::diriamba y basilica de san sebastian', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-jinotepe-y-parroquia-santiago', 'jinotepe-y-parroquia-santiago', 'Jinotepe y Parroquia Santiago', 'centro_cultural', null, 'Arquitectura, gastronomía, cultura, parques y servicios', 'fa-building-columns', 'carazo', null, null, 'Cabecera de Carazo con su parroquia de Santiago y fiestas patronales con bailes tradicionales y procesiones.', 'Cabecera de Carazo con su parroquia de Santiago y fiestas patronales con bailes tradicionales y procesiones.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'carazo::jinotepe y parroquia santiago', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-la-boquita', 'la-boquita', 'La Boquita', 'playa', null, 'Playa, gastronomía marina, familia y atardeceres', 'fa-umbrella-beach', 'carazo', 'carazo__diriamba', null, 'Balneario del Pacífico de Carazo con comedores de mariscos, pescadores y atardeceres.', 'Balneario del Pacífico de Carazo con comedores de mariscos, pescadores y atardeceres.', 11.67825, -86.38236, 'exact', true, null, 'verified', '2026-10-05'::timestamptz, 'Visit Nicaragua / GeoNames', 'https://www.visitanicaragua.com/atractivos/playas/', 'other', '{"activities":"Baño, descanso, gastronomía y atardecer.","facts":"Balneario del Pacífico en el municipio de Diriamba, Carazo, con acceso carretero y servicios turísticos."}'::jsonb, true, 'territories-data.js', 'carazo::la boquita', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-casares', 'casares', 'Casares', 'turismo_comunitario', null, 'Pesca artesanal, comunidad, restaurantes y paisaje costero', 'fa-fish', 'carazo', null, null, 'Comunidad de pescadores en la costa de Carazo, con playa tranquila y comida de mar.', 'Comunidad de pescadores en la costa de Carazo, con playa tranquila y comida de mar.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'carazo::casares', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-huehuete-y-el-tamarindo', 'huehuete-y-el-tamarindo', 'Huehuete y El Tamarindo', 'atractivo', null, 'Playas, recreación y costa caraceña', 'fa-water', 'carazo', null, null, 'Playas de la costa de Carazo con pesca artesanal y descanso frente al mar.', 'Playas de la costa de Carazo con pesca artesanal y descanso frente al mar.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'carazo::huehuete y el tamarindo', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-centro-ecoturistico-la-maquina', 'centro-ecoturistico-la-maquina', 'Centro Ecoturístico La Máquina', 'cascada', null, 'Cascadas, senderos y bosque seco', 'fa-water', 'carazo', null, null, 'Área natural en Carazo con ríos, pozas, cascadas y senderos entre bosque seco.', 'Área natural en Carazo con ríos, pozas, cascadas y senderos entre bosque seco.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'carazo::centro ecoturistico la maquina', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-refugio-rio-escalante-chacocente', 'refugio-rio-escalante-chacocente', 'Refugio Río Escalante–Chacocente', 'rio', null, 'Senderismo, fauna y conservación regulada de tortugas', 'fa-shield-heart', 'carazo', null, null, 'Playa protegida y bosque seco donde desovan tortugas marinas.', 'Playa protegida y bosque seco donde desovan tortugas marinas.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'carazo::refugio rio escalante chacocente', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-reserva-silvestre-privada-tonantzin', 'reserva-silvestre-privada-tonantzin', 'Reserva Silvestre Privada Tonantzin', 'reserva', null, 'Senderismo, aves, petroglifos, agricultura y educación ambiental', 'fa-leaf', 'carazo', null, null, 'Reserva privada en Carazo con senderos, aves, petroglifos y prácticas agrícolas sostenibles.', 'Reserva privada en Carazo con senderos, aves, petroglifos y prácticas agrícolas sostenibles.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'carazo::reserva silvestre privada tonantzin', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-reserva-silvestre-privada-franin', 'reserva-silvestre-privada-franin', 'Reserva Silvestre Privada FRANIN', 'reserva', null, 'Senderismo, observación de aves y cabalgatas', 'fa-feather', 'carazo', null, null, 'Reserva privada de bosque para senderismo, observación de aves y cabalgatas.', 'Reserva privada de bosque para senderismo, observación de aves y cabalgatas.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'carazo::reserva silvestre privada franin', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-centro-ecoturistico-loma-de-viento', 'centro-ecoturistico-loma-de-viento', 'Centro Ecoturístico Loma de Viento', 'turismo_rural', null, 'Senderismo, cabalgatas, jardín botánico y turismo rural', 'fa-mountain-sun', 'carazo', null, null, 'Espacio de turismo rural en Carazo con senderos, cabalgatas y jardín botánico.', 'Espacio de turismo rural en Carazo con senderos, cabalgatas y jardín botánico.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'carazo::centro ecoturistico loma de viento', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-dolores-y-fincas-cafetaleras', 'dolores-y-fincas-cafetaleras', 'Dolores y fincas cafetaleras', 'agroturismo', null, 'Ciclismo, agroturismo, café y producción local', 'fa-bicycle', 'carazo', null, null, 'Municipio de la meseta de Carazo con fincas de café, rutas en bicicleta y producción local.', 'Municipio de la meseta de Carazo con fincas de café, rutas en bicicleta y producción local.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'carazo::dolores y fincas cafetaleras', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-reserva-silvestre-privada-la-makina', 'reserva-silvestre-privada-la-makina', 'Reserva Silvestre Privada La Mákina', 'reserva', null, 'Turismo de naturaleza · Observación de aves', 'fa-tree', 'carazo', null, null, 'Santuario de biodiversidad camino a La Boquita con cascada, kayak, canopy y educación ambiental.', 'Santuario de biodiversidad camino a La Boquita con cascada, kayak, canopy y educación ambiental.', null, null, 'missing', false, 'Km 58 carretera Diriamba–playa La Boquita.', 'verified', '2026-10-05'::timestamptz, 'INTUR · Catálogo de Iniciativas de Turismo Rural y Comunitario (2026)', null, 'other', '{"activities":"Observación de aves, senderismo, cascada, kayak, camping y canopy.","services":"Alimentos, bebidas, diversiones y camping.","hours":"Sábado y domingo 8:00 a. m.–6:00 p. m.; lunes a viernes 9:00 a. m.–4:00 p. m. con reservación.","modality":"Turismo de naturaleza","facts":"Santuario de biodiversidad camino a La Boquita con cascada, kayak, canopy y educación ambiental.","map":"https://www.google.com/maps/d/u/0/edit?mid=1NA9gXfePzc4s9Vc-WxMBgUbKa641_No&usp=sharing","contact_note":"Contacto publicado por INTUR en el catálogo 2026; confirmar antes de viajar."}'::jsonb, true, 'territories-data.js', 'carazo::reserva silvestre privada la makina', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-cordillera-de-amerrisque', 'cordillera-de-amerrisque', 'Cordillera de Amerrisque', 'atractivo', null, 'Serranía Mística & Trekking', 'fa-mountain', 'chontales', null, null, 'Serranía de Chontales con montañas, ríos y miradores sobre la llanura ganadera.', 'Serranía de Chontales con montañas, ríos y miradores sobre la llanura ganadera.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'chontales::cordillera de amerrisque', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-museo-arqueologico-gregorio-aguilar-barea', 'museo-arqueologico-gregorio-aguilar-barea', 'Museo Arqueológico Gregorio Aguilar Barea', 'museo', null, 'Estatuas de Piedra Prehispánicas', 'fa-landmark', 'chontales', null, null, 'Museo de Juigalpa con una colección de estatuas prehispánicas de piedra de la región chontal.', 'Museo de Juigalpa con una colección de estatuas prehispánicas de piedra de la región chontal.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'chontales::museo arqueologico gregorio aguilar barea', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-zoologico-thomas-belt-de-juigalpa', 'zoologico-thomas-belt-de-juigalpa', 'Zoológico Thomas Belt de Juigalpa', 'atractivo', null, 'Fauna Silvestre & Puma Albino', 'fa-paw', 'chontales', null, null, 'Pequeño zoológico de Juigalpa con fauna nicaragüense, dedicado a la educación ambiental de familias y escuelas.', 'Pequeño zoológico de Juigalpa con fauna nicaragüense, dedicado a la educación ambiental de familias y escuelas.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'chontales::zoologico thomas belt de juigalpa', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-puerto-diaz-lago-cocibolca', 'puerto-diaz-lago-cocibolca', 'Puerto Díaz & Lago Cocibolca', 'lago', null, 'Pueblo de Pescadores', 'fa-anchor', 'chontales', null, null, 'Pueblo de pescadores a orillas del Cocibolca, con lanchas, pescado fresco y atardeceres sobre el lago.', 'Pueblo de pescadores a orillas del Cocibolca, con lanchas, pescado fresco y atardeceres sobre el lago.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'chontales::puerto diaz lago cocibolca', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-piedras-pintadas-de-villa-sandino', 'piedras-pintadas-de-villa-sandino', 'Piedras Pintadas de Villa Sandino', 'sitio_historico', null, 'Petroglifos Sagrados', 'fa-palette', 'chontales', null, null, 'Rocas con petroglifos precolombinos en Villa Sandino, parte de la memoria ancestral de Chontales.', 'Rocas con petroglifos precolombinos en Villa Sandino, parte de la memoria ancestral de Chontales.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'chontales::piedras pintadas de villa sandino', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-piramides-de-garro-grande', 'piramides-de-garro-grande', 'Pirámides de Garro Grande', 'sitio_historico', null, 'Arqueología y memoria precolombina', 'fa-monument', 'chontales', null, null, 'Sitio arqueológico con montículos y vestigios precolombinos en Chontales.', 'Sitio arqueológico con montículos y vestigios precolombinos en Chontales.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'chontales::piramides de garro grande', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-archipielago-el-nancital', 'archipielago-el-nancital', 'Archipiélago El Nancital', 'isla', null, '27 islas, aves, pesca, navegación y atardeceres', 'fa-ship', 'chontales', null, null, 'Grupo de islas del Cocibolca frente a Chontales, con aves, pesca, navegación y atardeceres.', 'Grupo de islas del Cocibolca frente a Chontales, con aves, pesca, navegación y atardeceres.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'chontales::archipielago el nancital', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-cerro-y-cuevas-las-ventanas', 'cerro-y-cuevas-las-ventanas', 'Cerro y Cuevas Las Ventanas', 'cueva', null, 'Senderismo, espeleología y geología en Acoyapa', 'fa-mountain-sun', 'chontales', null, null, 'Cerro con cuevas y formaciones rocosas en Acoyapa, para senderismo y espeleología guiada.', 'Cerro con cuevas y formaciones rocosas en Acoyapa, para senderismo y espeleología guiada.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'chontales::cerro y cuevas las ventanas', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-cascadas-de-chontales', 'cascadas-de-chontales', 'Cascadas de Chontales', 'cascada', null, 'El Corozo, El Silencio, El Chancho, Hato Grande y Kilona', 'fa-water', 'chontales', null, null, 'Caídas de agua como El Corozo, El Silencio, El Chancho, Hato Grande y Kilona, entre ganadería y bosque.', 'Caídas de agua como El Corozo, El Silencio, El Chancho, Hato Grande y Kilona, entre ganadería y bosque.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'chontales::cascadas de chontales', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-salto-y-cueva-la-oropendola', 'salto-y-cueva-la-oropendola', 'Salto y Cueva La Oropéndola', 'cascada', null, 'Senderismo y naturaleza en Santo Tomás', 'fa-person-hiking', 'chontales', null, null, 'Cascada y cueva en Santo Tomás, nombradas por las aves oropéndolas que anidan en la zona.', 'Cascada y cueva en Santo Tomás, nombradas por las aves oropéndolas que anidan en la zona.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'chontales::salto y cueva la oropendola', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-aguas-calientes-e-isla-arena', 'aguas-calientes-e-isla-arena', 'Aguas Calientes e Isla Arena', 'isla', null, 'Geología, lancha, balneario y campamento', 'fa-hot-tub-person', 'chontales', null, null, 'Aguas termales a orillas del Cocibolca y una isla de arena a la que se llega en lancha.', 'Aguas termales a orillas del Cocibolca y una isla de arena a la que se llega en lancha.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'chontales::aguas calientes e isla arena', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-finca-los-angeles', 'finca-los-angeles', 'Finca Los Ángeles', 'agroturismo', null, 'Agroturismo · Cabalgatas', 'fa-seedling', 'chontales', null, null, 'Propiedad agropecuaria de Juigalpa entre serranías, llanos, bosques y arroyos, abierta a la vida de campo.', 'Propiedad agropecuaria de Juigalpa entre serranías, llanos, bosques y arroyos, abierta a la vida de campo.', null, null, 'missing', false, 'Km 147 carretera Juigalpa–El Rama.', 'verified', '2026-10-05'::timestamptz, 'INTUR · Catálogo de Iniciativas de Turismo Rural y Comunitario (2026)', null, 'other', '{"activities":"Cabalgatas, senderismo, actividades agropecuarias y observación de flora y fauna.","services":"Alimentos, bebidas, hospedería, piscinas y camping.","hours":"Lunes a domingo, 6:00 a. m.–8:00 p. m.","modality":"Agroturismo","facts":"Propiedad agropecuaria de Juigalpa entre serranías, llanos, bosques y arroyos, abierta a la vida de campo.","map":"https://www.google.com/maps/d/u/0/edit?mid=1cZcB0bn7mNuAhu3NaY23pYVq66DrGn0&usp=sharing","contact_note":"Contacto publicado por INTUR en el catálogo 2026; confirmar antes de viajar."}'::jsonb, true, 'territories-data.js', 'chontales::finca los angeles', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-centro-historico-calles-escalonadas-de-boaco', 'centro-historico-calles-escalonadas-de-boaco', 'Centro Histórico & Calles Escalonadas de Boaco', 'atractivo', null, 'Arquitectura Topográfica', 'fa-city', 'boaco', null, null, 'La ''ciudad de dos pisos'': parte alta y parte baja unidas por calles en pendiente con vista al valle.', 'La ''ciudad de dos pisos'': parte alta y parte baja unidas por calles en pendiente con vista al valle.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'boaco::centro historico calles escalonadas de boaco', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-cerro-de-la-vieja-cerro-alegre', 'cerro-de-la-vieja-cerro-alegre', 'Cerro de la Vieja & Cerro Alegre', 'cerro', null, 'Senderismo & Mitos', 'fa-mountain', 'boaco', null, null, 'Cerros de Boaco con senderos, miradores y leyendas de la tradición oral local.', 'Cerros de Boaco con senderos, miradores y leyendas de la tradición oral local.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'boaco::cerro de la vieja cerro alegre', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-rio-fonseca-balnearios-naturales', 'rio-fonseca-balnearios-naturales', 'Río Fonseca & Balnearios Naturales', 'rio', null, 'Pozas de Montaña', 'fa-water', 'boaco', null, null, 'Río de montaña con pozas naturales para bañarse cerca de la ciudad de Boaco.', 'Río de montaña con pozas naturales para bañarse cerca de la ciudad de Boaco.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'boaco::rio fonseca balnearios naturales', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-pueblo-ganadero-de-camoapa', 'pueblo-ganadero-de-camoapa', 'Pueblo Ganadero de Camoapa', 'atractivo', null, 'Sombreros de Pita & Lácteos', 'fa-hat-cowboy', 'boaco', null, null, 'Municipio ganadero de Boaco, conocido por sus artesanías de palma (pita) y la vida de hacienda.', 'Municipio ganadero de Boaco, conocido por sus artesanías de palma (pita) y la vida de hacienda.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'boaco::pueblo ganadero de camoapa', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-mirador-el-faro', 'mirador-el-faro', 'Mirador El Faro', 'mirador', null, 'Panorámica de la Ciudad', 'fa-eye', 'boaco', null, null, 'Mirador sobre la ''ciudad de dos pisos'', con vista panorámica de Boaco.', 'Mirador sobre la ''ciudad de dos pisos'', con vista panorámica de Boaco.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'boaco::mirador el faro', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-reserva-mombachito-cerro-la-vieja', 'reserva-mombachito-cerro-la-vieja', 'Reserva Mombachito–Cerro La Vieja', 'reserva', null, 'Bosque, senderismo, agua y turismo rural', 'fa-tree', 'boaco', null, null, 'Reserva de bosque con fuentes de agua, senderos y turismo rural en Boaco.', 'Reserva de bosque con fuentes de agua, senderos y turismo rural en Boaco.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'boaco::reserva mombachito cerro la vieja', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-reserva-natural-filas-de-masigue', 'reserva-natural-filas-de-masigue', 'Reserva Natural Filas de Masigüe', 'reserva', null, 'Bosque húmedo, aves y conservación del agua', 'fa-feather', 'boaco', null, null, 'Serranía de bosque húmedo protegida por su valor para el agua y las aves.', 'Serranía de bosque húmedo protegida por su valor para el agua y las aves.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'boaco::reserva natural filas de masigue', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-comunidad-las-lagunas', 'comunidad-las-lagunas', 'Comunidad Las Lagunas', 'turismo_comunitario', null, 'Petrograbados, senderismo, gastronomía y miradores', 'fa-monument', 'boaco', null, null, 'Comunidad rural de Boaco con petrograbados, senderos, cocina local y miradores.', 'Comunidad rural de Boaco con petrograbados, senderos, cocina local y miradores.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'boaco::comunidad las lagunas', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-cerros-y-cascadas-de-santa-lucia', 'cerros-y-cascadas-de-santa-lucia', 'Cerros y cascadas de Santa Lucía', 'cascada', null, 'La Cruz, Santo Domingo, Peña Labrada y Salto Las Américas', 'fa-mountain-sun', 'boaco', null, null, 'Pueblo rodeado de montañas, con cerros y cascadas ideales para caminatas y turismo rural.', 'Pueblo rodeado de montañas, con cerros y cascadas ideales para caminatas y turismo rural.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'boaco::cerros y cascadas de santa lucia', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-cueva-la-cocinera-y-finca-el-tamarindo', 'cueva-la-cocinera-y-finca-el-tamarindo', 'Cueva La Cocinera y Finca El Tamarindo', 'cueva', null, 'Aventura, café, orquídeas y cactus', 'fa-person-hiking', 'boaco', null, null, 'Cueva para aventura guiada y una finca con café, orquídeas y cactus.', 'Cueva para aventura guiada y una finca con café, orquídeas y cactus.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'boaco::cueva la cocinera y finca el tamarindo', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
commit;
