-- BAQUEANO · Importación territories-data.js → Supabase · parte 05 de 07
-- Generado desde supabase/imports/20261005_territories_import.sql. Ejecutar las partes EN ORDEN en el SQL Editor.
-- Idempotente: si una parte se ejecuta dos veces, no duplica (ON CONFLICT).
begin;
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-salto-la-chorrera', 'salto-la-chorrera', 'Salto La Chorrera', 'cascada', null, 'Senderismo, aves, cafetales y miradores', 'fa-water', 'boaco', null, null, 'Cascada entre cafetales con senderos, aves y miradores.', 'Cascada entre cafetales con senderos, aves y miradores.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'boaco::salto la chorrera', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-finca-poza-redonda-azul', 'finca-poza-redonda-azul', 'Finca Poza Redonda Azul', 'cerro', null, 'Turismo rural · Senderismo al cerro El Diamante', 'fa-house-chimney', 'boaco', null, null, 'Finca agropecuaria sostenible en Teustepe con ganadería, granos, cítricos y una poza natural como atractivo principal.', 'Finca agropecuaria sostenible en Teustepe con ganadería, granos, cítricos y una poza natural como atractivo principal.', null, null, 'missing', false, 'Teustepe, carretera a San José de los Remates, km 82.5 a mano izquierda, 1½ km comunidad San Diego, portón de madera finca El Arbolito.', 'verified', '2026-10-05'::timestamptz, 'INTUR · Catálogo de Iniciativas de Turismo Rural y Comunitario (2026)', null, 'other', '{"activities":"Senderismo al cerro El Diamante y ojo de agua, actividades agropecuarias, fogatas literarias y comida tradicional.","services":"Alimentación y bebidas, cabañas, piscina y eventos familiares.","hours":"Lunes a domingo, 8:00 a. m.–7:00 p. m. (huéspedes hasta 10:00 p. m.).","modality":"Turismo rural","facts":"Finca agropecuaria sostenible en Teustepe con ganadería, granos, cítricos y una poza natural como atractivo principal.","map":"https://www.google.com/maps/d/u/0/edit?mid=1a7sf0EOmz7mutO0b5cKaJ33QapdemHw&usp=sharing","contact_note":"Contacto publicado por INTUR en el catálogo 2026; confirmar antes de viajar."}'::jsonb, true, 'territories-data.js', 'boaco::finca poza redonda azul', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-cerro-mogoton-2-107-msnm', 'cerro-mogoton-2-107-msnm', 'Cerro Mogotón (2,107 msnm)', 'volcan', null, 'Cima Más Alta de Nicaragua', 'fa-mountain', 'nueva_segovia', null, 'Frontera Nicaragua-Honduras', 'El punto más alto de Nicaragua, en una reserva natural de pinares y bosque nuboso en la frontera norte.', 'El punto más alto de Nicaragua, en una reserva natural de pinares y bosque nuboso en la frontera norte.', 13.763062, -86.399059, 'reference', false, null, 'verified', '2026-10-05'::timestamptz, 'GeoNames (catálogo de naturaleza 2026)', null, 'other', '{"activities":"Montañismo y senderismo especializado con guía local.","facts":"Pico de 2,107 metros registrado por GeoNames, considerado el punto de mayor elevación del territorio nicaragüense."}'::jsonb, true, 'territories-data.js', 'nueva-segovia::cerro mogoton 2 107 msnm', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-santuario-de-la-virgen-de-la-piedra-dipilto', 'santuario-de-la-virgen-de-la-piedra-dipilto', 'Santuario de la Virgen de la Piedra (Dipilto)', 'rio', null, 'Sitio Religioso & Río', 'fa-church', 'nueva_segovia', null, null, 'Santuario en una cueva de piedra en Dipilto, centro de peregrinación entre pinares y fincas de café.', 'Santuario en una cueva de piedra en Dipilto, centro de peregrinación entre pinares y fincas de café.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'nueva-segovia::santuario de la virgen de la piedra dipilto', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-aguas-termales-de-macuelizo-delia', 'aguas-termales-de-macuelizo-delia', 'Aguas Termales de Macuelizo & Delia', 'atractivo', null, 'Termalismo Terapéutico', 'fa-hot-tub-person', 'nueva_segovia', null, null, 'Fuentes de aguas termales en el municipio de Macuelizo, usadas como baños de descanso.', 'Fuentes de aguas termales en el municipio de Macuelizo, usadas como baños de descanso.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'nueva-segovia::aguas termales de macuelizo delia', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-valle-fertil-de-jalapa', 'valle-fertil-de-jalapa', 'Valle Fértil de Jalapa', 'atractivo', null, 'Granero de Maíz & Tabaco', 'fa-seedling', 'nueva_segovia', null, null, 'Valle agrícola del norte de Nueva Segovia, conocido por el maíz, el tabaco y el clima fresco.', 'Valle agrícola del norte de Nueva Segovia, conocido por el maíz, el tabaco y el clima fresco.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'nueva-segovia::valle fertil de jalapa', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-ocotal-colonial-casa-de-la-cultura', 'ocotal-colonial-casa-de-la-cultura', 'Ocotal Colonial & Casa de la Cultura', 'sitio_historico', null, 'Historia & Música', 'fa-landmark', 'nueva_segovia', null, null, 'Cabecera de Nueva Segovia con su parque central, catedral y casa de la cultura, puerta hacia los pinares del norte.', 'Cabecera de Nueva Segovia con su parque central, catedral y casa de la cultura, puerta hacia los pinares del norte.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'nueva-segovia::ocotal colonial casa de la cultura', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-ciudad-antigua', 'ciudad-antigua', 'Ciudad Antigua', 'turismo_comunitario', null, 'Ruta colonial, iglesias, arquitectura y comunidades', 'fa-building-columns', 'nueva_segovia', null, null, 'Uno de los pueblos coloniales más antiguos de Nicaragua, con su iglesia histórica y calles tradicionales.', 'Uno de los pueblos coloniales más antiguos de Nicaragua, con su iglesia histórica y calles tradicionales.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'nueva-segovia::ciudad antigua', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-cerro-las-tres-senoritas', 'cerro-las-tres-senoritas', 'Cerro Las Tres Señoritas', 'cerro', null, 'Senderismo y vistas panorámicas cerca de Ocotal', 'fa-mountain-sun', 'nueva_segovia', null, null, 'Cerro cercano a Ocotal con senderos y vistas panorámicas del valle.', 'Cerro cercano a Ocotal con senderos y vistas panorámicas del valle.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'nueva-segovia::cerro las tres senoritas', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-cruz-de-la-fe', 'cruz-de-la-fe', 'Cruz de la Fe', 'mirador', null, 'Mirador y recorrido religioso en Dipilto', 'fa-cross', 'nueva_segovia', null, null, 'Mirador con una gran cruz en Dipilto, destino de recorridos religiosos y paisaje de pinares.', 'Mirador con una gran cruz en Dipilto, destino de recorridos religiosos y paisaje de pinares.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'nueva-segovia::cruz de la fe', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-artesanias-de-mozonte', 'artesanias-de-mozonte', 'Artesanías de Mozonte', 'centro_cultural', null, 'Barro, talleres y compra directa a creadores', 'fa-hands', 'nueva_segovia', null, null, 'Talleres de cerámica de barro en Mozonte, comunidad de tradición indígena; se compra directo a las artesanas.', 'Talleres de cerámica de barro en Mozonte, comunidad de tradición indígena; se compra directo a las artesanas.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'nueva-segovia::artesanias de mozonte', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-salto-el-rosario', 'salto-el-rosario', 'Salto El Rosario', 'cascada', null, 'Cascada, senderismo, bosque y comunidades de Murra', 'fa-water', 'nueva_segovia', null, null, 'Cascada en el municipio de Murra, rodeada de bosque y comunidades cafetaleras.', 'Cascada en el municipio de Murra, rodeada de bosque y comunidades cafetaleras.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'nueva-segovia::salto el rosario', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-aguas-termales-don-alfonso', 'aguas-termales-don-alfonso', 'Aguas termales Don Alfonso', 'atractivo', null, 'Naturaleza y bienestar en San Fernando', 'fa-hot-tub-person', 'nueva_segovia', null, null, 'Aguas termales naturales en San Fernando para descanso y bienestar.', 'Aguas termales naturales en San Fernando para descanso y bienestar.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'nueva-segovia::aguas termales don alfonso', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-fortaleza-de-la-inmaculada-concepcion-el-castillo', 'fortaleza-de-la-inmaculada-concepcion-el-castillo', 'Fortaleza de la Inmaculada Concepción (El Castillo)', 'sitio_historico', null, 'Monumento Nacional Siglo XVII', 'fa-chess-rook', 'rio_san_juan', null, null, 'Fortaleza colonial sobre los raudales del río San Juan, construida para defender la ruta hacia el Caribe.', 'Fortaleza colonial sobre los raudales del río San Juan, construida para defender la ruta hacia el Caribe.', null, null, 'missing', false, null, 'verified', '2026-10-05'::timestamptz, 'Mapa Nacional de Turismo', 'https://www.mapanicaragua.com/arquitectura-de-el-castillo/', 'other', '{"facts":"Fortaleza colonial construida entre 1672 y 1675 para proteger la ruta del Río San Juan; es Patrimonio Cultural de la Nación y uno de los principales valores históricos del municipio.","price_note":{"text":"Consultar la tarifa vigente en el sitio.","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, true, 'territories-data.js', 'rio-san-juan::fortaleza de la inmaculada concepcion el castillo', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-reserva-biologica-indio-maiz', 'reserva-biologica-indio-maiz', 'Reserva Biológica Indio Maíz', 'parque', null, 'Selva Virgen & Jaguares', 'fa-tree', 'rio_san_juan', null, 'Sureste de Nicaragua', 'Una de las selvas mejor conservadas de Centroamérica; se visita por sus bordes con guías autorizados.', 'Una de las selvas mejor conservadas de Centroamérica; se visita por sus bordes con guías autorizados.', 12.91355, -84.67987, 'reference', false, null, 'verified', '2026-10-05'::timestamptz, 'MARENA / OpenStreetMap (catálogo de naturaleza 2026)', null, 'other', '{"activities":"Conservación, investigación y turismo de naturaleza regulado en sectores autorizados.","facts":"Gran reserva de bosque húmedo tropical en el sureste de Nicaragua, integrada a la Reserva de Biosfera Río San Juan."}'::jsonb, true, 'territories-data.js', 'rio-san-juan::reserva biologica indio maiz', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-archipielago-de-solentiname', 'archipielago-de-solentiname', 'Archipiélago de Solentiname', 'isla', null, 'Islas de Pintores Primitivistas', 'fa-palette', 'rio_san_juan', 'rio_san_juan__san_carlos', null, 'Islas de pintores y talladores de madera de balsa en el Cocibolca.', 'Islas de pintores y talladores de madera de balsa en el Cocibolca.', 11.17283, -84.99081, 'approximate', false, null, 'verified', '2026-10-05'::timestamptz, 'Visit Nicaragua / GeoNames', 'https://www.visitanicaragua.com/atractivos/islas/', 'other', '{"activities":"Arte primitivista, turismo comunitario, aves, lancha y cultura.","facts":"Conjunto insular del Lago Cocibolca reconocido por su naturaleza, sus comunidades y su tradición artística."}'::jsonb, true, 'territories-data.js', 'rio-san-juan::archipielago de solentiname', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-humedales-de-san-carlos-malecon', 'humedales-de-san-carlos-malecon', 'Humedales de San Carlos & Malecón', 'lago', null, 'Confluencia Lago-Río', 'fa-water', 'rio_san_juan', null, null, 'Malecón de San Carlos donde se unen el lago y el río San Juan, rodeado de humedales con aves.', 'Malecón de San Carlos donde se unen el lago y el río San Juan, rodeado de humedales con aves.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'rio-san-juan::humedales de san carlos malecon', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-san-juan-de-nicaragua-greytown', 'san-juan-de-nicaragua-greytown', 'San Juan de Nicaragua (Greytown)', 'atractivo', null, 'Salida al Caribe & Cementerios Británicos', 'fa-anchor', 'rio_san_juan', null, null, 'Poblado en la desembocadura del río San Juan al Caribe, con historia del tránsito interoceánico.', 'Poblado en la desembocadura del río San Juan al Caribe, con historia del tránsito interoceánico.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'rio-san-juan::san juan de nicaragua greytown', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-san-carlos-y-su-circuito-urbano', 'san-carlos-y-su-circuito-urbano', 'San Carlos y su circuito urbano', 'museo', null, 'Malecón, fortaleza, centro cultural, museo y puerto', 'fa-city', 'rio_san_juan', null, null, 'Cabecera de Río San Juan, con malecón, fortaleza, centro cultural y el puerto de salida hacia el río y Solentiname.', 'Cabecera de Río San Juan, con malecón, fortaleza, centro cultural y el puerto de salida hacia el río y Solentiname.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'rio-san-juan::san carlos y su circuito urbano', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-bartola', 'bartola', 'Bartola', 'atractivo', null, 'Senderismo, cacao, fauna, cabalgatas y aviturismo', 'fa-tree', 'rio_san_juan', null, null, 'Comunidad a orillas del río San Juan, junto a la Reserva Indio Maíz, con senderos, cacao y fauna.', 'Comunidad a orillas del río San Juan, junto a la Reserva Indio Maíz, con senderos, cacao y fauna.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'rio-san-juan::bartola', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-refugio-de-vida-silvestre-rio-san-juan', 'refugio-de-vida-silvestre-rio-san-juan', 'Refugio de Vida Silvestre Río San Juan', 'rio', null, 'Bosque húmedo, humedales y biodiversidad', 'fa-feather', 'rio_san_juan', null, null, 'Refugio a lo largo del río San Juan con selva, humedales y fauna, recorrido en lancha.', 'Refugio a lo largo del río San Juan con selva, humedales y fauna, recorrido en lancha.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'rio-san-juan::refugio de vida silvestre rio san juan', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-antigua-greytown', 'antigua-greytown', 'Antigua Greytown', 'sitio_historico', null, 'Cementerios, lagunas, caños y memoria del tránsito', 'fa-landmark', 'rio_san_juan', null, null, 'Sitio histórico con cementerios de la época del tránsito, lagunas y caños en la costa caribe de Río San Juan.', 'Sitio histórico con cementerios de la época del tránsito, lagunas y caños en la costa caribe de Río San Juan.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'rio-san-juan::antigua greytown', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-refugio-los-guatuzos', 'refugio-los-guatuzos', 'Refugio Los Guatuzos', 'reserva', null, 'Kayak, aves, fauna, bosque y senderos', 'fa-binoculars', 'rio_san_juan', null, null, 'Humedales y ríos con aves, caimanes y monos al sur del Cocibolca.', 'Humedales y ríos con aves, caimanes y monos al sur del Cocibolca.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'rio-san-juan::refugio los guatuzos', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-muelle-de-san-miguelito-y-chocoyolandia', 'muelle-de-san-miguelito-y-chocoyolandia', 'Muelle de San Miguelito y Chocoyolandia', 'atractivo', null, 'Atardeceres, gastronomía y balneario lacustre', 'fa-water', 'rio_san_juan', null, null, 'Muelle del Cocibolca con atardeceres, comida local y balneario lacustre.', 'Muelle del Cocibolca con atardeceres, comida local y balneario lacustre.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'rio-san-juan::muelle de san miguelito y chocoyolandia', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-hostal-buen-amigo', 'hostal-buen-amigo', 'Hostal Buen Amigo', 'turismo_comunitario', null, 'Turismo rural y comunitario · Caminatas', 'fa-people-group', 'rio_san_juan', null, null, 'Hostal en la isla Mancarrón, Solentiname, para descansar y conocer las tradiciones artísticas del archipiélago.', 'Hostal en la isla Mancarrón, Solentiname, para descansar y conocer las tradiciones artísticas del archipiélago.', null, null, 'missing', false, 'Isla Mancarrón, del cuadro municipal 100 m al sur.', 'verified', '2026-10-05'::timestamptz, 'INTUR · Catálogo de Iniciativas de Turismo Rural y Comunitario (2026)', null, 'other', '{"activities":"Caminatas, paseos en bote, talleres de artesanía y cultura local.","services":"Alimentos, bebidas, hospedería, piscinas y camping.","hours":"Lunes a domingo, 7:00 a. m.–8:00 p. m.","modality":"Turismo rural y comunitario","facts":"Hostal en la isla Mancarrón, Solentiname, para descansar y conocer las tradiciones artísticas del archipiélago.","map":"https://www.google.com/maps/d/u/0/edit?mid=1JVmXW9SioVGQQs52ImHU4cGQBICHsno&usp=sharing","contact_note":"Contacto publicado por INTUR en el catálogo 2026; confirmar antes de viajar."}'::jsonb, true, 'territories-data.js', 'rio-san-juan::hostal buen amigo', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-albergue-caiman-los-guatuzos', 'albergue-caiman-los-guatuzos', 'Albergue Caimán (Los Guatuzos)', 'turismo_comunitario', null, 'Turismo rural y comunitario · Observación de flora', 'fa-people-group', 'rio_san_juan', null, null, 'Albergue ecológico a orillas de los humedales del río Papaturro, en el Refugio de Vida Silvestre Los Guatuzos.', 'Albergue ecológico a orillas de los humedales del río Papaturro, en el Refugio de Vida Silvestre Los Guatuzos.', null, null, 'missing', false, 'Comunidad Papaturro, del muelle municipal 100 m al norte, San Carlos.', 'verified', '2026-10-05'::timestamptz, 'INTUR · Catálogo de Iniciativas de Turismo Rural y Comunitario (2026)', null, 'other', '{"activities":"Observación de flora y fauna, paisajes tropicales, kayak o bote y proceso del cacao.","services":"Hospedaje, alimentos, bebidas, transporte acuático, guía y camping.","hours":"Lunes a domingo, 7:00 a. m.–9:00 p. m.","modality":"Turismo rural y comunitario","facts":"Albergue ecológico a orillas de los humedales del río Papaturro, en el Refugio de Vida Silvestre Los Guatuzos.","map":"https://www.google.com/maps/d/u/0/edit?mid=1sYj97ccIS_7ybVgF2yEhC9F05BkfXdM&usp=sharing","contact_note":"Contacto publicado por INTUR en el catálogo 2026; confirmar antes de viajar."}'::jsonb, true, 'territories-data.js', 'rio-san-juan::albergue caiman los guatuzos', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-rio-san-juan', 'rio-san-juan', 'Río San Juan', 'rio', null, 'Río · Navegación', 'fa-water', 'rio_san_juan', null, 'San Carlos / El Castillo / San Juan de Nicaragua', 'Río histórico que nace en el Lago Cocibolca y fluye hacia el Caribe; eje de naturaleza, historia, navegación y turismo del departamento.', 'Río histórico que nace en el Lago Cocibolca y fluye hacia el Caribe; eje de naturaleza, historia, navegación y turismo del departamento.', 11.119218, -84.778118, 'approximate', false, null, 'verified', '2026-10-05'::timestamptz, 'Mapa Nacional de Turismo / Wikidata', 'https://www.mapanicaragua.com/rio-san-juan/', 'other', '{"activities":"Navegación, pesca deportiva, observación de aves e historia.","modality":"Ríos","facts":"Río histórico que nace en el Lago Cocibolca y fluye hacia el Caribe; eje de naturaleza, historia, navegación y turismo del departamento."}'::jsonb, true, 'territories-data.js', 'rio-san-juan::rio san juan', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-reserva-de-biosfera-bosawas', 'reserva-de-biosfera-bosawas', 'Reserva de Biosfera Bosawás', 'parque', null, 'Patrimonio de la Humanidad UNESCO', 'fa-tree', 'raccn', null, 'Norte y Caribe Norte', 'Uno de los bosques tropicales más extensos de Centroamérica, territorio mayangna y miskitu.', 'Uno de los bosques tropicales más extensos de Centroamérica, territorio mayangna y miskitu.', 13.44305, -85.14404, 'reference', false, null, 'verified', '2026-10-05'::timestamptz, 'Mapa Nacional de Turismo / MARENA (catálogo de naturaleza 2026)', null, 'other', '{"activities":"Investigación, conservación y turismo de naturaleza solo con condiciones y permisos adecuados.","facts":"Una de las áreas de conservación más extensas de Centroamérica y parte central del Corredor Biológico Mesoamericano, con territorios indígenas."}'::jsonb, true, 'territories-data.js', 'raccn::reserva de biosfera bosawas', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-rio-coco-wangki', 'rio-coco-wangki', 'Río Coco / Wangki', 'rio', null, 'Río Más Largo de Centroamérica', 'fa-water', 'raccn', 'raccn__waspam', null, 'El río más largo de Centroamérica, frontera con Honduras y eje de la vida miskitu.', 'El río más largo de Centroamérica, frontera con Honduras y eje de la vida miskitu.', 14.99751, -83.13809, 'approximate', false, null, 'verified', '2026-10-05'::timestamptz, 'GeoNames / Wikidata', 'https://mapcarta.com/es/19586360', 'other', '{"activities":"Paisaje fluvial, cultura comunitaria y navegación local.","facts":"Gran río del norte de Nicaragua que forma parte de la frontera con Honduras y desemboca en el Caribe; también se le conoce como Wangki."}'::jsonb, true, 'territories-data.js', 'raccn::rio coco wangki', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-bilwi-puerto-cabezas-muelle-historico', 'bilwi-puerto-cabezas-muelle-historico', 'Bilwi (Puerto Cabezas) & Muelle Histórico', 'centro_cultural', null, 'Cultura Caribeña & Playas', 'fa-anchor', 'raccn', null, null, 'Ciudad portuaria del Caribe norte con muelle, playa y cultura miskita.', 'Ciudad portuaria del Caribe norte con muelle, playa y cultura miskita.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'raccn::bilwi puerto cabezas muelle historico', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-comunidades-mayangnas-de-bonanza-y-rosita', 'comunidades-mayangnas-de-bonanza-y-rosita', 'Comunidades Mayangnas de Bonanza y Rosita', 'turismo_comunitario', null, 'Pueblos Originarios', 'fa-hands-holding', 'raccn', null, null, 'Pueblos originarios mayangnas que conservan su idioma y su relación con el bosque de Bosawás.', 'Pueblos originarios mayangnas que conservan su idioma y su relación con el bosque de Bosawás.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'raccn::comunidades mayangnas de bonanza y rosita', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-cayos-miskitos', 'cayos-miskitos', 'Cayos Miskitos', 'atractivo', null, 'Arrecifes & Casas sobre Pilotes', 'fa-fish', 'raccn', null, null, 'Cayos y arrecifes frente a la costa de la RACCN, con casas sobre pilotes de comunidades miskitas.', 'Cayos y arrecifes frente a la costa de la RACCN, con casas sobre pilotes de comunidades miskitas.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'raccn::cayos miskitos', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-waspam-portal-del-wangki', 'waspam-portal-del-wangki', 'Waspam, Portal del Wangki', 'rio', null, 'Navegación, comunidades, lengua y cultura', 'fa-ship', 'raccn', null, null, 'Pueblo a orillas del río Coco, centro de las comunidades miskitas del Wangki.', 'Pueblo a orillas del río Coco, centro de las comunidades miskitas del Wangki.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'raccn::waspam portal del wangki', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-sabanas-de-pino', 'sabanas-de-pino', 'Sabanas de Pino', 'turismo_comunitario', null, 'Paisaje, fotografía, fauna y comunidad', 'fa-tree', 'raccn', null, null, 'Extensas sabanas de pino caribe cerca de Bilwi, con fauna y paisajes abiertos.', 'Extensas sabanas de pino caribe cerca de Bilwi, con fauna y paisajes abiertos.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'raccn::sabanas de pino', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-triangulo-minero', 'triangulo-minero', 'Triángulo Minero', 'sitio_historico', null, 'Siuna, Bonanza y Rosita: naturaleza y memoria productiva', 'fa-mountain-sun', 'raccn', null, null, 'Siuna, Bonanza y Rosita: municipios mineros con historia productiva y acceso a la naturaleza de Bosawás.', 'Siuna, Bonanza y Rosita: municipios mineros con historia productiva y acceso a la naturaleza de Bosawás.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'raccn::triangulo minero', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-finca-agroturistica-el-cortes', 'finca-agroturistica-el-cortes', 'Finca Agroturística El Cortés', 'agroturismo', null, 'Agroturismo · Senderismo', 'fa-seedling', 'raccn', null, null, 'Finca de Siuna que une bosque denso y producción sostenible de cacao, granos y animales con la comunidad local.', 'Finca de Siuna que une bosque denso y producción sostenible de cacao, granos y animales con la comunidad local.', null, null, 'missing', false, 'Comunidad Campo Uno, del barrio Gilberto Romero 3 km al noreste, Siuna.', 'verified', '2026-10-05'::timestamptz, 'INTUR · Catálogo de Iniciativas de Turismo Rural y Comunitario (2026)', null, 'other', '{"activities":"Senderismo, camping, actividades agropecuarias, flora, fauna y aves.","services":"Alimentos, bebidas, cabañas, piscinas para niños y camping.","hours":"Jueves a domingo, 2:00 p. m.–9:00 p. m.","modality":"Agroturismo","facts":"Finca de Siuna que une bosque denso y producción sostenible de cacao, granos y animales con la comunidad local.","map":"https://www.google.com/maps/d/u/0/edit?mid=1XOFQIQ2p8s6_qUgbZZo4qnOkoLe5rnY&usp=sharing","contact_note":"Contacto publicado por INTUR en el catálogo 2026; confirmar antes de viajar."}'::jsonb, true, 'territories-data.js', 'raccn::finca agroturistica el cortes', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-parque-nacional-saslaya', 'parque-nacional-saslaya', 'Parque Nacional Saslaya', 'parque', null, 'Parque o área protegida · Turismo científico', 'fa-leaf', 'raccn', 'raccn__siuna', null, 'Parque nacional del gran sistema de conservación de Bosawás, de bosque tropical y alta biodiversidad.', 'Parque nacional del gran sistema de conservación de Bosawás, de bosque tropical y alta biodiversidad.', 13.7, -84.86, 'reference', false, null, 'verified', '2026-10-05'::timestamptz, 'MARENA · Plan de Manejo Parque Nacional Saslaya (catálogo de naturaleza 2026)', null, 'other', '{"activities":"Turismo científico y de naturaleza muy controlado, con coordinación local y ambiental.","facts":"Parque nacional del gran sistema de conservación de Bosawás, de bosque tropical y alta biodiversidad."}'::jsonb, true, 'territories-data.js', 'raccn::parque nacional saslaya', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-corn-island-little-corn-island', 'corn-island-little-corn-island', 'Corn Island & Little Corn Island', 'isla', null, 'Playas Turquesas & Arrecife', 'fa-umbrella-beach', 'raccs', null, null, 'Islas caribeñas de arena blanca, arrecifes y cultura creole.', 'Islas caribeñas de arena blanca, arrecifes y cultura creole.', 12.1664, -83.0514, 'approximate', false, null, 'verified', '2026-10-05'::timestamptz, 'Visit Nicaragua', 'https://www.visitanicaragua.com/islas/great-corn-island/', 'other', '{"facts":"Destino oficial del Caribe nicaragüense. Visit Nicaragua resalta playas de arena blanca, aguas transparentes, cultura afrocaribeña, gastronomía, snorkel, buceo y kayak.","contact_note":"Alojamiento, panga y buceo se registran como proveedores separados.","price_note":{"text":"Panga, snorkel, cabañas y taxi tienen precio por proveedor y fecha; consultar.","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, true, 'territories-data.js', 'raccs::corn island little corn island', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-cayos-perlas', 'cayos-perlas', 'Cayos Perlas', 'isla', null, 'Islas de Coral Desiertas', 'fa-fish', 'raccs', null, null, 'Cayos de arena y arrecife frente a Laguna de Perlas, en un área de anidación de tortugas.', 'Cayos de arena y arrecife frente a Laguna de Perlas, en un área de anidación de tortugas.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'raccs::cayos perlas', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-bahia-de-bluefields-malecon', 'bahia-de-bluefields-malecon', 'Bahía de Bluefields & Malecón', 'centro_cultural', null, 'Cultura Afrocaribeña', 'fa-anchor', 'raccs', null, null, 'Ciudad caribeña de música, bahía y mercado, cabecera de la RACCS.', 'Ciudad caribeña de música, bahía y mercado, cabecera de la RACCS.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'raccs::bahia de bluefields malecon', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-laguna-de-perlas-aspinwall', 'laguna-de-perlas-aspinwall', 'Laguna de Perlas & Aspinwall', 'laguna', null, 'Humedales & Comunidades Garífunas', 'fa-water', 'raccs', null, null, 'Laguna costera con comunidades creoles, garífunas y miskitu, punto de salida hacia los Cayos Perlas.', 'Laguna costera con comunidades creoles, garífunas y miskitu, punto de salida hacia los Cayos Perlas.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'raccs::laguna de perlas aspinwall', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-isla-rama-cay', 'isla-rama-cay', 'Isla Rama Cay', 'isla', null, 'Pueblo Originario Rama', 'fa-people-roof', 'raccs', null, null, 'Pequeña isla en la bahía de Bluefields, hogar principal del pueblo originario Rama.', 'Pequeña isla en la bahía de Bluefields, hogar principal del pueblo originario Rama.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'raccs::isla rama cay', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-bluff-beach', 'bluff-beach', 'Bluff Beach', 'playa', null, 'Playa, paisaje, deporte y gastronomía marina', 'fa-umbrella-beach', 'raccs', null, null, 'Playa en El Bluff, a la entrada de la bahía de Bluefields, con mar abierto y comida marina.', 'Playa en El Bluff, a la entrada de la bahía de Bluefields, con mar abierto y comida marina.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'raccs::bluff beach', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-playas-de-corn-island', 'playas-de-corn-island', 'Playas de Corn Island', 'isla', null, 'Long Bay, South West Bay, Heavy Sand y Mount Pleasant', 'fa-water', 'raccs', null, null, 'Playas de arena blanca y agua turquesa alrededor de Corn Island, con arrecifes para esnórquel.', 'Playas de arena blanca y agua turquesa alrededor de Corn Island, con arrecifes para esnórquel.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'raccs::playas de corn island', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-little-corn-island-y-otto-beach', 'little-corn-island-y-otto-beach', 'Little Corn Island y Otto Beach', 'isla', null, 'Caminatas, snorkel, buceo y descanso', 'fa-island-tropical', 'raccs', 'raccs__corn_island', null, 'Isla pequeña y sin carros, con senderos, arrecifes y playas tranquilas como Otto Beach.', 'Isla pequeña y sin carros, con senderos, arrecifes y playas tranquilas como Otto Beach.', 12.2884, -82.9812, 'approximate', false, null, 'verified', '2026-10-05'::timestamptz, 'Visit Nicaragua / GeoNames', 'https://www.visitanicaragua.com/atractivos/islas/', 'other', '{"activities":"Buceo, snorkel, playa, caminata y kayak.","facts":"Isla caribeña de menor tamaño, sin tránsito vehicular convencional, conocida por su ambiente tranquilo, playas y arrecifes."}'::jsonb, true, 'territories-data.js', 'raccs::little corn island y otto beach', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-awas-y-orinoco', 'awas-y-orinoco', 'Awas y Orinoco', 'centro_cultural', null, 'Experiencias culturales comunitarias miskita y garífuna', 'fa-people-group', 'raccs', null, null, 'Comunidades de Laguna de Perlas: Awas con playa lacustre y Orinoco, corazón de la cultura garífuna.', 'Comunidades de Laguna de Perlas: Awas con playa lacustre y Orinoco, corazón de la cultura garífuna.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'raccs::awas y orinoco', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-saltos-walpapigny-y-busay', 'saltos-walpapigny-y-busay', 'Saltos Walpapigny y Busay', 'atractivo', null, 'Senderismo, aves, naturaleza y aguas termales', 'fa-water', 'raccs', null, null, 'Caídas de agua en la RACCS rodeadas de bosque tropical, con aves y aguas termales en la zona.', 'Caídas de agua en la RACCS rodeadas de bosque tropical, con aves y aguas termales en la zona.', null, null, 'missing', false, null, 'pending_review', null, null, null, null, '{}'::jsonb, true, 'territories-data.js', 'raccs::saltos walpapigny y busay', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-garifuna-secrets-of-the-jungle', 'garifuna-secrets-of-the-jungle', 'Garífuna Secrets of the Jungle', 'turismo_comunitario', null, 'Turismo rural y comunitario · Tours a comunidades garífunas', 'fa-people-group', 'raccs', null, null, 'Experiencia garífuna cerca de Orinoco, Laguna de Perlas: música, gastronomía, historias ancestrales y selva tropical.', 'Experiencia garífuna cerca de Orinoco, Laguna de Perlas: música, gastronomía, historias ancestrales y selva tropical.', null, null, 'missing', false, '3 km afuera de la comunidad Orinoco, municipio de Laguna de Perlas.', 'verified', '2026-10-05'::timestamptz, 'INTUR · Catálogo de Iniciativas de Turismo Rural y Comunitario (2026)', null, 'other', '{"activities":"Tours a comunidades garífunas, río Wawashan, pesca tradicional, vida silvestre, bailes y música garífuna y saberes de finca.","services":"Hospedería, alimentos y bebidas.","hours":"Lunes a domingo, 8:00 a. m.–5:00 p. m.","modality":"Turismo rural y comunitario","facts":"Experiencia garífuna cerca de Orinoco, Laguna de Perlas: música, gastronomía, historias ancestrales y selva tropical.","map":"https://www.google.com/maps/d/u/0/edit?mid=1e1r8XYLJfIxIXfvCFCRm_n31drOyE9s&usp=sharing","contact_note":"Contacto publicado por INTUR en el catálogo 2026; confirmar antes de viajar."}'::jsonb, true, 'territories-data.js', 'raccs::garifuna secrets of the jungle', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
commit;
