-- BAQUEANO · Importación territories-data.js → Supabase · parte 06 de 07
-- Generado desde supabase/imports/20261005_territories_import.sql. Ejecutar las partes EN ORDEN en el SQL Editor.
-- Idempotente: si una parte se ejecuta dos veces, no duplica (ON CONFLICT).
begin;
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-rio-grande-de-matagalpa', 'rio-grande-de-matagalpa', 'Río Grande de Matagalpa', 'rio', null, 'Río · Paisaje', 'fa-water', 'raccs', null, 'Cuenca del Río Grande', 'Uno de los principales ríos de Nicaragua; recorre el país hacia el Caribe y drena una extensa cuenca.', 'Uno de los principales ríos de Nicaragua; recorre el país hacia el Caribe y drena una extensa cuenca.', 12.90905, -83.51531, 'approximate', false, null, 'verified', '2026-10-05'::timestamptz, 'GeoNames / OpenStreetMap', 'https://mapcarta.com/es/19583878', 'other', '{"activities":"Paisaje, navegación local y observación ambiental.","modality":"Ríos","facts":"Uno de los principales ríos de Nicaragua; recorre el país hacia el Caribe y drena una extensa cuenca."}'::jsonb, true, 'territories-data.js', 'raccs::rio grande de matagalpa', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.places (id, slug, name, category, subcategory, type_label, icon, department_id, municipality_id, zone_text, description, short_description, latitude, longitude, location_precision, map_ready, address, verification_status, verified_at, source_name, source_url, source_type, attributes, is_published, legacy_source, legacy_key, created_by, updated_by)
values ('pl-rio-escondido', 'rio-escondido', 'Río Escondido', 'rio', null, 'Río · Navegación', 'fa-water', 'raccs', null, 'Bluefields / El Rama', 'Río del sureste de Nicaragua que desemboca en el mar Caribe al norte de Bluefields.', 'Río del sureste de Nicaragua que desemboca en el mar Caribe al norte de Bluefields.', 12.08677, -83.74916, 'approximate', false, null, 'verified', '2026-10-05'::timestamptz, 'GeoNames / Mapcarta', 'https://mapcarta.com/es/19584100', 'other', '{"activities":"Navegación, paisaje y conexión fluvial.","modality":"Ríos","facts":"Río del sureste de Nicaragua que desemboca en el mar Caribe al norte de Bluefields."}'::jsonb, true, 'territories-data.js', 'raccs::rio escondido', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, category = excluded.category, subcategory = excluded.subcategory, type_label = excluded.type_label, icon = excluded.icon,
  municipality_id = excluded.municipality_id, zone_text = excluded.zone_text, description = excluded.description, short_description = excluded.short_description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, verification_status = excluded.verification_status, verified_at = excluded.verified_at, source_name = excluded.source_name,
  source_url = excluded.source_url, attributes = excluded.attributes
where public.places.updated_by = 'migration:territories';
insert into public.businesses (id, slug, name, category, business_type, department_id, municipality_id, municipality, description, latitude, longitude, location_precision, map_ready, address, phone, whatsapp, email, website_url, verification_status, verified, verified_at, source_name, source_url, source_type, attributes, status, legacy_source, legacy_key, created_by, updated_by)
values ('biz-poco-a-poco-hostel', 'poco-a-poco-hostel', 'Poco a Poco Hostel', 'hospedaje', 'hostal', 'leon', 'leon__leon', null, 'Hostal real en León con dormitorios y habitaciones privadas. Su web oficial confirma piscina, cocina, jardín, bar, rooftop, espacios de trabajo y tour desk.', 12.43701, -86.88182, 'exact', true, '2da calle NO, Iglesia Bautista 1/2 calle arriba, León', '+505 8295-5534', null, null, 'https://www.pocoapocohostel.com/', 'verified', true, '2026-10-05'::timestamptz, 'Poco a Poco Hostel (sitio oficial)', 'https://www.pocoapocohostel.com/', 'other', '{"modality":"Hospedajes","facts":"Hostal real en León con dormitorios y habitaciones privadas. Su web oficial confirma piscina, cocina, jardín, bar, rooftop, espacios de trabajo y tour desk.","amenities":["Dormitorios","Habitaciones privadas","Piscina","Cocina","Bar","Rooftop","Espacios de trabajo"],"price_note":{"text":"Consultar disponibilidad y tarifa","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, 'published', 'territories-data.js', 'leon::poco a poco hostel', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, business_type = excluded.business_type, municipality_id = excluded.municipality_id, description = excluded.description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, email = excluded.email, website_url = excluded.website_url,
  verification_status = excluded.verification_status, verified = excluded.verified, verified_at = excluded.verified_at,
  source_name = excluded.source_name, source_url = excluded.source_url, attributes = excluded.attributes
where public.businesses.updated_by = 'migration:territories';
insert into public.businesses (id, slug, name, category, business_type, department_id, municipality_id, municipality, description, latitude, longitude, location_precision, map_ready, address, phone, whatsapp, email, website_url, verification_status, verified, verified_at, source_name, source_url, source_type, attributes, status, legacy_source, legacy_key, created_by, updated_by)
values ('biz-hotel-el-convento', 'hotel-el-convento', 'Hotel El Convento', 'hospedaje', 'hotel', 'leon', 'leon__leon', null, 'Hotel ubicado en el centro histórico de León, registrado como alojamiento en OpenStreetMap y GeoNames, a pocos minutos caminando de la Catedral de León.', 12.43561, -86.8819, 'exact', true, 'Centro histórico de León, Nicaragua', null, null, null, null, 'verified', true, '2026-10-05'::timestamptz, 'OpenStreetMap / GeoNames / Wikidata', 'https://mapcarta.com/es/32808130', 'other', '{"modality":"Hospedajes","facts":"Hotel ubicado en el centro histórico de León, registrado como alojamiento en OpenStreetMap y GeoNames, a pocos minutos caminando de la Catedral de León.","amenities":["Alojamiento urbano y patrimonial"],"price_note":{"text":"Consultar disponibilidad y tarifa","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, 'published', 'territories-data.js', 'leon::hotel el convento', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, business_type = excluded.business_type, municipality_id = excluded.municipality_id, description = excluded.description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, email = excluded.email, website_url = excluded.website_url,
  verification_status = excluded.verification_status, verified = excluded.verified, verified_at = excluded.verified_at,
  source_name = excluded.source_name, source_url = excluded.source_url, attributes = excluded.attributes
where public.businesses.updated_by = 'migration:territories';
insert into public.businesses (id, slug, name, category, business_type, department_id, municipality_id, municipality, description, latitude, longitude, location_precision, map_ready, address, phone, whatsapp, email, website_url, verification_status, verified, verified_at, source_name, source_url, source_type, attributes, status, legacy_source, legacy_key, created_by, updated_by)
values ('biz-comedor-la-cucaracha', 'comedor-la-cucaracha', 'Comedor La Cucaracha', 'comedor', 'comedor', 'leon', 'leon__leon', null, 'Comedor popular en León con ubicación geográfica verificable y referencias públicas de comida nicaragüense.', 12.4342008, -86.873702, 'exact', true, 'León, Nicaragua', null, null, null, null, 'verified', true, '2026-10-05'::timestamptz, 'Near-Place / Google Business', 'https://ni.near-place.com/comedor-la-cucaracha-leon', 'other', '{"modality":"Comedores","facts":"Comedor popular en León con ubicación geográfica verificable y referencias públicas de comida nicaragüense.","map":"https://www.google.com/maps?q=12.4342008,-86.873702","amenities":["Comida popular nicaragüense","Almuerzo"],"price_note":{"text":"Consultar precio, menú y horario con el establecimiento","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, 'published', 'territories-data.js', 'leon::comedor la cucaracha', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, business_type = excluded.business_type, municipality_id = excluded.municipality_id, description = excluded.description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, email = excluded.email, website_url = excluded.website_url,
  verification_status = excluded.verification_status, verified = excluded.verified, verified_at = excluded.verified_at,
  source_name = excluded.source_name, source_url = excluded.source_url, attributes = excluded.attributes
where public.businesses.updated_by = 'migration:territories';
insert into public.businesses (id, slug, name, category, business_type, department_id, municipality_id, municipality, description, latitude, longitude, location_precision, map_ready, address, phone, whatsapp, email, website_url, verification_status, verified, verified_at, source_name, source_url, source_type, attributes, status, legacy_source, legacy_key, created_by, updated_by)
values ('biz-morgan-s-rock-reserve-ecolodge', 'morgan-s-rock-reserve-ecolodge', 'Morgan''s Rock Reserve & Ecolodge', 'hospedaje', 'ecolodge', 'rivas', 'rivas__san_juan_del_sur', null, 'Eco-lodge y reserva privada en Playa Ocotal. Su web oficial confirma alojamiento y ubicación en San Juan del Sur, además de actividades y experiencias de naturaleza.', 11.30552, -85.92049, 'exact', true, 'Playa Ocotal, San Juan del Sur, Rivas, Nicaragua', '+505 8670-7676', '+505 8988-7176', 'reservations@morgansrock.com', 'https://www.morgansrock.com/stay/', 'verified', true, '2026-10-05'::timestamptz, 'Morgan''s Rock (sitio oficial)', 'https://www.morgansrock.com/stay/', 'other', '{"modality":"Hospedajes","facts":"Eco-lodge y reserva privada en Playa Ocotal. Su web oficial confirma alojamiento y ubicación en San Juan del Sur, además de actividades y experiencias de naturaleza.","amenities":["Bungalows/villas","Naturaleza","Playa","Gastronomía","Actividades de reserva"],"price_note":{"text":"Consultar disponibilidad y tarifa","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, 'published', 'territories-data.js', 'rivas::morgan s rock reserve ecolodge', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, business_type = excluded.business_type, municipality_id = excluded.municipality_id, description = excluded.description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, email = excluded.email, website_url = excluded.website_url,
  verification_status = excluded.verification_status, verified = excluded.verified, verified_at = excluded.verified_at,
  source_name = excluded.source_name, source_url = excluded.source_url, attributes = excluded.attributes
where public.businesses.updated_by = 'migration:territories';
insert into public.businesses (id, slug, name, category, business_type, department_id, municipality_id, municipality, description, latitude, longitude, location_precision, map_ready, address, phone, whatsapp, email, website_url, verification_status, verified, verified_at, source_name, source_url, source_type, attributes, status, legacy_source, legacy_key, created_by, updated_by)
values ('biz-hotel-victoriano', 'hotel-victoriano', 'Hotel Victoriano', 'hospedaje', 'hotel', 'rivas', 'rivas__san_juan_del_sur', null, 'Hotel frente a la playa de San Juan del Sur. El sitio oficial confirma 25 habitaciones, piscina, restaurante, spa/masajes y alojamiento con Wi-Fi.', 11.25069, -85.87271, 'exact', true, 'Paseo del Rey, San Juan del Sur, Nicaragua', '+505 8679-0261', null, 'reservaciones@hotelvictoriano.com', 'https://www.hotelvictoriano.com/nosotros.php', 'verified', true, '2026-10-05'::timestamptz, 'Hotel Victoriano (sitio oficial)', 'https://www.hotelvictoriano.com/nosotros.php', 'other', '{"modality":"Hospedajes","facts":"Hotel frente a la playa de San Juan del Sur. El sitio oficial confirma 25 habitaciones, piscina, restaurante, spa/masajes y alojamiento con Wi-Fi.","amenities":["Habitaciones","Piscina","Restaurante","Spa","Gimnasio","Wi-Fi","Frente a la playa"],"price_note":{"text":"Consultar disponibilidad y tarifa","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, 'published', 'territories-data.js', 'rivas::hotel victoriano', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, business_type = excluded.business_type, municipality_id = excluded.municipality_id, description = excluded.description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, email = excluded.email, website_url = excluded.website_url,
  verification_status = excluded.verification_status, verified = excluded.verified, verified_at = excluded.verified_at,
  source_name = excluded.source_name, source_url = excluded.source_url, attributes = excluded.attributes
where public.businesses.updated_by = 'migration:territories';
insert into public.businesses (id, slug, name, category, business_type, department_id, municipality_id, municipality, description, latitude, longitude, location_precision, map_ready, address, phone, whatsapp, email, website_url, verification_status, verified, verified_at, source_name, source_url, source_type, attributes, status, legacy_source, legacy_key, created_by, updated_by)
values ('biz-totoco-eco-resort', 'totoco-eco-resort', 'TOTOCO Eco Resort', 'hospedaje', 'resort', 'rivas', 'rivas__altagracia', null, 'Eco resort de Ometepe con cabañas de selva y enfoque regenerativo. Su sitio oficial confirma la dirección, teléfono y experiencias en la isla.', 11.48042, -85.52183, 'reference', false, 'Callejón de la Palmera, 800 m arriba, Balgüe, Nicaragua', '+505 5815-0757', null, 'info@totoco-resort.com', 'https://www.totoco-resort.com/contact', 'verified', true, '2026-10-05'::timestamptz, 'TOTOCO Eco Resort (sitio oficial)', 'https://www.totoco-resort.com/contact', 'other', '{"modality":"Hospedajes","facts":"Eco resort de Ometepe con cabañas de selva y enfoque regenerativo. Su sitio oficial confirma la dirección, teléfono y experiencias en la isla.","amenities":["Cabañas","Naturaleza","Piscina","Excursiones","Experiencias de Ometepe"],"price_note":{"text":"Consultar disponibilidad y tarifa","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, 'published', 'territories-data.js', 'rivas::totoco eco resort', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, business_type = excluded.business_type, municipality_id = excluded.municipality_id, description = excluded.description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, email = excluded.email, website_url = excluded.website_url,
  verification_status = excluded.verification_status, verified = excluded.verified, verified_at = excluded.verified_at,
  source_name = excluded.source_name, source_url = excluded.source_url, attributes = excluded.attributes
where public.businesses.updated_by = 'migration:territories';
insert into public.businesses (id, slug, name, category, business_type, department_id, municipality_id, municipality, description, latitude, longitude, location_precision, map_ready, address, phone, whatsapp, email, website_url, verification_status, verified, verified_at, source_name, source_url, source_type, attributes, status, legacy_source, legacy_key, created_by, updated_by)
values ('biz-hotel-dario', 'hotel-dario', 'Hotel Darío', 'hospedaje', 'hotel', 'granada', 'granada__granada', null, 'Establecimiento hotelero identificado cartográficamente en el centro histórico de Granada, sobre el corredor turístico de Calle La Calzada.', 11.93027, -85.95161, 'exact', true, 'Calle La Calzada, Granada', null, null, null, 'http://www.hoteldario.com/', 'verified', true, '2026-10-05'::timestamptz, 'OpenStreetMap / GeoNames / Wikidata', 'https://mapcarta.com/es/32290446', 'other', '{"modality":"Hospedajes","facts":"Establecimiento hotelero identificado cartográficamente en el centro histórico de Granada, sobre el corredor turístico de Calle La Calzada.","amenities":["Alojamiento urbano en el centro histórico"],"price_note":{"text":"Consultar disponibilidad y tarifa","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, 'published', 'territories-data.js', 'granada::hotel dario', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, business_type = excluded.business_type, municipality_id = excluded.municipality_id, description = excluded.description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, email = excluded.email, website_url = excluded.website_url,
  verification_status = excluded.verification_status, verified = excluded.verified, verified_at = excluded.verified_at,
  source_name = excluded.source_name, source_url = excluded.source_url, attributes = excluded.attributes
where public.businesses.updated_by = 'migration:territories';
insert into public.businesses (id, slug, name, category, business_type, department_id, municipality_id, municipality, description, latitude, longitude, location_precision, map_ready, address, phone, whatsapp, email, website_url, verification_status, verified, verified_at, source_name, source_url, source_type, attributes, status, legacy_source, legacy_key, created_by, updated_by)
values ('biz-treehouse-nicaragua', 'treehouse-nicaragua', 'Treehouse Nicaragua', 'hospedaje', 'hostal', 'granada', 'granada__granada', null, 'Hostal de selva con casas árbol, habitaciones privadas y dormitorio compartido. Su web oficial confirma su ubicación en km 57.5 de la carretera Granada-Nandaime.', null, null, 'pending', false, 'Km 57.5 carretera Granada-Nandaime, Comarca Poste Rojo, Granada', null, '+505 8550-3093', 'hello@treehousenicaragua.com', 'https://www.treehousenicaragua.com/hostel', 'partial', false, '2026-10-05'::timestamptz, 'Treehouse Nicaragua (sitio oficial)', 'https://www.treehousenicaragua.com/hostel', 'other', '{"modality":"Hospedajes","facts":"Hostal de selva con casas árbol, habitaciones privadas y dormitorio compartido. Su web oficial confirma su ubicación en km 57.5 de la carretera Granada-Nandaime.","amenities":["Casas árbol","Habitaciones privadas","Dormitorio","Áreas comunes","Eventos"],"price_note":{"text":"Consultar disponibilidad y tarifa","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, 'published', 'territories-data.js', 'granada::treehouse nicaragua', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, business_type = excluded.business_type, municipality_id = excluded.municipality_id, description = excluded.description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, email = excluded.email, website_url = excluded.website_url,
  verification_status = excluded.verification_status, verified = excluded.verified, verified_at = excluded.verified_at,
  source_name = excluded.source_name, source_url = excluded.source_url, attributes = excluded.attributes
where public.businesses.updated_by = 'migration:territories';
insert into public.businesses (id, slug, name, category, business_type, department_id, municipality_id, municipality, description, latitude, longitude, location_precision, map_ready, address, phone, whatsapp, email, website_url, verification_status, verified, verified_at, source_name, source_url, source_type, attributes, status, legacy_source, legacy_key, created_by, updated_by)
values ('biz-hotel-plaza-colon', 'hotel-plaza-colon', 'Hotel Plaza Colón', 'hospedaje', 'hotel', 'granada', 'granada__granada', null, 'Hotel ubicado frente al Parque Central de Granada. Su web oficial confirma habitaciones, balcones, servicios hoteleros y prácticas de sostenibilidad certificadas.', 11.92982, -85.95451, 'exact', true, 'Parque Central, Granada, Nicaragua', '+505 2552-8489', '+505 8590-4062', 'reservaciones@hotelplazacolon.com', 'https://hotelplazacolon.com/es/inicio/', 'verified', true, '2026-10-05'::timestamptz, 'Hotel Plaza Colón (sitio oficial)', 'https://hotelplazacolon.com/es/inicio/', 'other', '{"modality":"Hospedajes","facts":"Hotel ubicado frente al Parque Central de Granada. Su web oficial confirma habitaciones, balcones, servicios hoteleros y prácticas de sostenibilidad certificadas.","amenities":["Habitaciones","Wi-Fi","Balcones","Servicios turísticos","Enfoque de sostenibilidad"],"price_note":{"text":"Consultar disponibilidad y tarifa","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, 'published', 'territories-data.js', 'granada::hotel plaza colon', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, business_type = excluded.business_type, municipality_id = excluded.municipality_id, description = excluded.description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, email = excluded.email, website_url = excluded.website_url,
  verification_status = excluded.verification_status, verified = excluded.verified, verified_at = excluded.verified_at,
  source_name = excluded.source_name, source_url = excluded.source_url, attributes = excluded.attributes
where public.businesses.updated_by = 'migration:territories';
insert into public.businesses (id, slug, name, category, business_type, department_id, municipality_id, municipality, description, latitude, longitude, location_precision, map_ready, address, phone, whatsapp, email, website_url, verification_status, verified, verified_at, source_name, source_url, source_type, attributes, status, legacy_source, legacy_key, created_by, updated_by)
values ('biz-restaurante-el-zaguan', 'restaurante-el-zaguan', 'Restaurante El Zaguán', 'restaurante', 'restaurante', 'granada', 'granada__granada', null, 'Restaurante del centro histórico de Granada, verificado mediante ficha comercial y cartografía abierta.', 11.92958, -85.95256, 'exact', true, 'Costado este de la Catedral, Granada', '+505 8886-6099', null, null, null, 'verified', true, '2026-10-05'::timestamptz, 'Google Business / OpenStreetMap', 'https://mapcarta.com/es/W419754191', 'other', '{"modality":"Restaurantes","facts":"Restaurante del centro histórico de Granada, verificado mediante ficha comercial y cartografía abierta.","map":"https://www.google.com/maps?q=11.92958,-85.95256","amenities":["Cortes de carne","Almuerzo","Cena"],"price_note":{"text":"Consultar precio, menú y horario con el establecimiento","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, 'published', 'territories-data.js', 'granada::restaurante el zaguan', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, business_type = excluded.business_type, municipality_id = excluded.municipality_id, description = excluded.description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, email = excluded.email, website_url = excluded.website_url,
  verification_status = excluded.verification_status, verified = excluded.verified, verified_at = excluded.verified_at,
  source_name = excluded.source_name, source_url = excluded.source_url, attributes = excluded.attributes
where public.businesses.updated_by = 'migration:territories';
insert into public.businesses (id, slug, name, category, business_type, department_id, municipality_id, municipality, description, latitude, longitude, location_precision, map_ready, address, phone, whatsapp, email, website_url, verification_status, verified, verified_at, source_name, source_url, source_type, attributes, status, legacy_source, legacy_key, created_by, updated_by)
values ('biz-boca-baco', 'boca-baco', 'Boca Baco', 'restaurante', 'restaurante', 'granada', 'granada__granada', null, 'Restaurante de cocina fusión y tapas en el centro de Granada. Su sitio oficial confirma contacto, ubicación y menú.', null, null, 'address', false, 'Costado oeste de la Catedral / Av. La Sirena, Granada', '+505 8810-9805', null, 'boca.baco20@gmail.com', 'https://bocabaconicaragua.com/english-menu/', 'partial', false, '2026-10-05'::timestamptz, 'Sitio oficial Boca Baco', 'https://bocabaconicaragua.com/english-menu/', 'other', '{"modality":"Restaurantes","facts":"Restaurante de cocina fusión y tapas en el centro de Granada. Su sitio oficial confirma contacto, ubicación y menú.","map":"https://www.google.com/maps/search/?api=1&query=Boca%20Baco%20Granada%20Nicaragua","amenities":["Cocina fusión","Sushi","Tapas","Vinos","Cocteles","Opciones veganas"],"price_note":{"text":"Consultar precio, menú y horario con el establecimiento","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, 'published', 'territories-data.js', 'granada::boca baco', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, business_type = excluded.business_type, municipality_id = excluded.municipality_id, description = excluded.description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, email = excluded.email, website_url = excluded.website_url,
  verification_status = excluded.verification_status, verified = excluded.verified, verified_at = excluded.verified_at,
  source_name = excluded.source_name, source_url = excluded.source_url, attributes = excluded.attributes
where public.businesses.updated_by = 'migration:territories';
insert into public.businesses (id, slug, name, category, business_type, department_id, municipality_id, municipality, description, latitude, longitude, location_precision, map_ready, address, phone, whatsapp, email, website_url, verification_status, verified, verified_at, source_name, source_url, source_type, attributes, status, legacy_source, legacy_key, created_by, updated_by)
values ('biz-comedor-dona-tulita', 'comedor-dona-tulita', 'Comedor Doña Tulita', 'comedor', 'comedor', 'granada', 'granada__granada', null, 'Comedor de comida casera nicaragüense en Granada. La dirección, el teléfono y las coordenadas coinciden en fuentes locales y cartográficas.', 11.9322657, -85.9573215, 'exact', true, 'Calle El Hormiguero, Granada', '+505 2552-7100', null, null, null, 'verified', true, '2026-10-05'::timestamptz, 'Near-Place / Google Business', 'https://ni.near-place.com/comedor-dona-tulita-w2jvw33-calle-el-hormiguero-granada/en', 'other', '{"modality":"Comedores","facts":"Comedor de comida casera nicaragüense en Granada. La dirección, el teléfono y las coordenadas coinciden en fuentes locales y cartográficas.","map":"https://www.google.com/maps?q=11.9322657,-85.9573215","amenities":["Comida casera","Almuerzo","Cena","Atención en local"],"price_note":{"text":"Consultar precio, menú y horario con el establecimiento","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, 'published', 'territories-data.js', 'granada::comedor dona tulita', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, business_type = excluded.business_type, municipality_id = excluded.municipality_id, description = excluded.description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, email = excluded.email, website_url = excluded.website_url,
  verification_status = excluded.verification_status, verified = excluded.verified, verified_at = excluded.verified_at,
  source_name = excluded.source_name, source_url = excluded.source_url, attributes = excluded.attributes
where public.businesses.updated_by = 'migration:territories';
insert into public.businesses (id, slug, name, category, business_type, department_id, municipality_id, municipality, description, latitude, longitude, location_precision, map_ready, address, phone, whatsapp, email, website_url, verification_status, verified, verified_at, source_name, source_url, source_type, attributes, status, legacy_source, legacy_key, created_by, updated_by)
values ('biz-comedor-la-parada', 'comedor-la-parada', 'Comedor La Parada', 'comedor', 'comedor', 'granada', 'granada__granada', null, 'Comedor local dentro de la terminal de pequeños buses de Granada. Fuentes recientes confirman dirección, teléfono y horario.', null, null, 'address', false, 'Terminal de pequeños buses, Granada (Plus Code W2HW+G8V)', '+505 8955-8759', null, null, null, 'partial', false, '2026-10-05'::timestamptz, 'Restaurant Guru / AZ Nicaragua', 'https://es.restaurantguru.com/Comedor-La-Parada-Granada-Granada', 'other', '{"modality":"Comedores","facts":"Comedor local dentro de la terminal de pequeños buses de Granada. Fuentes recientes confirman dirección, teléfono y horario.","map":"https://www.google.com/maps/search/?api=1&query=Comedor%20La%20Parada%20Granada%20Nicaragua","amenities":["Comida típica","Menú del día","Opciones vegetarianas","Para llevar"],"price_note":{"text":"Consultar precio, menú y horario con el establecimiento","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, 'published', 'territories-data.js', 'granada::comedor la parada', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, business_type = excluded.business_type, municipality_id = excluded.municipality_id, description = excluded.description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, email = excluded.email, website_url = excluded.website_url,
  verification_status = excluded.verification_status, verified = excluded.verified, verified_at = excluded.verified_at,
  source_name = excluded.source_name, source_url = excluded.source_url, attributes = excluded.attributes
where public.businesses.updated_by = 'migration:territories';
insert into public.businesses (id, slug, name, category, business_type, department_id, municipality_id, municipality, description, latitude, longitude, location_precision, map_ready, address, phone, whatsapp, email, website_url, verification_status, verified, verified_at, source_name, source_url, source_type, attributes, status, legacy_source, legacy_key, created_by, updated_by)
values ('biz-comedor-martha', 'comedor-martha', 'Comedor Martha', 'comedor', 'comedor', 'granada', 'granada__granada', null, 'Comedor y restaurante nicaragüense con ficha comercial activa en Granada.', null, null, 'address', false, 'Frente al parque del cementerio, Granada', '+505 8477-5431', null, null, null, 'partial', false, '2026-10-05'::timestamptz, 'Google Business', 'https://www.google.com/maps/search/?api=1&query=Comedor+Martha+Granada+Nicaragua', 'other', '{"modality":"Comedores","facts":"Comedor y restaurante nicaragüense con ficha comercial activa en Granada.","map":"https://www.google.com/maps/search/?api=1&query=Comedor%20Martha%20Granada%20Nicaragua","amenities":["Comida nicaragüense","Atención en local"],"price_note":{"text":"Consultar precio, menú y horario con el establecimiento","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, 'published', 'territories-data.js', 'granada::comedor martha', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, business_type = excluded.business_type, municipality_id = excluded.municipality_id, description = excluded.description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, email = excluded.email, website_url = excluded.website_url,
  verification_status = excluded.verification_status, verified = excluded.verified, verified_at = excluded.verified_at,
  source_name = excluded.source_name, source_url = excluded.source_url, attributes = excluded.attributes
where public.businesses.updated_by = 'migration:territories';
insert into public.businesses (id, slug, name, category, business_type, department_id, municipality_id, municipality, description, latitude, longitude, location_precision, map_ready, address, phone, whatsapp, email, website_url, verification_status, verified, verified_at, source_name, source_url, source_type, attributes, status, legacy_source, legacy_key, created_by, updated_by)
values ('biz-kiosco-la-gata', 'kiosco-la-gata', 'Kiosco La Gata', 'kiosco', 'kiosco', 'granada', 'granada__granada', null, 'Kiosco tradicional de vigorón en el Parque Central Colón, identificado por fuentes periodísticas nicaragüenses como un kiosco histórico de Granada.', null, null, 'address', false, 'Parque Central Colón, Granada', null, null, null, null, 'partial', false, '2026-10-05'::timestamptz, 'La Gaceta / La Verdad Nica', 'https://www.lagaceta.gob.ni/la-imponente-gran-sultana-granada-muestra-algunos-de-sus-rincones-mas-hermosos/', 'other', '{"modality":"Kioscos","facts":"Kiosco tradicional de vigorón en el Parque Central Colón, identificado por fuentes periodísticas nicaragüenses como un kiosco histórico de Granada.","map":"https://www.google.com/maps/search/?api=1&query=Kiosco%20La%20Gata%20Granada%20Nicaragua","amenities":["Vigorón","Cerdo con yuca","Bebidas tradicionales"],"price_note":{"text":"Consultar precio, menú y horario con el establecimiento","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, 'published', 'territories-data.js', 'granada::kiosco la gata', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, business_type = excluded.business_type, municipality_id = excluded.municipality_id, description = excluded.description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, email = excluded.email, website_url = excluded.website_url,
  verification_status = excluded.verification_status, verified = excluded.verified, verified_at = excluded.verified_at,
  source_name = excluded.source_name, source_url = excluded.source_url, attributes = excluded.attributes
where public.businesses.updated_by = 'migration:territories';
insert into public.businesses (id, slug, name, category, business_type, department_id, municipality_id, municipality, description, latitude, longitude, location_precision, map_ready, address, phone, whatsapp, email, website_url, verification_status, verified, verified_at, source_name, source_url, source_type, attributes, status, legacy_source, legacy_key, created_by, updated_by)
values ('biz-selva-negra-ecolodge', 'selva-negra-ecolodge', 'Selva Negra Ecolodge', 'hospedaje', 'ecolodge', 'matagalpa', 'matagalpa__matagalpa', null, 'Hotel y finca cafetalera histórica en las montañas de Matagalpa. Su sitio oficial confirma senderismo, aviturismo, tours de café y cacao y experiencias de naturaleza.', 12.99908, -85.90928, 'reference', false, 'Km 140 carretera Matagalpa-Jinotega, Matagalpa, Nicaragua', '+505 8100-9100', null, 'info@selvanegra.com', 'https://www.selvanegra.com/', 'verified', true, '2026-10-05'::timestamptz, 'Selva Negra (sitio oficial)', 'https://www.selvanegra.com/', 'other', '{"modality":"Hospedajes","facts":"Hotel y finca cafetalera histórica en las montañas de Matagalpa. Su sitio oficial confirma senderismo, aviturismo, tours de café y cacao y experiencias de naturaleza.","amenities":["Hotel","Cabañas","Senderismo","Aviturismo","Café","Cacao","Finca","Restaurante"],"price_note":{"text":"Consultar disponibilidad y tarifa","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, 'published', 'territories-data.js', 'matagalpa::selva negra ecolodge', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, business_type = excluded.business_type, municipality_id = excluded.municipality_id, description = excluded.description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, email = excluded.email, website_url = excluded.website_url,
  verification_status = excluded.verification_status, verified = excluded.verified, verified_at = excluded.verified_at,
  source_name = excluded.source_name, source_url = excluded.source_url, attributes = excluded.attributes
where public.businesses.updated_by = 'migration:territories';
insert into public.businesses (id, slug, name, category, business_type, department_id, municipality_id, municipality, description, latitude, longitude, location_precision, map_ready, address, phone, whatsapp, email, website_url, verification_status, verified, verified_at, source_name, source_url, source_type, attributes, status, legacy_source, legacy_key, created_by, updated_by)
values ('biz-hotel-san-jose-matagalpa', 'hotel-san-jose-matagalpa', 'Hotel San José Matagalpa', 'hospedaje', 'hotel', 'matagalpa', 'matagalpa__matagalpa', null, 'Hotel urbano en el centro de Matagalpa. Su sitio oficial confirma habitaciones y su ubicación detrás de la Iglesia San José.', 12.92163, -85.91877, 'exact', true, 'Detrás de la Iglesia San José, Matagalpa', '+505 2772-2544', '+505 8534-9559', null, 'https://hotelsanjosematagalpa.com/', 'verified', true, '2026-10-05'::timestamptz, 'Hotel San José Matagalpa (sitio oficial)', 'https://hotelsanjosematagalpa.com/', 'other', '{"modality":"Hospedajes","facts":"Hotel urbano en el centro de Matagalpa. Su sitio oficial confirma habitaciones y su ubicación detrás de la Iglesia San José.","amenities":["Habitaciones","Desayuno","Wi-Fi","Alojamiento urbano"],"price_note":{"text":"Consultar disponibilidad y tarifa","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, 'published', 'territories-data.js', 'matagalpa::hotel san jose matagalpa', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, business_type = excluded.business_type, municipality_id = excluded.municipality_id, description = excluded.description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, email = excluded.email, website_url = excluded.website_url,
  verification_status = excluded.verification_status, verified = excluded.verified, verified_at = excluded.verified_at,
  source_name = excluded.source_name, source_url = excluded.source_url, attributes = excluded.attributes
where public.businesses.updated_by = 'migration:territories';
insert into public.businesses (id, slug, name, category, business_type, department_id, municipality_id, municipality, description, latitude, longitude, location_precision, map_ready, address, phone, whatsapp, email, website_url, verification_status, verified, verified_at, source_name, source_url, source_type, attributes, status, legacy_source, legacy_key, created_by, updated_by)
values ('biz-intercontinental-managua-at-metrocentro-mall', 'intercontinental-managua-at-metrocentro-mall', 'InterContinental Managua at Metrocentro Mall', 'hospedaje', 'hotel', 'managua', 'managua__managua', null, 'Hotel urbano de la cadena InterContinental. Su sitio oficial confirma alojamiento, piscina, restaurantes, gimnasio, estacionamiento y servicios de negocios.', 12.1266, -86.26488, 'exact', true, 'Frente al Centro Comercial Metrocentro, Managua', '+505 2276-8989', null, 'inter.mga@r-hr.com', 'https://www.ihg.com/intercontinental/hotels/es/es/managua/mgahb/hoteldetail', 'verified', true, '2026-10-05'::timestamptz, 'IHG / InterContinental (sitio oficial)', 'https://www.ihg.com/intercontinental/hotels/es/es/managua/mgahb/hoteldetail', 'other', '{"modality":"Hospedajes","facts":"Hotel urbano de la cadena InterContinental. Su sitio oficial confirma alojamiento, piscina, restaurantes, gimnasio, estacionamiento y servicios de negocios.","amenities":["Habitaciones y suites","Piscina","Restaurantes","Gimnasio","Estacionamiento","Accesibilidad"],"price_note":{"text":"Consultar disponibilidad y tarifa","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, 'published', 'territories-data.js', 'managua::intercontinental managua at metrocentro mall', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, business_type = excluded.business_type, municipality_id = excluded.municipality_id, description = excluded.description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, email = excluded.email, website_url = excluded.website_url,
  verification_status = excluded.verification_status, verified = excluded.verified, verified_at = excluded.verified_at,
  source_name = excluded.source_name, source_url = excluded.source_url, attributes = excluded.attributes
where public.businesses.updated_by = 'migration:territories';
insert into public.businesses (id, slug, name, category, business_type, department_id, municipality_id, municipality, description, latitude, longitude, location_precision, map_ready, address, phone, whatsapp, email, website_url, verification_status, verified, verified_at, source_name, source_url, source_type, attributes, status, legacy_source, legacy_key, created_by, updated_by)
values ('biz-hyatt-place-managua', 'hyatt-place-managua', 'Hyatt Place Managua', 'hospedaje', 'hotel', 'managua', 'managua__managua', null, 'Hotel de la marca Hyatt Place. Hyatt confirma habitaciones modernas, desayuno, Wi-Fi, piscina exterior y espacios para viajeros de negocios y ocio.', 12.10173, -86.24828, 'exact', true, 'Carretera Masaya km 8.2, Managua', '+505 2252-7000', null, null, 'https://www.hyatt.com/hyatt-place/es-ES/mgazm-hyatt-place-managua', 'verified', true, '2026-10-05'::timestamptz, 'Hyatt (sitio oficial)', 'https://www.hyatt.com/hyatt-place/es-ES/mgazm-hyatt-place-managua', 'other', '{"modality":"Hospedajes","facts":"Hotel de la marca Hyatt Place. Hyatt confirma habitaciones modernas, desayuno, Wi-Fi, piscina exterior y espacios para viajeros de negocios y ocio.","amenities":["Habitaciones y suites","Desayuno","Wi-Fi","Piscina","Bar","Espacios de trabajo"],"price_note":{"text":"Consultar disponibilidad y tarifa","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, 'published', 'territories-data.js', 'managua::hyatt place managua', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, business_type = excluded.business_type, municipality_id = excluded.municipality_id, description = excluded.description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, email = excluded.email, website_url = excluded.website_url,
  verification_status = excluded.verification_status, verified = excluded.verified, verified_at = excluded.verified_at,
  source_name = excluded.source_name, source_url = excluded.source_url, attributes = excluded.attributes
where public.businesses.updated_by = 'migration:territories';
insert into public.businesses (id, slug, name, category, business_type, department_id, municipality_id, municipality, description, latitude, longitude, location_precision, map_ready, address, phone, whatsapp, email, website_url, verification_status, verified, verified_at, source_name, source_url, source_type, attributes, status, legacy_source, legacy_key, created_by, updated_by)
values ('biz-cocina-de-dona-haydee', 'cocina-de-dona-haydee', 'Cocina de Doña Haydée', 'restaurante', 'restaurante', 'managua', 'managua__managua', null, 'Restaurante nicaragüense ampliamente conocido en Managua. La ficha comercial actual confirma su dirección, teléfono y operación diaria.', 12.11872, -86.26163, 'exact', true, 'Carretera a Masaya km 4 1/2, Managua', '+505 2270-6100', null, null, null, 'verified', true, '2026-10-05'::timestamptz, 'Google Business / OpenStreetMap', 'https://mapcarta.com/N887699115', 'other', '{"modality":"Restaurantes","facts":"Restaurante nicaragüense ampliamente conocido en Managua. La ficha comercial actual confirma su dirección, teléfono y operación diaria.","map":"https://www.google.com/maps?q=12.11872,-86.26163","amenities":["Comida nicaragüense","Desayuno","Almuerzo","Cena","Atención en local"],"price_note":{"text":"Consultar precio, menú y horario con el establecimiento","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, 'published', 'territories-data.js', 'managua::cocina de dona haydee', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, business_type = excluded.business_type, municipality_id = excluded.municipality_id, description = excluded.description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, email = excluded.email, website_url = excluded.website_url,
  verification_status = excluded.verification_status, verified = excluded.verified, verified_at = excluded.verified_at,
  source_name = excluded.source_name, source_url = excluded.source_url, attributes = excluded.attributes
where public.businesses.updated_by = 'migration:territories';
insert into public.businesses (id, slug, name, category, business_type, department_id, municipality_id, municipality, description, latitude, longitude, location_precision, map_ready, address, phone, whatsapp, email, website_url, verification_status, verified, verified_at, source_name, source_url, source_type, attributes, status, legacy_source, legacy_key, created_by, updated_by)
values ('biz-restaurante-don-candido', 'restaurante-don-candido', 'Restaurante Don Cándido', 'restaurante', 'restaurante', 'managua', 'managua__managua', null, 'Restaurante especializado en cortes de carne, con ficha comercial activa y ubicación cartográfica verificada en Managua.', 12.12577, -86.26316, 'exact', true, '15 Av. Sureste, Managua', '+505 2277-2485', null, null, null, 'verified', true, '2026-10-05'::timestamptz, 'Google Business / OpenStreetMap', 'https://mapcarta.com/es/N1748771743', 'other', '{"modality":"Restaurantes","facts":"Restaurante especializado en cortes de carne, con ficha comercial activa y ubicación cartográfica verificada en Managua.","map":"https://www.google.com/maps?q=12.12577,-86.26316","amenities":["Cortes de carne","Almuerzo","Cena","Atención en local"],"price_note":{"text":"Consultar precio, menú y horario con el establecimiento","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, 'published', 'territories-data.js', 'managua::restaurante don candido', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, business_type = excluded.business_type, municipality_id = excluded.municipality_id, description = excluded.description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, email = excluded.email, website_url = excluded.website_url,
  verification_status = excluded.verification_status, verified = excluded.verified, verified_at = excluded.verified_at,
  source_name = excluded.source_name, source_url = excluded.source_url, attributes = excluded.attributes
where public.businesses.updated_by = 'migration:territories';
insert into public.businesses (id, slug, name, category, business_type, department_id, municipality_id, municipality, description, latitude, longitude, location_precision, map_ready, address, phone, whatsapp, email, website_url, verification_status, verified, verified_at, source_name, source_url, source_type, attributes, status, legacy_source, legacy_key, created_by, updated_by)
values ('biz-restaurante-el-eskimo', 'restaurante-el-eskimo', 'Restaurante El Eskimo', 'restaurante', 'restaurante', 'managua', 'managua__managua', null, 'Restaurante registrado cartográficamente en Managua y con ficha comercial activa.', 12.14409, -86.29012, 'exact', true, '18 y 19 Ave. Sur Oeste, Managua', '+505 2266-6313', null, null, null, 'verified', true, '2026-10-05'::timestamptz, 'Google Business / OpenStreetMap', 'https://mapcarta.com/es/N887537085', 'other', '{"modality":"Restaurantes","facts":"Restaurante registrado cartográficamente en Managua y con ficha comercial activa.","map":"https://www.google.com/maps?q=12.14409,-86.29012","amenities":["Restaurante","Comidas y bebidas"],"price_note":{"text":"Consultar precio, menú y horario con el establecimiento","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, 'published', 'territories-data.js', 'managua::restaurante el eskimo', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, business_type = excluded.business_type, municipality_id = excluded.municipality_id, description = excluded.description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, email = excluded.email, website_url = excluded.website_url,
  verification_status = excluded.verification_status, verified = excluded.verified, verified_at = excluded.verified_at,
  source_name = excluded.source_name, source_url = excluded.source_url, attributes = excluded.attributes
where public.businesses.updated_by = 'migration:territories';
insert into public.businesses (id, slug, name, category, business_type, department_id, municipality_id, municipality, description, latitude, longitude, location_precision, map_ready, address, phone, whatsapp, email, website_url, verification_status, verified, verified_at, source_name, source_url, source_type, attributes, status, legacy_source, legacy_key, created_by, updated_by)
values ('biz-restaurante-los-ranchos', 'restaurante-los-ranchos', 'Restaurante Los Ranchos', 'restaurante', 'restaurante', 'managua', 'managua__managua', null, 'Restaurante con presencia consolidada en Managua. La ficha comercial y OpenStreetMap confirman su ubicación.', 12.14443, -86.29049, 'exact', true, 'Distrito II, Managua', '+505 2266-0527', null, null, null, 'verified', true, '2026-10-05'::timestamptz, 'Google Business / OpenStreetMap', 'https://mapcarta.com/es/N887536144', 'other', '{"modality":"Restaurantes","facts":"Restaurante con presencia consolidada en Managua. La ficha comercial y OpenStreetMap confirman su ubicación.","map":"https://www.google.com/maps?q=12.14443,-86.29049","amenities":["Restaurante","Almuerzo","Cena","Atención en local"],"price_note":{"text":"Consultar precio, menú y horario con el establecimiento","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, 'published', 'territories-data.js', 'managua::restaurante los ranchos', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, business_type = excluded.business_type, municipality_id = excluded.municipality_id, description = excluded.description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, email = excluded.email, website_url = excluded.website_url,
  verification_status = excluded.verification_status, verified = excluded.verified, verified_at = excluded.verified_at,
  source_name = excluded.source_name, source_url = excluded.source_url, attributes = excluded.attributes
where public.businesses.updated_by = 'migration:territories';
insert into public.businesses (id, slug, name, category, business_type, department_id, municipality_id, municipality, description, latitude, longitude, location_precision, map_ready, address, phone, whatsapp, email, website_url, verification_status, verified, verified_at, source_name, source_url, source_type, attributes, status, legacy_source, legacy_key, created_by, updated_by)
values ('biz-kiosko-vilma', 'kiosko-vilma', 'Kiosko Vilma', 'kiosco', 'kiosco', 'managua', 'managua__managua', null, 'Kiosco y cafetería identificado públicamente dentro del Aeropuerto Internacional Augusto C. Sandino; también sirve de punto de referencia para el transporte turístico.', null, null, 'address', false, 'Aeropuerto Internacional Augusto C. Sandino, Managua', null, null, null, null, 'partial', false, '2026-10-05'::timestamptz, 'Google Business / Bigfoot Hostel', 'https://www.bigfoothostelleon.com/service-page/from-managua-airport-to-leon-shared-shuttle-23', 'other', '{"modality":"Kioscos","facts":"Kiosco y cafetería identificado públicamente dentro del Aeropuerto Internacional Augusto C. Sandino; también sirve de punto de referencia para el transporte turístico.","map":"https://www.google.com/maps/search/?api=1&query=Kiosko%20Vilma%20Managua%20Nicaragua","amenities":["Cafetería","Kiosco"],"price_note":{"text":"Consultar precio, menú y horario con el establecimiento","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, 'published', 'territories-data.js', 'managua::kiosko vilma', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, business_type = excluded.business_type, municipality_id = excluded.municipality_id, description = excluded.description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, email = excluded.email, website_url = excluded.website_url,
  verification_status = excluded.verification_status, verified = excluded.verified, verified_at = excluded.verified_at,
  source_name = excluded.source_name, source_url = excluded.source_url, attributes = excluded.attributes
where public.businesses.updated_by = 'migration:territories';
insert into public.businesses (id, slug, name, category, business_type, department_id, municipality_id, municipality, description, latitude, longitude, location_precision, map_ready, address, phone, whatsapp, email, website_url, verification_status, verified, verified_at, source_name, source_url, source_type, attributes, status, legacy_source, legacy_key, created_by, updated_by)
values ('biz-yemaya-reefs', 'yemaya-reefs', 'Yemaya Reefs', 'hospedaje', 'resort', 'raccs', 'raccs__corn_island', null, 'Hotel boutique frente al mar en Little Corn Island. Su web oficial confirma habitaciones frente a la playa, actividades acuáticas, wellness y prácticas de sostenibilidad.', 12.30195, -82.98502, 'reference', false, 'Northern End, Little Corn Island, Nicaragua', '+505 5830-2200', '+505 8415-5543', 'reservations.yemaya@colibriboutiquehotels.com', 'https://yemayalittlecorn.com/es/inicio/', 'verified', true, '2026-10-05'::timestamptz, 'Yemaya Reefs (sitio oficial)', 'https://yemayalittlecorn.com/es/inicio/', 'other', '{"modality":"Hospedajes","facts":"Hotel boutique frente al mar en Little Corn Island. Su web oficial confirma habitaciones frente a la playa, actividades acuáticas, wellness y prácticas de sostenibilidad.","amenities":["Habitaciones frente al mar","Spa/wellness","Kayak","Snorkel","Paddleboard","Restaurante"],"price_note":{"text":"Consultar disponibilidad y tarifa","checked_at":"2026-10-05","status":"por_estructurar_en_prices"}}'::jsonb, 'published', 'territories-data.js', 'raccs::yemaya reefs', 'migration:territories', 'migration:territories')
on conflict (legacy_source, legacy_key) where legacy_key is not null do update set
  name = excluded.name, business_type = excluded.business_type, municipality_id = excluded.municipality_id, description = excluded.description,
  latitude = excluded.latitude, longitude = excluded.longitude, location_precision = excluded.location_precision, map_ready = excluded.map_ready,
  address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, email = excluded.email, website_url = excluded.website_url,
  verification_status = excluded.verification_status, verified = excluded.verified, verified_at = excluded.verified_at,
  source_name = excluded.source_name, source_url = excluded.source_url, attributes = excluded.attributes
where public.businesses.updated_by = 'migration:territories';
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-rosquillas-delicias-del-norte', 'Mapa Nacional de Turismo', 'https://www.mapanicaragua.com/municipio-de-somoto/', 'media', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-rosquillas-delicias-del-norte', 'INTUR', 'https://www.intur.gob.ni/2015/06/25/mpymes-de-granada-y-madriz-intercambian-experiencias/', 'government', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-finca-entre-pinos', 'INTUR · Catálogo de Iniciativas de Turismo Rural y Comunitario (2026)', null, 'government', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-casa-de-huesped-la-ceibita', 'INTUR · Catálogo de Iniciativas de Turismo Rural y Comunitario (2026)', null, 'government', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-rio-esteli', 'GeoNames', 'https://mapcarta.com/es/19584058', 'osm', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-volcan-telica', 'INETER (catálogo de naturaleza 2026)', null, 'government', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-isla-juan-venado', 'Wikidata / Mapa Nacional de Turismo', 'https://www.mapanicaragua.com/sol-y-playa/', 'media', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('business', 'biz-poco-a-poco-hostel', 'Poco a Poco Hostel (sitio oficial)', 'https://www.pocoapocohostel.com/', 'business_official', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('business', 'biz-poco-a-poco-hostel', 'Mapcarta / OpenStreetMap', 'https://mapcarta.com/N4595638290', 'osm', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-rancho-los-alpes', 'INTUR · Catálogo de Iniciativas de Turismo Rural y Comunitario (2026)', null, 'government', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-playa-las-penitas', 'Mapa Nacional de Turismo / GeoNames', 'https://www.mapanicaragua.com/sol-y-playa/', 'media', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-playa-poneloya', 'Mapa Nacional de Turismo / GeoNames', 'https://www.mapanicaragua.com/videos/', 'media', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('business', 'biz-hotel-el-convento', 'OpenStreetMap / GeoNames / Wikidata', 'https://mapcarta.com/es/32808130', 'osm', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('business', 'biz-hotel-el-convento', 'Mapcarta / OpenStreetMap', 'https://mapcarta.com/es/32808130', 'osm', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('business', 'biz-comedor-la-cucaracha', 'Near-Place / Google Business', 'https://ni.near-place.com/comedor-la-cucaracha-leon', 'directory', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-reserva-de-biosfera-isla-de-ometepe', 'INTUR', 'https://www.intur.gob.ni/recinto/isla-de-ometepe/', 'government', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-reserva-de-biosfera-isla-de-ometepe', 'Visit Nicaragua', 'https://www.visitanicaragua.com/islas/isla-de-ometepe/', 'media', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-volcan-concepcion', 'Visit Nicaragua / OpenStreetMap (catálogo de naturaleza 2026)', null, 'osm', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-volcan-maderas', 'Visit Nicaragua / OpenStreetMap (catálogo de naturaleza 2026)', null, 'osm', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-cascada-de-san-ramon', 'Visit Nicaragua', 'https://www.visitanicaragua.com/islas/isla-de-ometepe/', 'media', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-san-juan-del-sur-y-cristo-de-la-misericordia', 'Mapa Nacional de Turismo', 'https://www.mapanicaragua.com/municipio-de-san-juan-del-sur/', 'media', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-san-juan-del-sur-y-cristo-de-la-misericordia', 'Mapa Nacional de Turismo', 'https://www.mapanicaragua.com/arquitectura-de-san-juan-del-sur/page/4/', 'media', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-maderas-marsella-remanso-hermosa-y-el-coco', 'INTUR', 'https://www.intur.gob.ni/2021/09/13/torneo-centroamericano-de-surf-se-despide-de-playa-maderas/', 'government', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-maderas-marsella-remanso-hermosa-y-el-coco', 'Mapa Nacional de Turismo', 'https://www.mapanicaragua.com/municipio-de-san-juan-del-sur/', 'media', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-refugio-de-vida-silvestre-la-flor', 'MARENA', 'https://www.marena.gob.ni/2026/09/08/ii-arribada-de-tortugas-en-la-flor/', 'government', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-refugio-de-vida-silvestre-la-flor', 'MARENA', 'https://www.marena.gob.ni/2025/04/15/refugio-de-vida-silvestre-la-flor-en-san-juan-del-sur-un-sitio-para-descubrir-en-semana-santa/', 'government', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('business', 'biz-morgan-s-rock-reserve-ecolodge', 'Morgan''s Rock (sitio oficial)', 'https://www.morgansrock.com/stay/', 'business_official', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('business', 'biz-morgan-s-rock-reserve-ecolodge', 'Wikidata', 'https://www.wikidata.org/wiki/Q125863965', 'wikidata', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-hostal-puesta-del-sol-ometepe', 'INTUR · Catálogo de Iniciativas de Turismo Rural y Comunitario (2026)', null, 'government', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-finca-magdalena-ometepe', 'INTUR · Catálogo de Iniciativas de Turismo Rural y Comunitario (2026)', null, 'government', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-playa-san-juan-del-sur', 'Visit Nicaragua / Mapcarta-OSM', 'https://visitanicaragua.com/en/beaches/San-Juan-del-Sur-beach/', 'osm', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-playa-maderas', 'Visit Nicaragua / OpenStreetMap', 'https://www.visitanicaragua.com/playas/playa-maderas/', 'osm', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-playa-remanso', 'Mapa Nacional de Turismo / OpenStreetMap', 'https://www.mapanicaragua.com/municipio-de-san-juan-del-sur/', 'osm', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-playa-el-coco', 'Mapa Nacional de Turismo', 'https://www.mapanicaragua.com/sol-y-playa/', 'media', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-popoyo-y-guasacate', 'Mapa Nacional de Turismo / OpenStreetMap', 'https://www.mapanicaragua.com/sol-y-playa/', 'osm', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-playa-gigante', 'Mapa Nacional de Turismo / Wikidata-OSM', 'https://www.mapanicaragua.com/videos/', 'media', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('business', 'biz-hotel-victoriano', 'Hotel Victoriano (sitio oficial)', 'https://www.hotelvictoriano.com/nosotros.php', 'business_official', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('business', 'biz-hotel-victoriano', 'Mapcarta / OpenStreetMap', 'https://mapcarta.com/es/W415533338', 'osm', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('business', 'biz-totoco-eco-resort', 'TOTOCO Eco Resort (sitio oficial)', 'https://www.totoco-resort.com/contact', 'business_official', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('business', 'biz-totoco-eco-resort', 'Near-Place / referencia cartográfica', 'https://ni.near-place.com/totoco-eco-lodge-callejon-de-la-palmera-800m-arriba-balgue', 'directory', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-lago-de-apanas', 'Wikidata / OpenStreetMap (catálogo de naturaleza 2026)', null, 'osm', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-reserva-natural-cerro-datanli-el-diablo', 'Mapa Nacional de Turismo (catálogo de naturaleza 2026)', null, 'media', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-cerro-kilambe-y-aguas-termales-de-el-cano', 'Mapa Nacional de Turismo (catálogo de naturaleza 2026)', null, 'media', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-cascada-la-bujona', 'OpenStreetMap', 'https://mapcarta.com/es/N6907277586', 'osm', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-parque-nacional-volcan-masaya', 'MARENA', 'https://www.marena.gob.ni/2026/07/17/mas-visitas-en-volcan-masaya/', 'government', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-parque-nacional-volcan-masaya', 'MARENA', 'https://www.marena.gob.ni/2025/12/20/marena-anuncia-reapertura-de-la-plaza-oviedo-del-parque-nacional-volcan-masaya/', 'government', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-mirador-de-catarina', 'Visit Nicaragua (catálogo de naturaleza 2026)', null, 'media', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-posada-ecologica-la-abuela-laguna-de-apoyo', 'Sitio oficial', 'https://www.posadaecologicalaabuela.com.ni/Page/Contacto', 'business_official', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-posada-ecologica-la-abuela-laguna-de-apoyo', 'Sitio oficial', 'https://www.posadaecologicalaabuela.com.ni/Page/Servicios', 'business_official', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-volcan-masaya-caldera-santiago', 'INETER / Visit Nicaragua (catálogo de naturaleza 2026)', null, 'government', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-centro-historico-y-calle-la-calzada', 'Mapa Nacional de Turismo', 'https://www.mapanicaragua.com/local/calle-la-calzada/', 'media', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-centro-historico-y-calle-la-calzada', 'Mapa Nacional de Turismo', 'https://www.mapanicaragua.com/granada/', 'media', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-convento-e-iglesia-san-francisco', 'Mapa Nacional de Turismo', 'https://www.mapanicaragua.com/municipio-de-granada/', 'media', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-convento-e-iglesia-san-francisco', 'Mapa Nacional de Turismo', 'https://www.mapanicaragua.com/arquitectura-de-granada/page/2/', 'media', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-isletas-de-granada', 'Visit Nicaragua / GeoNames', 'https://www.visitanicaragua.com/atractivos/islas/', 'media', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-lago-cocibolca', 'OpenStreetMap / GeoNames (catálogo de naturaleza 2026)', null, 'osm', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('business', 'biz-hotel-dario', 'OpenStreetMap / GeoNames / Wikidata', 'https://mapcarta.com/es/32290446', 'osm', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('business', 'biz-hotel-dario', 'Mapcarta / OpenStreetMap', 'https://mapcarta.com/es/32290446', 'osm', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('business', 'biz-treehouse-nicaragua', 'Treehouse Nicaragua (sitio oficial)', 'https://www.treehousenicaragua.com/hostel', 'business_official', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('business', 'biz-treehouse-nicaragua', 'Dirección oficial / Google Hotels', 'https://www.treehousenicaragua.com/find-us', 'media', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-finca-el-rayo', 'INTUR · Catálogo de Iniciativas de Turismo Rural y Comunitario (2026)', null, 'government', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-eco-finca-el-buen-pastor', 'INTUR · Catálogo de Iniciativas de Turismo Rural y Comunitario (2026)', null, 'government', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-finca-maria-auxiliadora', 'INTUR · Catálogo de Iniciativas de Turismo Rural y Comunitario (2026)', null, 'government', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-rio-tipitapa', 'GeoNames / Wikidata', 'https://mapcarta.com/es/19577744', 'osm', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('place', 'pl-isla-zapatera', 'MARENA / GeoNames', 'https://www.marena.gob.ni/wp-content/uploads/2023/08/11-Plan-de-Manejo-Parque-Nacional-Archipielago-Zapatera.pdf', 'government', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('business', 'biz-hotel-plaza-colon', 'Hotel Plaza Colón (sitio oficial)', 'https://hotelplazacolon.com/es/inicio/', 'business_official', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('business', 'biz-hotel-plaza-colon', 'Mapcarta / OpenStreetMap', 'https://mapcarta.com/34348452', 'osm', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('business', 'biz-restaurante-el-zaguan', 'Google Business / OpenStreetMap', 'https://mapcarta.com/es/W419754191', 'osm', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('business', 'biz-boca-baco', 'Sitio oficial Boca Baco', 'https://bocabaconicaragua.com/english-menu/', 'business_official', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
insert into public.verification_sources (entity_type, entity_id, source_name, source_url, source_type, verified_at, expires_at, verified_by, status)
values ('business', 'biz-comedor-dona-tulita', 'Near-Place / Google Business', 'https://ni.near-place.com/comedor-dona-tulita-w2jvw33-calle-el-hormiguero-granada/en', 'directory', '2026-10-05'::timestamptz, '2026-10-05'::timestamptz + interval '1 year', 'migration:territories', 'active')
on conflict (entity_type, entity_id, source_name, source_url) do nothing;
commit;
